# Generated by Django 3.1.8 on 2021-04-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210415_1607'),
        ('csw', '0003_auto_20210415_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestresult',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_results', to='service.metadata'),
        ),
    ]
