# Generated by Django 3.1.7 on 2021-04-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0004_auto_20210415_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestresult',
            options={'ordering': ['-created']},
        ),
    ]
