# Generated by Django 3.1.8 on 2021-04-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210415_1607'),
        ('csw', '0004_auto_20210415_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harvestresult',
            unique_together={('metadata', 'timestamp_end')},
        ),
    ]
