# Generated by Django 3.2.9 on 2021-12-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='web_feature_service',
            field=models.ForeignKey(blank=True, help_text='Select the service you want to subscribe. When you edit an existing subscription, you can not change this selection.', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.webfeatureservice', verbose_name='web feature service'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='web_map_service',
            field=models.ForeignKey(blank=True, help_text='Select the service you want to subscribe. When you edit an existing subscription, you can not change this selection.', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.webmapservice', verbose_name='web map service'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='from_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pending_publish_requests', to='accounts.organization', verbose_name='requesting organization'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='to_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pending_publish_requests', to='accounts.organization', verbose_name='requested organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('web_map_service', 'web_feature_service', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='publishrequest',
            unique_together={('from_organization', 'to_organization')},
        ),
    ]
