# Generated by Django 3.2.9 on 2022-01-04 15:34
import os

from django.contrib.auth import get_user_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):

        superuser = get_user_model().objects.create_superuser(
            username=os.environ.get("MRMAP_USER"),
            password=os.environ.get("MRMAP_PASSWORD")
        )
        superuser.is_active = True
        superuser.save()

    def generate_testorganization(apps, schema_editor):
        if os.environ.get('MRMAP_PRODUCTION', False):

            Organization = apps.get_model("accounts", "Organization")
            Organization.objects.create(name="Testorganization")

    operations = [
        migrations.RunPython(generate_superuser),
        migrations.RunPython(generate_testorganization),
    ]
