# Generated by Django 3.2.9 on 2022-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, help_text='json storage on backend to provide configurations for frontends.', null=True, verbose_name='settings'),
        ),
    ]
