# Generated by Django 3.2.9 on 2022-02-22 11:21

import accounts.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=accounts.models.users.get_settings, help_text='json storage on backend to provide configurations for frontends.', verbose_name='settings'),
        ),
    ]
