<<<<<<< HEAD
# Generated by Django 3.1 on 2021-03-11 15:39
=======
# Generated by Django 3.1.7 on 2021-03-11 09:56
>>>>>>> cc6b21af7f0e12c81a045cc53f7959a2f36f6be3

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csw', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestresult',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
