version: '3.8'
services:
  mrmap-postgis:
    image: mdillon/postgis:11-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: mrmap
      POSTGRES_PASSWORD: mrmap
    volumes:
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
  mrmap-redis:
    image: library/redis:6.2-alpine
    ports:
      - 5556:6379
    volumes:
      - ./redis/redis_data:/data
  mrmap-mapserver:
    image: camptocamp/mapserver:7.6
    ports:
      - 5557:80
    volumes:
      - ./mapserver/mapfiles:/etc/mapserver
  #mrmap-wsgi:
  #  build:
  #    context: ./wsgi
  #  command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn mydjango.wsgi -b 0.0.0.0:8000"
  #  depends_on:
  #    - mrmap-postgis
  #  volumes:
  #    - ../:/src
  #  expose:
  #    - "8000"
  mrmap-nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/mrmap.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/static:/opt/mrmap/mrmap
    extra_hosts:
      - host.docker.internal:host-gateway

#  mrmap-etf-webapp:
#    image: wetransform/etf-webapp:2.0.1-20190716
#    ports:
#      - 8091:8080
#    volumes:
#      - ./etf/:/etf
#  mrmap-inspire-validator:
#    build:
#      context: ./inspire-validator
#    ports:
#      - 8092:8080
# MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    networks:
      - graylog
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge