# Generated by Django 3.1.8 on 2021-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', help_text='Describe what this job does.', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
    ]
