# Generated by Django 3.1.8 on 2021-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.TextField(default=''),
        ),
    ]
