# Generated by Django 3.1.8 on 2021-06-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210609_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-done_at']},
        ),
    ]
