from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext as __
from django.views.generic.base import ContextMixin
from django_filters.views import FilterView
from extras.enums.bootstrap import BadgeColorEnum
from extras.views import (SecuredCreateView, SecuredDeleteView, SecuredDependingListMixin,
                          SecuredDetailView, SecuredListMixin, SecuredUpdateView)
from MrMap.icons import IconEnum, get_icon
from MrMap.messages import PUBLISH_REQUEST_ACCEPTED, PUBLISH_REQUEST_DENIED
from MrMap.views import CustomSingleTableMixin

from users.forms.groups import OrganizationChangeForm
from users.models.groups import Organization, PublishRequest
from users.tables.groups import OrganizationTable, OrganizationDetailTable, OrganizationPublishersTable, PublishesRequestTable


class OrganizationDetailContextMixin(ContextMixin):
    object = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tab_nav = [{'url': self.object.get_absolute_url,
                    'title': _('Details')},
                   {'url': self.object.publishers_uri,
                    'title': _('Publishers ').__str__() + f'<span class="badge {BadgeColorEnum.SECONDARY.value}">New</span>'},
                   ]
        context.update({"object": self.object,
                        # FIXME: use functions from GenericModelMixin instead to provide actions
                        #'actions': self.object.get_actions(),
                        'tab_nav': tab_nav,
                        'publisher_requests_count': PublishRequest.objects.filter(from_organization=self.object).count()})
        return context


class OrganizationTableView(SecuredListMixin, FilterView):
    model = Organization
    table_class = OrganizationTable
    filterset_fields = {'name': ['icontains'],
                        'description': ['icontains']}


class OrganizationCreateView(SecuredCreateView):
    model = Organization


class OrganizationDetailView(OrganizationDetailContextMixin, SecuredDetailView):
    class Meta:
        verbose_name = _('Details')

    model = Organization
    template_name = 'MrMap/detail_views/table_tab.html'
    title = _('Details')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        details_table = OrganizationDetailTable(
            data=[self.object, ], request=self.request)
        context.update({'table': details_table})
        return context


class OrganizationUpdateView(SecuredUpdateView):
    model = Organization
    form_class = OrganizationChangeForm 


class OrganizationDeleteView(SecuredDeleteView):
    model = Organization
    queryset = Organization.objects.filter(is_autogenerated=False)

    def get_msg_dict(self):
        return {'name': self.get_object().name}


class OrganizationPublishersTableView(SecuredDependingListMixin, OrganizationDetailContextMixin, CustomSingleTableMixin, FilterView):
    model = Organization
    depending_model = Organization
    table_class = OrganizationPublishersTable
    filterset_fields = {'name': ['icontains']}
    template_name = 'MrMap/detail_views/table_tab.html'
    object = None
    title = get_icon(IconEnum.PUBLISHERS) + __(' Publish for list')

    def get_queryset(self):
        return self.object.get_publishers()

    """def get_table_kwargs(self):
        return {'organization': self.object}"""


class PublishRequestCreateView(SecuredCreateView):
    model = PublishRequest
    fields = ('from_organization', 'to_organization', 'message')

    # FIXME: find a better solution to handle request keword argument with forms.ModelForm classes
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.pop("request")
        return kwargs


class PublishRequestTableView(SecuredListMixin, FilterView):
    model = PublishRequest
    table_class = PublishesRequestTable
    filterset_fields = ['from_organization', 'to_organization', 'message']


class PublishRequestUpdateView(SecuredUpdateView):
    model = PublishRequest
    fields = ('is_accepted', )
    success_message = PUBLISH_REQUEST_ACCEPTED
    title = _('Accept request')

    def get_success_url(self):
        return self.object.to_organization.get_absolute_url()

    # FIXME: find a better solution to handle request keword argument with forms.ModelForm classes
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.pop("request")
        return kwargs


class PublishRequestRemoveView(SecuredDeleteView):
    model = PublishRequest
    success_message = PUBLISH_REQUEST_DENIED
    title = _('Deny request')
