env:
  browser: true
  es2021: true
  node: true
  jest: true
globals:
  window: true
  document: true
  localStorage: true
  sessionStorage: true
  URLSearchParams: true
  FormData: true
  FileReader: true
  File: true
  jest: true
  describe: true
  it: true
  afterEach: true
  beforeEach: true
  expect: true
extends:
  - react-app
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - import
settings:
  react:
    version: detect
rules:
  indent:
    - error
    - 2
  quotes:
    - 2
    - single
    - avoidEscape: true
  no-console:
    - warn
    - allow:
        - info
        - warn
        - error
  semi:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  no-unused-vars: 0
  no-debugger: 0
  no-prototype-builtins: 1
  no-shadow: 1
  no-multiple-empty-lines: 1
  camelcase:
    - error
    - allow:
        - "jwt_decode"
  max-len:
    - 2
    - 120
    - ignorePattern: "^import"
  eol-last:
    - error
    - always
  no-use-before-define: 0
  jsx-quotes:
    - error
    - prefer-single
  import/export: warn
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
        - unknown
      newlines-between: always-and-inside-groups
      alphabetize:
        order: asc
        caseInsensitive: true
      pathGroups:
        # enforce react imports to be at the top of imports
        - pattern: react
          group: builtin
          position: before
      pathGroupsExcludedImportTypes:
        - react
overrides:
  - files:
      - "**/*.tsx"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.js"
    rules:
      react/prop-types: 0
      "@typescript-eslint/no-use-before-define": 1
      "@typescript-eslint/no-empty-interface": 1
      "@typescript-eslint/no-unused-vars": 2
      "@typescript-eslint/no-explicit-any": 0
      "@typescript-eslint/ban-ts-comment": 0
      "@typescript-eslint/no-shadow": 1
