version: 2

build:
  apt_packages:
    - gdal-bin
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - python -m sphinx -T -E -W --keep-going -b linkcheck -d _build/linkcheck -D language=en . $READTHEDOCS_OUTPUT/html
python:
  # Install our python package before building the docs
  install:
    - requirements: mrmap/requirements.txt

sphinx:
  fail_on_warning: true
