version: 2

build:
  apt_packages:
    - gdal-bin
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt

sphinx:
  fail_on_warning: true
