version: '3.8'
services:
  postgis:
    ports:
      5432:5432
  test:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    command: >
      /bin/bash -c "python manage.py test --noinput"
    hostname: "mrmap-test"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    networks:
      - backend
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis