version: '3.8'
services:
  postgis:
    image: mdillon/postgis:11-alpine
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    env_file:
      - ./.env.db
  redis:
    image: library/redis:6.2-alpine
    volumes:
      - type: volume
        source: mem-db-data
        target: /data
  mapserver:
    image: camptocamp/mapserver:7.6
    volumes:
      - type: bind
        source: ./docker/mapserver/mapfiles
        target: /etc/mapserver
  nginx:
    build:
      context: ./mrmap
      dockerfile: ../docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./docker/nginx/mrmap.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: app-static
        target: /opt/mrmap/static
    extra_hosts:
      - host.docker.internal:host-gateway
  #inspire-validator:
  #  build:
  #    context: ./docker/inspire-validator
  app:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: app-static
        target: /var/www/mrmap/static
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis
      - mapserver
      - nginx
      #- inspire-validator
volumes:
  app-static:
  db-data:
  mem-db-data: