# docker compose file for productive useage
version: '3.8'
services:
  postgis:
    image: postgis/postgis:14-3.1-alpine
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    networks:
      - mrmap-internal
    env_file:
      - ./docker/postgis/.db.env
  redis:
    image: library/redis:6.2-alpine
    volumes:
      - type: volume
        source: mem-db-data
        target: /data
    networks:
      - mrmap-internal
  mapserver:
    image: camptocamp/mapserver:7.6
    volumes:
      - type: bind
        source: ./docker/mapserver/mapfiles
        target: /etc/mapserver
    networks:
      - mrmap-internal
  nginx:
    build:
      context: ./backend
      dockerfile: ../docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    hostname: "mrmap-nginx"
    volumes:
      - type: bind
        source: ./docker/nginx/mrmap.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: mrmap-static
        target: /var/www/mrmap/static
    networks:
      - mrmap-internal
    extra_hosts:
      - host.docker.internal:host-gateway

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    hostname: "mrmap-frontend"
    volumes:
      - type: bind
        source: ./frontend/src
        target: /opt/mrmap/src
      - type: bind
        source: ./frontend/public
        target: /opt/mrmap/public
    networks:
      - mrmap-internal
    env_file:
      - docker/frontend/.mrmap.env
    working_dir: "/opt/mrmap"
    command: "npm start"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    tty: true # To support colorized log output.
    entrypoint: /opt/mrmap/.bash_scripts/entrypoint.sh
    command: /bin/bash -c "gunicorn -b 0.0.0.0:8001 -k uvicorn.workers.UvicornWorker --workers=4 --reload --log-level=info --timeout=0 MrMap.asgi:application"
    hostname: "mrmap-backend"
    volumes:
      - type: bind
        source: ./backend
        target: /opt/mrmap
      - type: volume
        source: mrmap-static
        target: /var/www/mrmap/static
      - type: volume
        source: mrmap-media
        target: /var/mrmap/media
      - type: volume
        source: mrmap-log
        target: /var/log/mrmap
    networks:
      - mrmap-internal
    env_file:
      - docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis
      - mapserver
  celery-default-worker:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    command: >
      /bin/bash -c "celery -A MrMap worker -E -l INFO -n default -Q default"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-default-worker"
    volumes:
      - type: bind
        source: ./backend
        target: /opt/mrmap
      - type: volume
        source: mrmap-media
        target: /var/mrmap/media
      - type: volume
        source: mrmap-log
        target: /var/log/mrmap
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis
  celery-download-worker:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    command: >
      /bin/bash -c "celery -A MrMap worker -E -l INFO -n download -Q download"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-worker"
    volumes:
      - type: bind
        source: ./backend
        target: /opt/mrmap
      - type: volume
        source: mrmap-media
        target: /var/mrmap/media
      - type: volume
        source: mrmap-log
        target: /var/log/mrmap
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis

  celery-db-calc-worker:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    command: >
      /bin/bash -c "celery -A MrMap worker -E -l INFO -n db-calc -Q db-calc"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-worker"
    volumes:
      - type: bind
        source: ./backend
        target: /opt/mrmap
      - type: volume
        source: mrmap-media
        target: /var/mrmap/media
      - type: volume
        source: mrmap-log
        target: /var/log/mrmap
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis

volumes:
  mrmap-static: null
  mrmap-media: null
  mrmap-log: null
  db-data: null
  mem-db-data:

    null
networks:
  mrmap-internal: null
