# docker compose file for development with visual studio code
version: "3.8"
services:
  gunicorn:
    build:
      args:
        MRMAP_PRODUCTION: "False"
    command: >
      /bin/bash -c "echo 'waiting for debugging client...' && python -u -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m gunicorn -b 0.0.0.0:8001 -k uvicorn.workers.UvicornWorker --workers=4 --reload --log-level=debug --timeout=0 MrMap.asgi:application"
    environment:
      PYDEVD_LOAD_VALUES_ASYNC: "True"
      PYTHONUNBUFFERED: "1"
      IPYTHONENABLE: "True"
    ports:
      - "0.0.0.0:3001:5678"
    working_dir: "/opt/mrmap"
    stdin_open: true
  
  celery-default-worker:
    build:
      args:
        MRMAP_PRODUCTION: "False"
    command: >
      /bin/bash -c "echo 'waiting for debugging client...' && python -u -m debugpy --listen 0.0.0.0:5678 --wait-for-client /usr/local/bin/watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A MrMap worker -E -l DEBUG -n default -Q default"
    environment:
      PYDEVD_LOAD_VALUES_ASYNC: "True"
      PYTHONUNBUFFERED: "1"
      IPYTHONENABLE: "True"
    ports:
      - "0.0.0.0:3002:5678"

  celery-download-worker:
    build:
      args:
        MRMAP_PRODUCTION: "False"
    command: >
      /bin/bash -c "echo 'waiting for debugging client...' && python -u -m debugpy --listen 0.0.0.0:5678 --wait-for-client /usr/local/bin/watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A MrMap worker -E -l DEBUG -n download -Q download_iso_metadata,download_described_elements,harvest"
    environment:
      PYDEVD_LOAD_VALUES_ASYNC: "True"
      PYTHONUNBUFFERED: "1"
      IPYTHONENABLE: "True"
    ports:
      - "0.0.0.0:3003:5678"