version: '3.8'


services:
  mrmap-postgis:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_USER: mrmap
      POSTGRES_PASSWORD: mrmap  # in productive setup you shall change this password
    volumes:
      - ./docker/postgis/postgresql_data:/var/lib/postgresql/data:Z

  #mrmap-redis:
  #  image: library/redis:6.2-alpine
  #  #ports:
  #  #  - "5556:6379"
  #  volumes:
  #    - ./docker/redis/redis_data:/data

  #mrmap-mapserver:
  #  image: camptocamp/mapserver:7.6
  #  #ports:
  #  #  - "5557:80"
  #  volumes:
  #    - ./docker/mapserver/mapfiles:/etc/mapserver

  mrmap-nginx:
    build:
      context: ./mrmap
      dockerfile: ../docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/mrmap.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/mrmap/static:/opt/mrmap/static
    extra_hosts:
      - host.docker.internal:host-gateway


  #mrmap-inspire-validator:
  #  build:
  #    context: ./docker/inspire-validator
  #  ports:
  #    - "8092:8080"

  mrmap-app:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    volumes:
      - ./docker/mrmap/static:/opt/mrmap/static
    depends_on:
      - mrmap-postgis


