# docker compose file for productive useage
version: '3.8'
services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    networks:
      - mrmap-internal
    env_file:
      - ./docker/postgis/.db.env
  redis:
    image: library/redis:7.2.0-alpine
    volumes:
      - type: volume
        source: mem-db-data
        target: /data
    networks:
      - mrmap-internal
  mapserver:
    image: camptocamp/mapserver:7.6
    volumes:
      - type: bind
        source: ./docker/mapserver/mapfiles
        target: /etc/mapserver/mapfiles
      - type: bind
        source: ./docker/mapserver/shapefiles
        target: /etc/mapserver/shapefiles
    networks:
      - mrmap-internal

  backend:
    build:
      context: ./mrmap
      dockerfile: ../docker/backend/alpine.Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    tty: true # To support colorized log output.
    hostname: "mrmap-backend"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: backend-static
        target: /var/www/mrmap/backend
      - type: volume
        source: backend-media
        target: /var/mrmap/backend/media
      - type: volume
        source: backend-log
        target: /var/log/mrmap/backend
      - type: volume
        source: backend-import
        target: /var/mrmap/import
    networks:
      - mrmap-internal
    env_file:
      - docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis
      - mapserver
    ports:
      - "0.0.0.0:8001:8001"

  celery-worker-default:
    build:
      context: ./mrmap
      dockerfile: ../docker/backend/alpine.Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    # deploy:
    #   replicas: 10
    command: >
      /bin/sh -c "celery -A MrMap worker -E -l INFO -Q default"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-worker"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: backend-media
        target: /var/mrmap/backend/media
      - type: volume
        source: backend-log
        target: /var/log/mrmap/backend
      - type: volume
        source: backend-import
        target: /var/mrmap/import
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis

  celery-worker-download:
    build:
      context: ./mrmap
      dockerfile: ../docker/backend/alpine.Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    # deploy:
    #   replicas: 10
    command: >
      /bin/sh -c "celery -A MrMap worker -E -l INFO -Q download"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-worker"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: backend-media
        target: /var/mrmap/backend/media
      - type: volume
        source: backend-log
        target: /var/log/mrmap/backend
      - type: volume
        source: backend-import
        target: /var/mrmap/import
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis

  celery-worker-db-routines:
    build:
      context: ./mrmap
      dockerfile: ../docker/backend/alpine.Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    # deploy:
    #   replicas: 10
    command: >
      /bin/sh -c "celery -A MrMap worker -E -l INFO -Q routines"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-worker"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: backend-media
        target: /var/mrmap/backend/media
      - type: volume
        source: backend-log
        target: /var/log/mrmap/backend
      - type: volume
        source: backend-import
        target: /var/mrmap/import
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis

  celery-beat:
    build:
      context: ./mrmap
      dockerfile: ../docker/backend/alpine.Dockerfile
      args:
        MRMAP_PRODUCTION: "True"
    command: >
      /bin/sh -c "celery -A MrMap beat --loglevel INFO --scheduler django"
    tty: true # To support colorized log output.
    hostname: "mrmap-celery-beat"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: backend-media
        target: /var/mrmap/backend/media
      - type: volume
        source: backend-log
        target: /var/log/mrmap/backend
      - type: volume
        source: backend-import
        target: /var/mrmap/import
    networks:
      - mrmap-internal
    env_file:
      - ./docker/backend/.mrmap.env
    depends_on:
      - postgis
      - redis

volumes:
  backend-static: null
  backend-media: null
  backend-log: null
  backend-import: null
  db-data: null
  mem-db-data:

    null
networks:
  mrmap-internal: null
