# docker compose file for development useage
version: '3.8'
services:
  test:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    entrypoint: /opt/mrmap/.bash_scripts/wait_db.sh
    command:
      /bin/bash -c "python manage.py test"
    hostname: "mrmap-test"
    volum
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    networks:
      - backend
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis

  behave:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    entrypoint: /opt/mrmap/.bash_scripts/wait_db.sh
    command:
      /bin/bash -c "python manage.py behave"
    hostname: "mrmap-behave"
    volum
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    networks:
      - backend
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis