# docker compose file for development useage
version: '3.8'
services:
  test:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
      args: 
        MRMAP_PRODUCTION: 'False'
    entrypoint: /opt/mrmap/.bash_scripts/wait_db.sh
    command:
      /bin/bash -c "coverage run manage.py test && coverage xml -i -o behave-coverage-report.xml"
    hostname: "mrmap-test"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    networks:
      - backend
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis

  behave:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
      args: 
        MRMAP_PRODUCTION: 'False'
    entrypoint: /opt/mrmap/.bash_scripts/wait_db.sh
    command:
      /bin/bash -c "coverage run manage.py behave"
    hostname: "mrmap-behave"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    networks:
      - backend
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis