# docker compose file for development with visual studio code
version: "3.8"
services:

  appserver:
    command: >
      /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/mrmap/manage.py runserver 0.0.0.0:8001"
    ports:
      - "0.0.0.0:3001:5678"
  
  celery-default-worker:
    command: >
      /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678 -m celery -A MrMap worker -E -l DEBUG -n default -Q default"
    ports:
      - "0.0.0.0:3002:5678"

  celery-download-worker:
    command: >
      /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678 -m celery -A MrMap worker -E -l DEBUG -n download -Q download_iso_metadata,download_described_elements,harvest"
    ports:
      - "0.0.0.0:3003:5678"