version: '3.8'
services:
  mrmap-postgis:
    image: mdillon/postgis:11-alpine
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  mrmap-redis:
    image: library/redis:6.2-alpine
    volumes:
      - type: volume
        source: mem-db-data
        target: /data
  mrmap-mapserver:
    image: camptocamp/mapserver:7.6
    volumes:
      - type: bind
        source: ./docker/mapserver/mapfiles
        target: /etc/mapserver
  mrmap-nginx:
    build:
      context: ./mrmap
      dockerfile: ../docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./docker/nginx/mrmap.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: app-static
        target: /opt/mrmap/static
    extra_hosts:
      - host.docker.internal:host-gateway
  #mrmap-inspire-validator:
  #  build:
  #    context: ./docker/inspire-validator
  mrmap-app:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    command:
      /opt/mrmap/start.sh
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
      - type: volume
        source: app-static
        target: /var/www/mrmap/static
    env_file:
      - ./.env.dev
    depends_on:
      - mrmap-postgis
      - mrmap-redis
      - mrmap-mapserver
      #- mrmap-inspire-validator
volumes:
  app-static:
  db-data:
  mem-db-data: