version: '3.8'
services:
  test:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    command: >
      /bin/bash -c "python manage.py test"
    hostname: "mrmap-test"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis

  behave:
    build:
      context: ./mrmap
      dockerfile: ../docker/mrmap/Dockerfile
    command: >
      /bin/bash -c "python manage.py behave --noinput"
    hostname: "mrmap-behave"
    volumes:
      - type: bind
        source: ./mrmap
        target: /opt/mrmap
    env_file:
      - ./.env.mrmap
    depends_on:
      - postgis
      - redis