site_name: MrMap Documentation
site_url: https://mrmap.readthedocs.io/
repo_url: https://github.com/mrmap-community/mrmap
python:
    version: 3.7
    install:
        - requirements: docs/requirements.txt
theme:
    name: readthedocs
    navigation_depth: 3


markdown_extensions:
    - admonition:
    - codehilite:
    - markdown_include.include:
        headingOffset: 1
    - pymdownx.arithmatex:
        generic: true


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
    - Introduction: 'index.md'
    - Installation:
          - Installing MrMap: 'installation/index.md'
          - 1. PostgreSQL: 'installation/1-postgresql.md'
          - 2. Redis: 'installation/2-redis.md'
          - 3. Mapserver: 'installation/3-mapserver.md'
    - Core Functionality:
          - Service registration: 'core-functionality/service-registration.md'
          - Metadata editor: 'core-functionality/metadata-editor.md'
          - Security engine: 'core-functionality/security-engine.md'
          - Monitoring engine: 'core-functionality/monitoring-engine.md'
          - Logging engine: 'core-functionality/logging-engine.md'
    - Administration:
        - Permissions: 'administration/permissions.md'
    - Development:
          - Introduction: 'development/index.md'
          - Getting Started: 'development/getting-started.md'