site_name: MrMap Documentation
site_url: https://mrmap.readthedocs.io/
repo_url: https://github.com/mrmap-community/mrmap
python:
    install:
        - requirements: docs/requirements.txt
theme:
    name: readthedocs
    navigation_depth: 3
markdown_extensions:
    - admonition:
    - markdown_include.include:
        headingOffset: 1
nav:
    - Introduction: 'index.md'
    - Installation:
            - Installing MrMap: 'installation/index.md'
            - 1. PostgreSQL: 'installation/1-postgresql.md'
            - 2. Redis: 'installation/2-redis.md'
            - 3. Mapserver: 'installation/3-mapserver.md'
    - Development:
          - Introduction: 'development/index.md'
          - Getting Started: 'development/getting-started.md'