site_name: MrMap Documentation
site_url: https://mrmap.readthedocs.io/
repo_url: https://github.com/mrmap-community/mrmap
python:
    install:
        - requirements: docs/requirements.txt
theme:
    name: readthedocs
    navigation_depth: 3
markdown_extensions:
    - admonition:
    - markdown_include.include:
        headingOffset: 1
nav:
    - Introduction: 'index.md'
    - Installation:
          - Installing MrMap: 'installation/index.md'
          - 1. PostgreSQL: 'installation/1-postgresql.md'
          - 2. Redis: 'installation/2-redis.md'
          - 3. Mapserver: 'installation/3-mapserver.md'
          - 4. MrMap: 'installation/4-mrmap.md'
          - 5. Application-Server: 'installation/5-application-server.md'
          - 6. HTTP-Server: 'installation/6-HTTP-Server.md'

    - Core Functionality:
          - Service registration: 'core-functionality/service-registration.md'
          - Metadata editor: 'core-functionality/metadata-editor.md'
          - Security engine: 'core-functionality/security-engine.md'
          - Monitoring engine: 'core-functionality/monitoring-engine.md'
          - Logging engine: 'core-functionality/logging-engine.md'
    - Development:
          - Introduction: 'development/index.md'
          - Getting Started: 'development/getting-started.md'
