from enum import Enum


class IconEnum(Enum):
    POWER_OFF = "fas fa-power-off"
    PROXY = "fas fa-archway"
    LOGGING = "fas fa-file-signature"
    WFS = "fas fa-draw-polygon"
    FEATURETYPE = "fas fa-draw-polygon"
    WMS = "far fa-map"
    LAYER = "fas fa-layer-group"
    CSW = "fas fa-book"
    DATASET = "fas fa-clipboard-list"
    PASSWORD = "fas fa-lock"
    HEARTBEAT = "fas fa-heartbeat"
    PENDING_TASKS = "fas fa-tasks"
    INFO = "fas fa-info"
    CAPABILITIES = "fas fa-file-code"
    NEWSPAPER = "far fa-newspaper"
    METADATA = "fas fa-file-alt"
    ERROR = "fas fa-exclamation-circle"
    PLAY = "fas fa-play"
    LOGS = "fas fa-stethoscope"
    DOWNLOAD = "fas fa-download"
    PUBLIC = "fas fa-globe"
    EDIT = "fas fa-edit"
    ACCESS = "fas fa-key"
