# Generated by Django 3.2.9 on 2022-02-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime')),
                ('phase', models.CharField(help_text='Current phase of the process', max_length=256, verbose_name='phase')),
                ('process_type', models.CharField(choices=[('harvesting', 'harvesting'), ('monitoring', 'monitoring'), ('registering', 'registering')], help_text='tells you what kind of process this is', max_length=32, verbose_name='process type')),
                ('description', models.CharField(help_text='Human readable description of what this process does', max_length=128, verbose_name='description')),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('related_resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('threads', models.ManyToManyField(blank=True, related_name='processes', related_query_name='process', to='django_celery_results.TaskResult')),
            ],
            options={
                'verbose_name': 'Background Process',
                'verbose_name_plural': 'Background Processes',
            },
        ),
    ]
