# Generated by Django 4.1.7 on 2023-07-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20220228_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='process_type',
            field=models.CharField(choices=[('harvesting', 'Harvesting'), ('monitoring', 'Monitoring'), ('registering', 'Registering')], help_text='tells you what kind of process this is', max_length=32, verbose_name='process type'),
        ),
    ]
