# Generated by Django 3.1.7 on 2021-03-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishrequest',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_publishrequest_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='from_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pending_publish_requests', to='structure.organization', verbose_name='requesting organization'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_publishrequest_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_publishrequest_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='to_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pending_publish_requests', to='structure.organization', verbose_name='requested organization'),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure.organization'),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='error_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.errorreport'),
        ),
        migrations.AddField(
            model_name='organization',
            name='can_publish_for',
            field=models.ManyToManyField(blank=True, related_name='_organization_can_publish_for_+', to='structure.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='real_organization',
            field=models.ForeignKey(blank=True, help_text='The real organization is a non auto generated organization which is verified by a user.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure.organization', verbose_name='Related real organization'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='publishrequest',
            unique_together={('from_organization', 'to_organization')},
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('organization_name', 'person_name', 'email', 'phone', 'facsimile', 'city', 'postal_code', 'address_type', 'address', 'state_or_province', 'country', 'description')},
        ),
    ]
