# Generated by Django 3.1.7 on 2021-04-21 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publishrequest',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_publishrequest_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='from_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pending_publish_requests', to='structure.organization', verbose_name='requesting organization'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_publishrequest_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_publishrequest_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='to_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pending_publish_requests', to='structure.organization', verbose_name='requested organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='can_publish_for',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(_negated=True, pk=django.db.models.expressions.F('pk')), related_name='_organization_can_publish_for_+', related_query_name='publishers', to='structure.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_organization_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_organization_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_organization_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='publishrequest',
            unique_together={('from_organization', 'to_organization')},
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('organization_name', 'person_name', 'email', 'phone', 'facsimile', 'city', 'postal_code', 'address_type', 'address', 'state_or_province', 'country', 'description')},
        ),
    ]
