# Generated by Django 3.1.7 on 2021-03-22 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210322_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 38, 18, 245485, tzinfo=utc)),
        ),
    ]
