# Generated by Django 3.1.7 on 2021-04-19 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210419_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 11, 48, 1, 991570, tzinfo=utc)),
        ),
    ]
