# Generated by Django 3.1.8 on 2021-05-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210531_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
