# Generated by Django 3.1.7 on 2021-03-23 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210323_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 9, 34, 9, 316361, tzinfo=utc)),
        ),
    ]
