# Generated by Django 3.1.8 on 2021-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20210531_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
