# Generated by Django 3.1.8 on 2021-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20210526_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='E-Mail'),
        ),
    ]
