# Generated by Django 3.1.7 on 2021-03-24 10:01

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20210323_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_auto_generated',
        ),
        migrations.AlterField(
            model_name='organization',
            name='can_publish_for',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(_negated=True, pk=django.db.models.expressions.F('pk')), related_name='_organization_can_publish_for_+', related_query_name='publishers', to='structure.Organization'),
        ),
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 10, 1, 8, 185958, tzinfo=utc)),
        ),
    ]
