# Generated by Django 3.1.7 on 2021-03-24 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210324_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='real_organization',
        ),
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 10, 24, 50, 735470, tzinfo=utc)),
        ),
    ]
