# Generated by Django 3.1.8 on 2021-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_pendingtask_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtask',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
