# Generated by Django 3.1.8 on 2021-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210427_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_autogenerated',
            field=models.BooleanField(default=True),
        ),
    ]
