# Generated by Django 3.1.7 on 2021-03-15 14:50

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210315_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrmapgroup',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(name='Public', then=0)), 'name'], 'permissions': [('add_user_to_group', 'Can add user to a group'), ('remove_user_from_group', 'Can remove user from a group'), ('request_to_become_publisher', 'Can request to become publisher')], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name'], 'permissions': [('remove_publisher', 'Can remove publisher')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='publishrequest',
            options={'permissions': [('toggle_publish_requests', 'Can toggle publish requests')], 'verbose_name': 'Pending publish request', 'verbose_name_plural': 'Pending publish requests'},
        ),
        migrations.AlterField(
            model_name='groupinvitationrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 50, 36, 132298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 50, 36, 132298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 50, 36, 130920, tzinfo=utc)),
        ),
    ]
