# Generated by Django 3.1.8 on 2021-06-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_organizationpublishrelation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpublishrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
