# Generated by Django 3.1.7 on 2021-04-09 18:30

import MrMap.validators
import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0023_auto_20210408_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtask',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupinvitationrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 18, 30, 28, 169342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pendingtask',
            name='type',
            field=models.CharField(blank=True, choices=[(None, '---'), ('harvest', 'harvest'), ('register', 'register'), ('validate', 'validate'), ('secure', 'secure')], max_length=500, null=True, validators=[MrMap.validators.validate_pending_task_enum_choices]),
        ),
        migrations.AlterField(
            model_name='publishrequest',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 18, 30, 28, 169342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 18, 30, 28, 168374, tzinfo=utc)),
        ),
    ]
