# Generated by Django 3.2.7 on 2021-09-21 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('structure', '0002_initial'),
        ('acl', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuserobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.service'),
        ),
        migrations.AddField(
            model_name='servicegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='servicegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_accesscontrollists',
            field=models.ManyToManyField(blank=True, help_text="Select which acl's shall be accessible with the configured permissions.", related_name='_acl_accesscontrollist_accessible_accesscontrollists_+', to='acl.AccessControlList', verbose_name='Accessible access control lists'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_organizations',
            field=models.ManyToManyField(blank=True, help_text='Select which organizations shall be accessible with the configured permissions.', to='structure.Organization', verbose_name='Accessible organizations'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceuserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='servicegroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
    ]
