# Generated by Django 3.1.7 on 2021-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_auto_20210426_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrollist',
            name='default_acl',
            field=models.BooleanField(default=False),
        ),
    ]
