# Generated by Django 3.1.8 on 2021-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_auto_20210504_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrollist',
            name='organization_admin',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
