# Generated by Django 3.1.8 on 2021-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_auto_20210608_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='accessible_pendingtasks',
        ),
        migrations.AlterField(
            model_name='metadatagroupobjectpermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadatauserobjectpermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
