# Generated by Django 3.1.8 on 2021-04-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_accesscontrollist_default_acl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrollist',
            old_name='secured_objects',
            new_name='accessible_objects',
        ),
    ]
