# Generated by Django 3.1.8 on 2021-05-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_accesscontrollist_organization_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accesscontrollist',
            managers=[
            ],
        ),
    ]
