# Generated by Django 3.1.8 on 2021-04-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20210427_0938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0005_auto_20210427_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrollist',
            options={'verbose_name': 'Access Control List', 'verbose_name_plural': 'Access Control Lists'},
        ),
        migrations.AddField(
            model_name='genericobjectrelation',
            name='search_helper',
            field=models.TextField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='accessible_objects',
            field=models.ManyToManyField(blank=True, help_text='Select which objects shall be accessible with the configured permissions.', to='acl.GenericObjectRelation', verbose_name='Accessible objects'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='default_acl',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='description',
            field=models.CharField(blank=True, help_text='Describe what this acl shall allow.', max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_owned', to='structure.organization', verbose_name='Owner'),
        ),
    ]
