# Generated by Django 3.1.8 on 2021-06-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0007_auto_20210614_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatagroupobjectpermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadatauserobjectpermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
