# Generated by Django 3.1.8 on 2021-04-27 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210427_1135'),
        ('service', '0004_auto_20210427_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0007_auto_20210427_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='accessible_objects',
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_metadatas',
            field=models.ManyToManyField(blank=True, help_text='Select which resource shall be accessible with the configured permissions.', to='service.Metadata', verbose_name='Accessible resource'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_organization',
            field=models.ForeignKey(blank=True, editable=False, help_text='Select which organization shall be accessible with the configured permissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.organization', verbose_name='Accessible organization'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_accesscontrollist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.DeleteModel(
            name='GenericObjectRelation',
        ),
    ]
