# Generated by Django 3.1.8 on 2021-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0008_auto_20210427_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_accesscontrollist',
            field=models.ManyToManyField(blank=True, help_text='Select which acl shall be accessible with the configured permissions.', related_name='_accesscontrollist_accessible_accesscontrollist_+', to='acl.AccessControlList', verbose_name='Accessible access control lists'),
        ),
    ]
