# Generated by Django 3.1.8 on 2021-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_organization_is_autogenerated'),
        ('acl', '0010_auto_20210427_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='accessible_accesscontrollist',
        ),
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='accessible_organization',
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_accesscontrollists',
            field=models.ManyToManyField(blank=True, help_text="Select which acl's shall be accessible with the configured permissions.", related_name='_accesscontrollist_accessible_accesscontrollists_+', to='acl.AccessControlList', verbose_name='Accessible access control lists'),
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='accessible_organizations',
            field=models.ManyToManyField(blank=True, help_text='Select which organizations shall be accessible with the configured permissions.', to='structure.Organization', verbose_name='Accessible organizations'),
        ),
    ]
