"""
Author: Michel Peltriaux
Organization: Spatial data infrastructure Rhineland-Palatinate, Germany
Contact: michel.peltriaux@vermkv.rlp.de
Created on: 04.05.20

"""
from django.utils import timezone
from django.test import TestCase

from mrmap.service.helper import service_helper
from service.helper.enums import OGCOperationEnum
from service.models import Metadata, RequestOperation
from service.tasks import async_increase_hits
from structure.models import Organization
from tests.baker_recipes.db_setup import create_superadminuser, create_wms_service, create_non_autogenerated_orgas, \
    create_operation
from tests.test_data import get_capabilitites_url

TIMEOUT_MSG_TEMPLATE = "Timeout on async call: {}"


class ServiceTaskTestCase(TestCase):

    def setUp(self):
        self.user = create_superadminuser()
        self.group = self.user.get_groups.first()
        self.metadata = create_wms_service(self.group, how_much_services=10)[0]

        # Declare timeout span
        self.timeout_delta = timezone.timedelta(seconds=10)

        # For new service testing
        create_non_autogenerated_orgas(self.user, 3)
        self.org = Organization.objects.all().first()

        # For securing service
        create_operation(OGCOperationEnum.GET_MAP.value)
        self.operation = RequestOperation.objects.all().first()

    def test_async_increase_hits(self):
        """ Tests the functionality of the asynchronous increasing of hits

        Returns:

        """
        pre_hit_count = self.metadata.hits

        # Perform async hit increasing
        async_increase_hits(self.metadata.id)

        # Get fresh state from db
        self.metadata.refresh_from_db()
        post_hit_count = self.metadata.hits

        fail_msg = "Asynchronous implemented increasing of hits did not work!"
        self.assertNotEqual(pre_hit_count, post_hit_count, fail_msg)
        self.assertEqual(pre_hit_count + 1, post_hit_count, fail_msg)

    def test_async_new_service(self):
        """ Tests the functionality of the asynchronous new service implementation

        PLEASE NOTE: CURRENTLY NOT USED FOR TESTING

        Returns:
        """
        # Get a valid capabilities url and split it's components into a dict
        urls = get_capabilitites_url()
        url = urls["valid"]
        url_dict = service_helper.split_service_uri(url)

        # Replace the OGCServiceEnum instance with it's value (neede for further process testing)
        url_dict["service"] = url_dict["service"].value

        pre_num_metadatas = Metadata.objects.all().count()

        # ToDo: Outcommented until suitable method has been found to test this celery driven implementation
        #async_new_service(url_dict=url_dict, user_id=self.user.id, register_group_id=self.group.id, register_for_organization_id=None, external_auth=None)
        #post_num_metadatas = Metadata.objects.all().count()
        #self.assertNotEqual(pre_num_metadatas, post_num_metadatas, msg="Asynchronous implementation of new service does not work.")
