# Generated by Django 4.2.7 on 2023-11-27 08:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataRelationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_level', models.TextField()),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('bounding_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(
                    srid=4326)),
                ('modified_at', models.DateTimeField()),
                ('resource_identifier', models.TextField()),
                ('file_identifier', models.TextField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None)),
                ('search', models.TextField()),
            ],
            options={
                'db_table': 'registry_metadatarelation_view',
                'managed': False,
            },
        ),
    ]
