# Generated by Django 3.2.9 on 2022-01-05 15:03

from django.db import migrations
from registry.enums.service import (SecureableWFSOperationEnum,
                                    SecureableWMSOperationEnum)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    def create_wms_operations(apps, schema_editor):
        WebMapServiceOperation = apps.get_model(
            "registry", "WebMapServiceOperation")
        objs = []
        for key, value in SecureableWMSOperationEnum.as_choices(drop_empty_choice=True):
            objs.append(WebMapServiceOperation(operation=value))
        WebMapServiceOperation.objects.bulk_create(objs=objs)

    def create_wfs_operations(apps, schema_editor):
        WebFeatureServiceOperation = apps.get_model(
            "registry", "WebFeatureServiceOperation")
        objs = []
        for key, value in SecureableWFSOperationEnum.as_choices(drop_empty_choice=True):
            objs.append(WebFeatureServiceOperation(operation=value))
        WebFeatureServiceOperation.objects.bulk_create(objs=objs)

    operations = [
        migrations.RunPython(create_wms_operations),
        migrations.RunPython(create_wfs_operations),
    ]
