# Generated by Django 5.0 on 2023-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymdmetadatafile',
            name='import_error',
            field=models.TextField(default='', help_text='raised error while importing', verbose_name='import error'),
        ),
    ]
