# Generated by Django 3.2.7 on 2021-10-04 10:19

from django.db import migrations, models
import django.db.models.deletion
import registry.models.mapcontext


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontextlayer',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.datasetmetadata'),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.layer'),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='A preview image for the Map Context Layer', null=True, upload_to=registry.models.mapcontext.preview_image_file_path, verbose_name='preview image'),
        ),
    ]
