# Generated by Django 5.0 on 2024-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_searchabledatasetmetadatarecord_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('keyword', ''), _negated=True), models.Q(('keyword__isnull', True), _negated=True), _connector='OR'), name='registry_keyword_non_empty_keywords'),
        ),
    ]
