# Generated by Django 5.0 on 2023-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_temporarymdmetadatafile_import_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesystem',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='referencesystem',
            name='prefix',
            field=models.CharField(choices=[('EPSG', 'Epsg')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarymdmetadatafile',
            name='import_error',
            field=models.TextField(blank=True, default='', help_text='raised error while importing', verbose_name='import error'),
        ),
    ]
