# Generated by Django 5.0 on 2023-12-18 11:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_datasetmetadatarecordkeywords_sync_keywords_list_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='datasetmetadatarecordkeywords',
            name='sync_keywords_list',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datasetmetadatarecordkeywords',
            trigger=pgtrigger.compiler.Trigger(name='sync_keywords_list', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    UPDATE registry_datasetmetadatarecord\n                    SET keywords_list = array(\n                        SELECT keyword \n                        FROM registry_keyword \n                        WHERE keyword.id IN (\n                            SELECT keyword_id\n                            FROM registry_datasetmetadatarecordkeywords\n                            WHERE dataset_id = NEW.dataset_id\n                        )\n                    )\n                    WHERE id = NEW.dataset_id;\n                    RETURN NULL;\n                ', hash='b87f83091f20af91fe83b0cded5aa676153ca567', operation='UPDATE OR DELETE OR INSERT', pgid='pgtrigger_sync_keywords_list_44e2d', table='registry_datasetmetadatarecordkeywords', when='AFTER')),
        ),
    ]
