# Generated by Django 4.1.11 on 2023-11-06 13:07

from django.db import migrations, models
import django.db.models.deletion
import registry.models.harvest


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_datasetmetadatarecord_metadatarelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueservice',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='metadatarelation',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], help_text='determines where this relation was found or it is added by a user.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='temporarymdmetadatafile',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.harvestingjob', verbose_name='harvesting job'),
        ),
        migrations.AlterField(
            model_name='temporarymdmetadatafile',
            name='md_metadata_file',
            field=models.FileField(editable=False, help_text='the content of the http response, or of the imported file', upload_to=registry.models.harvest.response_file_path, verbose_name='response'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='origin',
            field=models.CharField(choices=[('Capabilities', 'Capabilities'), ('Upload', 'Upload'), ('File System Import', 'File System Import'), ('Editor', 'Editor'), ('Catalogue', 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', max_length=20, verbose_name='origin'),
        ),
    ]
