# Generated by Django 5.1.2 on 2024-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_remove_layergetmapresult_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getcapabilitiesprobe',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='getmapprobe',
            name='setting',
        ),
        migrations.AddField(
            model_name='webmapservicemonitoringsetting',
            name='get_capabilities_probes',
            field=models.ManyToManyField(help_text='define multiple get capabilities probes for this service', to='registry.getcapabilitiesprobe', verbose_name='Get Capabilities Probes'),
        ),
        migrations.AddField(
            model_name='webmapservicemonitoringsetting',
            name='get_map_probes',
            field=models.ManyToManyField(help_text='define multiple get map probes for this service', to='registry.getmapprobe', verbose_name='Get Map Probes'),
        ),
    ]
