# Generated by Django 5.1.2 on 2024-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_remove_layergetmapresult_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getcapabilitiesprobe',
            name='check_response_does_contain',
            field=models.CharField(default='Title>,Abstract>', help_text='comma seperated search strings like: Title>,Abstract>', max_length=256, verbose_name='Check response does contain'),
        ),
        migrations.AlterField(
            model_name='getcapabilitiesprobe',
            name='check_response_does_not_contain',
            field=models.CharField(default='ExceptionReport>, ServiceException>', help_text='comma seperated search strings like: ExceptionReport>, ServiceException>', max_length=256, verbose_name='Check response does not contain'),
        ),
        migrations.AlterField(
            model_name='getmapprobe',
            name='check_response_does_not_contain',
            field=models.CharField(default='ExceptionReport>, ServiceException>', help_text='comma seperated search strings like: ExceptionReport>, ServiceException>', max_length=256, verbose_name='Check response does not contain'),
        ),
    ]
