# Generated by Django 3.2.7 on 2021-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20211027_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='rendering_layer',
            field=models.ForeignKey(blank=True, help_text='Select a layer as an offering for rendering.', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.layer', verbose_name='Rendering layer'),
        ),
    ]
