# Generated by Django 3.1.7 on 2021-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210401_1235'),
        ('monitoring', '0002_auto_20210315_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonitoringResultCapability',
            new_name='MonitoringResultDocument',
        ),
        migrations.AlterUniqueTogether(
            name='monitoringresult',
            unique_together={('metadata', 'monitored_uri')},
        ),
    ]
