# Generated by Django 3.1.7 on 2021-03-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
        ('service', '0001_initial'),
        ('monitoring', '0002_auto_20210325_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringrun',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='metadatas',
            field=models.ManyToManyField(related_name='monitoring_runs', to='service.Metadata', verbose_name='Checked resources'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.metadata', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='monitoring_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='monitoring.monitoringrun'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='healthstatereason',
            name='health_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='monitoring.healthstate'),
        ),
        migrations.AddField(
            model_name='healthstatereason',
            name='monitoring_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_state_reasons', to='monitoring.monitoringresult'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='service.metadata', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='monitoring_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='monitoring.monitoringrun', verbose_name='Monitoring Run'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringresult',
            unique_together={('metadata', 'monitored_uri', 'monitoring_run')},
        ),
    ]
