# Generated by Django 3.2.7 on 2021-09-22 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('monitoring', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringrun',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='dataset_metadatas',
            field=models.ManyToManyField(blank=True, related_name='monitoring_runs', to='registry.DatasetMetadata', verbose_name='Checked dataset metadatas'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='feature_types',
            field=models.ManyToManyField(blank=True, related_name='monitoring_runs', to='registry.FeatureType', verbose_name='Checked feature types'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='monitoring_runs', to='registry.Layer', verbose_name='Checked layers'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='monitoring_runs', to='registry.Service', verbose_name='Checked services'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.datasetmetadata', verbose_name='Dataset Metadata'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='feature_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.featuretype', verbose_name='Feature Type'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.layer', verbose_name='Layer'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='monitoring_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='monitoring.monitoringrun'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='monitoringresult',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='healthstatereason',
            name='health_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='monitoring.healthstate'),
        ),
        migrations.AddField(
            model_name='healthstatereason',
            name='monitoring_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_state_reasons', to='monitoring.monitoringresult'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_states', related_query_name='health_states', to='registry.datasetmetadata', verbose_name='Dataset Metadata'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='feature_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_states', related_query_name='health_states', to='registry.featuretype', verbose_name='Feature Type'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_states', related_query_name='health_states', to='registry.layer', verbose_name='Layer'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='monitoring_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_states', to='monitoring.monitoringrun', verbose_name='Monitoring Runs'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='healthstate',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_states', related_query_name='health_states', to='registry.service', verbose_name='Service'),
        ),
    ]
