# Generated by Django 3.2.3 on 2021-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20210531_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstatereason',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
