# Generated by Django 3.1.8 on 2021-04-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20210427_0938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0003_auto_20210426_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_healthstate_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringresult_owned', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='monitoringrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='monitoringrun',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='monitoringrun',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='monitoringrun',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='monitoringrun',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_monitoringrun_owned', to='structure.organization', verbose_name='Owner'),
        ),
    ]
