# Generated by Django 3.1.8 on 2021-05-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210504_0939'),
        ('monitoring', '0004_auto_20210504_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstate',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_states', related_query_name='health_states', to='service.metadata', verbose_name='Resource'),
        ),
    ]
