---
name: ✨ Feature Request
about: Propose a new MrMap feature or enhancement
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: "**NOTE:** This form is only for submitting well-formed proposals to extend or
      modify MrMap in some way. If you're trying to solve a problem but can't figure out how,
      or if you still need time to work on the details of a proposed new feature, please start
      a [discussion](https://github.com/mrmap-community/mrmap/discussions) instead."
  - type: input
    attributes:
      label: MrMap version
      description: "What version of MrMap are you currently running?"
      placeholder: v1.0.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Feature type
      options:
        - Data model extension
        - New functionality
        - Change to existing functionality
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed functionality
      description: "Describe in detail the new feature or behavior you'd like to propose.
        Include any specific changes to work flows, data models, or the user interface."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: "Explain how adding this functionality would benefit MrMap users. What
        need does it address?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Database changes
      description: "Note any changes to the database schema necessary to support the new
        feature. For example, does the proposal require adding a new model or field? (Not
        all new features require database changes.)"
  - type: textarea
    attributes:
      label: External dependencies
      description: "List any new dependencies on external libraries or services that this
        new feature would introduce. For example, does the proposal require the installation
        of a new Python package? (Not all new features introduce new dependencies.)"
  - type: markdown
    attributes:
      value: |
        ### Additional information
        You can use the space below to provide any additional information or to attach files.
