from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy, NoReverseMatch
from django.views.generic import DetailView, DeleteView, UpdateView, CreateView
from guardian.mixins import LoginRequiredMixin, PermissionRequiredMixin, PermissionListMixin
from MrMap.views import CustomSingleTableMixin, SuccessMessageDeleteMixin, GenericViewContextMixin, InitFormMixin, \
    ConfirmView, DependingListMixin
from django.contrib.auth.mixins import PermissionRequiredMixin as DjangoPermissionRequiredMixin
from django.utils.translation import gettext_lazy as _


class GenericPermissionMixin:
    action = None
    app_label = None
    model_name = None

    def get_model_data(self, model):
        self.app_label = model._meta.app_label
        self.model_name = model._meta.model_name.lower()

    def get_default_permission(self):
        """return the default view permission of the given model in format: 'app_label.model_name'"""
        if not self.action:
            raise ImproperlyConfigured("`GenericPermissionRequiredMixin` requires 'action' attribute to be set to "
                                       "default permission action like 'view' but is set to 'None'")
        self.get_model_data(self.model)
        return f"{self.app_label}.{self.action}_{self.model_name}"


class GenericSuccessUrlMixin:
    def get_success_url(self):
        if not self.success_url:
            try:
                url = self.object.get_absolute_url()
            except NoReverseMatch:
                raise ImproperlyConfigured(f'configure success_url or define a default detail view for {self.model_name}')
            return url
        else:
            return self.success_url


class DjangoGenericPermissionRequiredMixin(GenericPermissionMixin, DjangoPermissionRequiredMixin):
    raise_exception = True

    def get_permission_required(self):
        """return the default view permission of the given model in format: 'app_label.model_name' if
        self.permission_required is None. Else the permission is generated by the self.action attribute.
        """
        if not self.permission_required:
            self.permission_required = self.get_default_permission()
        return super().get_permission_required()


class GenericPermissionRequiredMixin(GenericPermissionMixin, PermissionRequiredMixin):
    raise_exception = True

    def get_required_permissions(self, request=None):
        """return the default view permission of the given model in format: 'app_label.model_name' if
        self.permission_required is None. Else the permission is generated by the self.action attribute.
        """
        if self.permission_required:
            return super().get_required_permissions(request=request)
        return [self.get_default_permission()]


class GenericPermissionListMixin(GenericPermissionMixin, PermissionListMixin):

    get_objects_for_user_extra_kwargs = {'accept_global_perms': False}

    def get_required_permissions(self, request=None):
        """return the default view permission of the given model in format: 'app_label.model_name' if
        self.permission_required is None. Else the permission is generated by the self.action attribute.
        """
        if not self.permission_required:
            self.permission_required = self.get_default_permission()
        return super().get_required_permissions(request=request)


class SecuredCreateView(LoginRequiredMixin,
                        GenericSuccessUrlMixin,
                        DjangoGenericPermissionRequiredMixin,
                        GenericViewContextMixin,
                        InitFormMixin,
                        SuccessMessageMixin,
                        CreateView):
    """
    Secured django `CreateView` class with default permission '<app_label>.add_<model_name>'
    """
    action = 'add'
    template_name = 'MrMap/detail_views/generic_form.html'

    def get_required_permissions(self, request=None):
        """return the default view permission of the given model in format: 'app_label.model_name' if
        self.permission_required is None. Else the permission is generated by the self.action attribute.
        """
        if self.permission_required:
            return super().get_required_permissions(request=request)
        return [self.get_default_permission()]


class SecuredDetailView(LoginRequiredMixin, GenericPermissionRequiredMixin, GenericViewContextMixin, DetailView):
    """
    Secured django `DetailView` class with default permission '<app_label>.view_<model_name>'
    """
    action = 'view'


class SecuredDeleteView(LoginRequiredMixin,
                        GenericPermissionRequiredMixin,
                        GenericViewContextMixin,
                        SuccessMessageDeleteMixin,
                        DeleteView):
    """
    Secured django `DeleteView` class with default permission '<app_label>.delete_<model_name>'
    """
    action = 'delete'

    def get_success_url(self):
        if not self.success_url:
            return reverse_lazy(f'{self.app_label}:{self.model_name}_overview')
        else:
            return super().get_success_url()


class SecuredUpdateView(LoginRequiredMixin,
                        GenericSuccessUrlMixin,
                        GenericPermissionRequiredMixin,
                        GenericViewContextMixin,
                        InitFormMixin,
                        SuccessMessageMixin,
                        UpdateView):
    """
    Secured django `UpdateView` class with default permission '<app_label>.change_<model_name>'
    """
    action = 'change'
    template_name = "MrMap/detail_views/generic_form.html"

    def get_title(self):
        return _("Edit ") + self.get_object().__str__()


class SecuredListMixin(LoginRequiredMixin, GenericPermissionListMixin, CustomSingleTableMixin):
    """
    Secured django-tables2 table mixin class with default permission '<app_label>.view_<model_name>'
    """
    action = 'view'


class SecuredDependingListMixin(LoginRequiredMixin, GenericPermissionListMixin, DependingListMixin, CustomSingleTableMixin):
    """
    Secured `DependingListView` mixin class with default permission '<app_label>.view_<model_name>'
    """
    action = 'view'


class SecuredConfirmView(LoginRequiredMixin, PermissionRequiredMixin, GenericViewContextMixin, InitFormMixin, SuccessMessageMixin, ConfirmView):
    """
    Secured `ConfirmView` class with default permission '<app_label>.change_<model_name>'
    """
    action = 'change'
