"""
Author: Michel Peltriaux
Organization: Spatial data infrastructure Rhineland-Palatinate, Germany
Contact: michel.peltriaux@vermkv.rlp.de
Created on: 05.05.20

"""

MD_CORE_MODEL = {
    'typename': 'pycsw:CoreMetadata',
    'outputschema': 'http://pycsw.org/metadata',
    'mappings': {
        'pycsw:Identifier': 'identifier',
        'pycsw:Typename': 'csw_typename',
        'pycsw:Schema': 'csw_schema',
        'pycsw:MdSource': '',
        'pycsw:InsertDate': '',
        'pycsw:XML': 'metadata_xml',
        'pycsw:AnyText': 'csw_anytext',
        'pycsw:Language': '',
        'pycsw:Title': 'title',
        'pycsw:Abstract': 'abstract',
        'pycsw:Keywords': 'csw_keywords',
        'pycsw:KeywordType': '',
        'pycsw:Format': '',
        'pycsw:Source': 'capabilities_uri',
        'pycsw:Date': '',
        'pycsw:Modified': 'last_modified',
        'pycsw:Type': 'csw_typename',
        'pycsw:BoundingBox': 'csw_bounding_geometry',
        'pycsw:CRS': 'csw_srs',
        'pycsw:AlternateTitle': '',
        'pycsw:RevisionDate': '',
        'pycsw:CreationDate': '',
        'pycsw:PublicationDate': '',
        'pycsw:Organization': 'csw_organizationname',
        'pycsw:OrganizationName': 'csw_organizationname',
        'pycsw:SecurityConstraints': '',
        'pycsw:ParentIdentifier': '',
        'pycsw:TopicCategory': 'csw_category',
        'pycsw:ResourceLanguage': '',
        'pycsw:GeographicDescriptionCode': '',
        'pycsw:Denominator': '',
        'pycsw:DistanceValue': '',
        'pycsw:DistanceUOM': '',
        'pycsw:TempExtent_begin': 'csw_temp_dim_start',
        'pycsw:TempExtent_end': 'csw_temp_dim_end',
        'pycsw:ServiceType': 'csw_service_type',
        'pycsw:ServiceTypeVersion': 'csw_service_version',
        'pycsw:Operation': '',
        'pycsw:CouplingType': '',
        'pycsw:OperatesOn': 'csw_operates_on',
        'pycsw:OperatesOnIdentifier': 'csw_operates_on_identifier',
        'pycsw:OperatesOnName': 'csw_operates_on_name',
        'pycsw:Degree': '',
        'pycsw:AccessConstraints': 'access_constraints',
        'pycsw:OtherConstraints': '',
        'pycsw:Classification': '',
        'pycsw:ConditionApplyingToAccessAndUse': '',
        'pycsw:Lineage': '',
        'pycsw:ResponsiblePartyRole': '',
        'pycsw:SpecificationTitle': '',
        'pycsw:SpecificationDate': '',
        'pycsw:SpecificationDateType': '',
        'pycsw:Creator': '',
        'pycsw:Publisher': 'published_for',
        'pycsw:Contributor': '',
        'pycsw:Relation': '',
        'pycsw:Links': '',
    }
}