# Generated by Django 3.1.7 on 2021-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210315_1154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metadata',
            name='service_met_id_fa3740_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='featuretype',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='featuretypeelement',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='genericurl',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='mimetype',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='public_id',
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(fields=['id', 'identifier'], name='service_met_id_0adfe4_idx'),
        ),
    ]
