# Generated by Django 3.1.8 on 2021-05-06 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20210504_1909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_auto_20210504_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='The timestamp of the creation date of this object.', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericurl',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_genericurl_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='genericurl',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='genericurl',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_genericurl_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='genericurl',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_genericurl_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
    ]
