# Generated by Django 3.1.8 on 2021-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210505_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(choices=[(None, '---'), ('wms', 'wms'), ('wfs', 'wfs'), ('wmc', 'wmc'), ('dataset', 'dataset'), ('csw', 'csw')], db_index=True, max_length=100),
        ),
    ]
