# Generated by Django 3.1.8 on 2021-05-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210506_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='mime_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mimetype'),
        ),
    ]
