# Generated by Django 3.1.7 on 2021-03-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210315_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='featuretype',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='featuretypeelement',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='genericurl',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata'), ('activate_resource', 'Can activate a resource'), ('update_resource', 'Can update a resource'), ('harvest_resource', 'Can harvest a resource')]},
        ),
        migrations.AlterModelOptions(
            name='mimetype',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='proxylog',
            options={'ordering': ['-timestamp'], 'permissions': [('download_logs', 'Can download logs')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
        migrations.AlterModelOptions(
            name='serviceurl',
            options={'permissions': [('delete_dataset_metadata', 'Can delete dataset metadata'), ('add_dataset_metadata', 'Can add dataset metadata')]},
        ),
    ]
