# Generated by Django 3.1.8 on 2021-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210414_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericurl',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
