# Generated by Django 3.1.8 on 2021-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210506_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(choices=[(None, '---'), ('wms', 'wms'), ('wfs', 'wfs'), ('wmc', 'wmc'), ('dataset', 'dataset'), ('csw', 'csw')], max_length=100),
        ),
    ]
