# Generated by Django 3.1.8 on 2021-05-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210506_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthentication',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_authentication', to='service.metadata'),
        ),
        migrations.AlterField(
            model_name='style',
            name='mime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.mimetype'),
        ),
    ]
