# Generated by Django 3.1.8 on 2021-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210506_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
    ]
