# Generated by Django 3.1.7 on 2021-03-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210315_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='featuretype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='featuretypeelement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genericurl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mimetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceurl',
            options={},
        ),
    ]
