# Generated by Django 3.1.7 on 2021-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210415_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatarelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(None, '---'), ('visualizes', 'visualizes'), ('describes', 'describes'), ('harvestedThrough', 'harvestedThrough'), ('harvestedParent', 'harvestedParent'), ('publishedBy', 'publishedBy')], max_length=255, null=True),
        ),
    ]
