# Generated by Django 3.1.8 on 2021-04-27 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0005_auto_20210415_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatarelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(None, '---'), ('visualizes', 'visualizes'), ('describes', 'describes'), ('harvestedThrough', 'harvestedThrough'), ('harvestedParent', 'harvestedParent'), ('publishedBy', 'publishedBy')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MapContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('layer_tree', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
