# Generated by Django 3.1.7 on 2021-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210316_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericurl',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
