# Generated by Django 3.1.8 on 2021-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0007_auto_20210618_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedoperation',
            name='allowed_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='allowedoperation',
            name='operations',
            field=models.ManyToManyField(to='service.OGCOperation'),
        ),
    ]
