# Generated by Django 3.1.7 on 2021-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210401_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='language_code',
            field=models.CharField(blank=True, choices=[('ger', 'German'), ('eng', 'English')], default='ger', max_length=100, null=True),
        ),
    ]
