version: '3.5'
services:
  mrmap-postgis:
    image: mdillon/postgis:11-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgis/initdata/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
  mrmap-redis:
    image: library/redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis_data:/data
  mrmap-geoserver:
    image: terrestris/geoserver:2.15.2
    ports:
      - 8090:8080
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data:Z
    depends_on:
      - mrmap-postgis
  mrmap-etf-webapp:
    image: wetransform/etf-webapp:2.0.1-20190716
    ports:
      - 8091:8080
    volumes:
      - ./etf/:/etf
  mrmap-inspire-validator:
    build:
      context: ./inspire-validator
    ports:
      - 8092:8080
    volumes:
      - ./etf-inspire/:/etf
