# Generated by Django 2.1.2 on 2019-04-04 12:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_DE', models.CharField(max_length=100, unique=True)),
                ('title_EN', models.CharField(max_length=100, unique=True)),
                ('description_DE', models.CharField(max_length=100, unique=True)),
                ('description_EN', models.CharField(max_length=100, unique=True)),
                ('is_inspire', models.BooleanField()),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=1000)),
                ('online_resource', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_open_data', models.BooleanField()),
                ('fees', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.User')),
            ],
        ),
        migrations.CreateModel(
            name='WFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abstract', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('availability', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_available', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abstract', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('availability', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_available', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('metadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.Metadata')),
                ('bbox', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dimension', models.CharField(max_length=100)),
                ('authority_url', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('metadata_url', models.CharField(max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Dataset')),
            ],
            bases=('service.metadata',),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('wms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.WMS')),
                ('hits', models.IntegerField()),
                ('preview_image', models.CharField(max_length=100)),
                ('preview_extend', models.CharField(max_length=100)),
                ('preview_legend', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('service.wms',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('wfs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.WFS')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('service.wfs',),
        ),
        migrations.CreateModel(
            name='ServiceMetadata',
            fields=[
                ('metadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.Metadata')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_person_position', models.CharField(max_length=100)),
                ('contact_organization', models.CharField(max_length=100)),
                ('address_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('access_constraints', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('last_change', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('last_harvest_successful', models.BooleanField()),
                ('last_harvest_exception', models.CharField(max_length=200)),
                ('export_to_csw', models.BooleanField()),
                ('spatial_res_type', models.CharField(max_length=100)),
                ('spatial_res_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('is_inspire_conform', models.BooleanField()),
                ('has_inspire_downloads', models.BooleanField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('bounding_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            bases=('service.metadata',),
        ),
        migrations.AddField(
            model_name='wms',
            name='categories',
            field=models.ManyToManyField(to='service.Category'),
        ),
        migrations.AddField(
            model_name='wms',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.Group'),
        ),
        migrations.AddField(
            model_name='wms',
            name='published_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.Organization'),
        ),
        migrations.AddField(
            model_name='wms',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.ServiceType'),
        ),
        migrations.AddField(
            model_name='wfs',
            name='categories',
            field=models.ManyToManyField(to='service.Category'),
        ),
        migrations.AddField(
            model_name='wfs',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.Group'),
        ),
        migrations.AddField(
            model_name='wfs',
            name='published_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.Organization'),
        ),
        migrations.AddField(
            model_name='wfs',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.ServiceType'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Keyword'),
        ),
        migrations.AddField(
            model_name='servicemetadata',
            name='service_wfs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.WFS'),
        ),
        migrations.AddField(
            model_name='servicemetadata',
            name='service_wms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.WMS'),
        ),
        migrations.AddField(
            model_name='servicemetadata',
            name='terms_of_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.TermsOfUse'),
        ),
        migrations.AddField(
            model_name='contentmetadata',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Layer'),
        ),
        migrations.AddField(
            model_name='contentmetadata',
            name='reference_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.ReferenceSystem'),
        ),
    ]
