# Generated by Django 3.1.5 on 2021-01-26 09:17

import MrMap.validators
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210125_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedoperation',
            name='bounding_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, validators=[MrMap.validators.geometry_is_empty]),
        ),
    ]
