# Generated by Django 3.1.7 on 2021-02-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210222_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthentication',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_authentication', to='service.metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='related_metadatas',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='service.MetadataRelation', to='service.Metadata'),
        ),
    ]
