# Generated by Django 3.1.5 on 2021-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210105_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='language_code',
            field=models.CharField(blank=True, choices=[('ger', 'German'), ('eng', 'English')], default='ger', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='related_metadata',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='service.MetadataRelation'),
        ),
    ]
