# Generated by Django 3.1.7 on 2021-02-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210219_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='related_metadata',
        ),
        migrations.RemoveField(
            model_name='metadatarelation',
            name='metadata_to',
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadata_relations',
            field=models.ManyToManyField(blank=True, related_name='_metadata_metadata_relations_+', through='service.MetadataRelation', to='service.Metadata'),
        ),
        migrations.AddField(
            model_name='metadatarelation',
            name='from_metadata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_metadatas', to='service.metadata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarelation',
            name='to_metadata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_metadatas', to='service.metadata'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('metadata', 'is_original', 'document_type')},
        ),
    ]
