# Generated by Django 3.1.2 on 2020-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20201202_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='related_metadata',
            field=models.ManyToManyField(blank=True, related_name='metadata_from', to='service.MetadataRelation'),
        ),
    ]
