# Generated by Django 3.1.5 on 2021-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('service', '0003_auto_20210126_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedoperation',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='allowed_operations', to='structure.MrMapGroup'),
        ),
        migrations.AlterField(
            model_name='allowedoperation',
            name='operations',
            field=models.ManyToManyField(related_name='allowed_operations', to='service.OGCOperation'),
        ),
        migrations.AlterField(
            model_name='allowedoperation',
            name='secured_metadata',
            field=models.ManyToManyField(related_name='allowed_operations', to='service.Metadata'),
        ),
    ]
