# Generated by Django 3.1.7 on 2021-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210222_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatarelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(None, '---'), ('visualizes', 'visualizes'), ('describes', 'describes'), ('harvestedThrough', 'harvestedThrough'), ('harvestedParent', 'harvestedParent')], max_length=255, null=True),
        ),
    ]
