# Generated by Django 3.1.5 on 2021-01-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210126_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedoperation',
            old_name='bounding_geometry',
            new_name='allowed_area',
        ),
    ]
