# Generated by Django 3.1.5 on 2021-01-28 09:29

import MrMap.validators
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210127_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedoperation',
            name='allowed_area',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326, validators=[MrMap.validators.geometry_is_empty]),
        ),
    ]
