pipeline {
    agent { docker { image 'python:3.7.0' } }
    stages {
        stage('Test') {
            steps {
                echo 'Running Unit-Tests..'
                sh 'python --version'
                sh 'python manage.py test --where "tests/unit_tests/"'
            }
        }
        stage('Analysis') {
            steps {
                echo 'Analysing....'
            }
        }
    }
    
}