# Generated by Django 3.2.7 on 2021-12-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('object_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmapserviceuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.webmapservice'),
        ),
        migrations.AddField(
            model_name='webmapserviceuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
    ]
