# Generated by Django 3.1.7 on 2021-03-18 12:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
        ('service', '0002_auto_20210318_1052'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0004_auto_20210318_1353'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectBasedTemplateRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('description', models.TextField(help_text='Describe what permissions this role shall grant', verbose_name='Description')),
                ('based_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_based_template_roles', to='permission.templaterole')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metadatauserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metadatauserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='metadatauserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='metadatauserobjectpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='objectbasedrolegroup',
            name='based_template',
        ),
        migrations.RemoveField(
            model_name='objectbasedrolegroup',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='objectbasedrolegroup',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='MetadataGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='MetadataUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='ObjectBasedRoleGroup',
        ),
        migrations.AddField(
            model_name='customuserobjectpermission',
            name='object_based_template_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='permission.objectbasedtemplaterole'),
        ),
        migrations.AddField(
            model_name='customuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='customuserobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgroupobjectpermission',
            name='object_based_template_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='permission.objectbasedtemplaterole'),
        ),
        migrations.AddField(
            model_name='customgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddIndex(
            model_name='customuserobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk'], name='permission__content_519ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuserobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk', 'user'], name='permission__content_c39a8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customuserobjectpermission',
            unique_together={('user', 'permission', 'object_pk')},
        ),
        migrations.AddIndex(
            model_name='customgroupobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk'], name='permission__content_dbfa1f_idx'),
        ),
        migrations.AddIndex(
            model_name='customgroupobjectpermission',
            index=models.Index(fields=['content_type', 'object_pk', 'group'], name='permission__content_259fb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customgroupobjectpermission',
            unique_together={('group', 'permission', 'object_pk')},
        ),
    ]
