# Generated by Django 3.1.7 on 2021-03-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_auto_20210318_1353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customuserobjectpermission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customuserobjectpermission',
            name='object_based_template_role',
        ),
        migrations.RemoveField(
            model_name='customuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='customuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='CustomUserObjectPermission',
        ),
    ]
