# Generated by Django 3.1.7 on 2021-03-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210310_1106'),
        ('monitoring', '0002_auto_20210310_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstate',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='service.metadata', verbose_name='Resource'),
        ),
    ]
