# Generated by Django 3.1.6 on 2021-02-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210217_1348'),
        ('monitoring', '0002_auto_20210217_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringrun',
            name='metadatas',
            field=models.ManyToManyField(related_name='monitoring_runs', to='service.Metadata'),
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.metadata', verbose_name='Resource'),
        ),
    ]
