# Generated by Django 3.1.6 on 2021-02-18 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210217_1348'),
        ('monitoring', '0003_auto_20210217_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringresult',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Monitoring result', 'verbose_name_plural': 'Monitoring results'},
        ),
        migrations.AlterModelOptions(
            name='monitoringrun',
            options={'ordering': ['-end'], 'verbose_name': 'Monitoring run', 'verbose_name_plural': 'Monitoring runs'},
        ),
        migrations.AlterField(
            model_name='monitoringresult',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Result'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringresult',
            unique_together={('metadata', 'monitored_uri', 'monitoring_run')},
        ),
    ]
