# Generated by Django 3.1.7 on 2021-03-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20210310_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthstate',
            options={'ordering': ['-monitoring_run__start'], 'verbose_name': 'Health state', 'verbose_name_plural': 'Health states'},
        ),
    ]
