# Generated by Django 3.1.5 on 2021-02-18 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210217_1348'),
        ('monitoring', '0004_auto_20210218_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthstate',
            options={'verbose_name': 'Health state', 'verbose_name_plural': 'Health states'},
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='health_state_code',
            field=models.CharField(choices=[('ok', 'ok'), ('warning', 'warning'), ('critical', 'critical'), ('unknown', 'unknown'), ('unauthorized', 'unauthorized')], default='unknown', max_length=12, verbose_name='Health state code'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='service.metadata'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='monitoring_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='monitoring.monitoringrun'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Health state'),
        ),
        migrations.AlterField(
            model_name='monitoringrun',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
