# Generated by Django 3.1.5 on 2021-02-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210217_1348'),
        ('monitoring', '0005_auto_20210218_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstate',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='service.metadata', verbose_name='Health state'),
        ),
        migrations.AlterField(
            model_name='healthstate',
            name='monitoring_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_state', to='monitoring.monitoringrun', verbose_name='Health state'),
        ),
    ]
