# Generated by Django 3.2.4 on 2021-08-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0002_initial'),
        ('resourceNew', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformitycheckrun',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceNew.datasetmetadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_conformitycheckrun_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='conformitycheckconfigurationinternal',
            name='mandatory_rule_sets',
            field=models.ManyToManyField(related_name='mandatory_rule_sets', to='quality.RuleSet'),
        ),
        migrations.AddField(
            model_name='conformitycheckconfigurationinternal',
            name='optional_rule_sets',
            field=models.ManyToManyField(blank=True, related_name='optional_rule_sets', to='quality.RuleSet'),
        ),
    ]
