# Generated by Django 3.2.7 on 2021-09-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
        ('users', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conformitycheckrun',
            name='created_by_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_conformitycheckrun_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, help_text='the dataset metadata targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.datasetmetadata', verbose_name='dataset metadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='feature_type',
            field=models.ForeignKey(blank=True, help_text='the feature type targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.featuretype', verbose_name='feature type'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='feature_type_metadata',
            field=models.ForeignKey(blank=True, help_text='the feature type metadata targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.featuretypemetadata', verbose_name='feature type metadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_conformitycheckrun_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='layer',
            field=models.ForeignKey(blank=True, help_text='the layer targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.layer', verbose_name='layer'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='layer_metadata',
            field=models.ForeignKey(blank=True, help_text='the layer metadata targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.layermetadata', verbose_name='layer metadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_conformitycheckrun_owned_by_org', to='users.organization', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='service',
            field=models.ForeignKey(blank=True, help_text='the service targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='service_metadata',
            field=models.ForeignKey(blank=True, help_text='the service metadata targeted by this check', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.servicemetadata', verbose_name='service metadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckconfigurationinternal',
            name='mandatory_rule_sets',
            field=models.ManyToManyField(related_name='mandatory_rule_sets', to='quality.RuleSet'),
        ),
        migrations.AddField(
            model_name='conformitycheckconfigurationinternal',
            name='optional_rule_sets',
            field=models.ManyToManyField(blank=True, related_name='optional_rule_sets', to='quality.RuleSet'),
        ),
    ]
