# Generated by Django 3.2.4 on 2021-08-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0001_initial'),
        ('quality', '0002_rename_metadata_conformitycheckrun_dataset_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformitycheckrun',
            name='feature_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.featuretype'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='feature_type_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.featuretypemetadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.layer'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='layer_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.layermetadata'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.service'),
        ),
        migrations.AddField(
            model_name='conformitycheckrun',
            name='service_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.servicemetadata'),
        ),
        migrations.AlterField(
            model_name='conformitycheckrun',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.datasetmetadata'),
        ),
    ]
