# Generated by Django 3.2.9 on 2022-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0, help_text='the current progress of the process as per', verbose_name='progress')),
                ('phase', models.CharField(help_text='Current phase of the process', max_length=256, verbose_name='phase')),
                ('name', models.CharField(choices=[('harvesting', 'harvesting'), ('monitoring', 'monitoring'), ('registering', 'registering')], help_text='Human readable short name of this process', max_length=32, verbose_name='name')),
                ('description', models.CharField(help_text='Human readable description of what this process does', max_length=128, verbose_name='description')),
                ('threads', models.ManyToManyField(related_name='processes', related_query_name='process', to='django_celery_results.TaskResult')),
            ],
            options={
                'verbose_name': 'Background Process',
                'verbose_name_plural': 'Background Processes',
            },
        ),
    ]
