# Generated by Django 5.2.8 on 2025-11-24 14:58

import django.contrib.postgres.fields
import django.db.models.deletion
import notify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime')),
                ('done_at', models.DateTimeField(blank=True, help_text='Datetime field when the process was completed in UTC', null=True, verbose_name='Completed DateTime')),
                ('phase', models.CharField(help_text='Current phase of the process', max_length=512, verbose_name='phase')),
                ('total_steps', models.IntegerField(default=None, help_text='total steps of processing', null=True, verbose_name='total')),
                ('done_steps', models.IntegerField(default=0, help_text='done steps of processing', verbose_name='done')),
                ('process_type', models.CharField(choices=[('harvesting', 'Harvesting'), ('monitoring', 'Monitoring'), ('registering', 'Registering')], help_text='tells you what kind of process this is', max_length=32, verbose_name='process type')),
                ('description', models.CharField(help_text='Human readable description of what this process does', max_length=512, verbose_name='description')),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('related_resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('threads', models.ManyToManyField(blank=True, related_name='processes', related_query_name='process', to='django_celery_results.taskresult')),
            ],
            options={
                'verbose_name': 'Background Process',
                'verbose_name_plural': 'Background Processes',
            },
        ),
        migrations.CreateModel(
            name='BackgroundProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime')),
                ('extented_description', models.FileField(help_text='this can be the response content for example', null=True, upload_to=notify.models.extented_description_file_path, verbose_name='Extented Description')),
                ('background_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', related_query_name='log', to='notify.backgroundprocess')),
            ],
        ),
    ]
