# Generated by Django 5.2.8 on 2025-12-15 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='backgroundprocesslog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
    ]
