# Generated by Django 3.2.9 on 2022-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='description',
            field=models.CharField(help_text='Human readable description of what this process does', max_length=512, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='backgroundprocess',
            name='phase',
            field=models.CharField(help_text='Current phase of the process', max_length=512, verbose_name='phase'),
        ),
    ]
