# Generated by Django 6.0.8 on 2026-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_results', '0014_alter_taskresult_status'),
        ('notify', '0003_backgroundprocess_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='backgroundprocess',
            index=models.Index(fields=['date_created'], name='bgproc_date_created_idx'),
        ),
    ]
