# Generated by Django 5.1.2 on 2024-12-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_backgroundprocess_done_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='done_steps',
            field=models.IntegerField(default=0, help_text='done steps of processing', verbose_name='done'),
        ),
        migrations.AlterField(
            model_name='backgroundprocess',
            name='total_steps',
            field=models.IntegerField(default=None, help_text='total steps of processing', null=True, verbose_name='total'),
        ),
    ]
