# Generated by Django 5.1.2 on 2024-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_alter_backgroundprocess_done_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundprocess',
            name='done_at',
            field=models.DateTimeField(blank=True, help_text='Datetime field when the process was completed in UTC', null=True, verbose_name='Completed DateTime'),
        ),
    ]
