# Generated by Django 5.1.2 on 2025-02-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_backgroundprocess_done_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime')),
                ('background_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.backgroundprocess')),
            ],
        ),
    ]
