# Generated by Django 5.1.7 on 2025-03-18 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0009_backgroundprocess_celery_task_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='celery_task_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
    ]
