from django.utils.translation import gettext_lazy as _
from extras.enums import SmartIntegerChoices

class MetadataCharsetChoices(SmartIntegerChoices):
    """Represents all valueable choices for MD_CharacterSetCode<<CodeList>> ISO19139"""
    # 16-bit fixed size Universal Character Set, based on ISO/IEC 10646
    UCS2 = 2, _("ucs2")
    # 32-bit fixed size Universal Character Set, based on ISO/IEC 10646
    UCS4 = 3, _("ucs4")
    # 7-bit variable size UCS Transfer Format, based on ISO/IEC 10646
    utf7 = 4, _("utf7")
    # 8-bit variable size UCS Transfer Format, based on ISO/IEC 10646
    UTF8 = 5, _("utf8")
    # 16-bit variable size UCS Transfer Format, based on ISO/IEC 10646
    utf16 = 6, _("utf16")
    # ISO/IEC 8859-1, Information technology - 8-bit single-byte coded graphic character sets - Part 1: Latin alphabet No. 1
    PART1 = 7, _("8859part1")
    # ISO/IEC 8859-2, Information technology - 8-bit single-byte coded graphic character sets - Part 2: Latin alphabet No. 2
    PART2 = 8, _("8859part2")
    # ISO/IEC 8859-3, Information technology - 8-bit single-byte coded graphic character sets - Part 3: Latin alphabet No. 3
    PART3 = 9, _("8859part3")
    # ISO/IEC 8859-4, Information technology - 8-bit single-byte coded graphic character sets - Part 4: Latin alphabet No. 4
    PART4 = 10, _("8859part4")
    # ISO/IEC 8859-51, Information technology - 8-bit single-byte coded graphic character sets - Part 5: Latin/Cyrillic alphabet
    PART5 = 11, _("8859part5")
    # ISO/IEC 8859-6, Information technology - 8-bit single-byte coded graphic character sets - Part 6: Latin/Arabic alphabet
    PART6 = 12, _("8859part6")
    # ISO/IEC 8859-7, Information technology - 8-bit single-byte coded graphic character sets - Part 7: Latin/Greek alphabet
    PART7 = 13, _("8859part7")
    # ISO/IEC 8859-8, Information technology - 8-bit single-byte coded graphic character sets - Part 8: Latin/Hebrew alphabet
    PART8 = 14, _("8859part8")
    # ISO/IEC8859-9, Information technology - 8-bit single-byte coded graphic character sets - Part 9: Latin alphabet No. 5
    PART9 = 15, _("8859part9")
    # ISO/IEC 8859-10, Information technology - 8-bit single-byte coded graphic character sets - Part 10: Latin alphabet No. 6
    PART10 = 16, _("8859part10")
    # ISO/IEC 8859-11, Information technology - 8-bit single-byte coded graphic character sets - Part 11: Latin/Thai alphabet
    PART11 = 17, _("8859part11")
    # 18 (reserved for future use) a future ISO/IEC 8-bit single-byte coded graphic character set (e.g. possibly ISO/IEC 8859-12
    # ISO/IEC 8859-13, Information technology - 8-bit single-byte coded graphic character sets - Part 13: Latin alphabet No. 7
    PART13 = 19, _("8859part13")
    # ISO/IEC 8859-14, Information technology - 8-bit single-byte coded graphic character sets - Part 14: Latin alphabet No. 8 (Celtic)
    PART14 = 20, _("8859part14")
    # ISO/IEC 8859-15, Information technology - 8-bit single-byte coded graphic character sets - Part 15: Latin alphabet No. 9
    PART15 = 21, _("8859part15")
    # ISO/IEC 8859-16, Information technology - 8-bit single-byte coded graphic character sets - Part 16: Latin alphabet No. 10
    PART16 = 22, _("8859part16")
    JIS = 23, _("jis")  # japanese code set used for electronic transmission
    # japanese code set used on MS-DOS based machines
    SHIFT_JIS = 24, _("shiftJIS")
    EUC_JP = 25, _("eucJP")  # japanese code set used on UNIX based machines
    US_ASCII = 26, _("usAscii")  # united states ASCII code set (ISO 646 US)
    EBCDIC = 27, _("ebcdic")  # ibm mainframe code set
    EUC_KR = 28, _("eucKR")  # korean code set
    # traditional Chinese code set used in Taiwan, HongKong of China and other areas
    BID_5 = 29, _("big5")
    GB2312 = 30, _("GB2312")  # simplified Chinese code set


class UpdateFrequencyChoices(SmartIntegerChoices):
    """Represents all valueable choices for MD_MaintenanceFrequencyCode<<CodeList>> ISO19139"""

    CONTINUAL = 2, _("continual")  # data is repeatedly and frequently updated
    DAILY = 3, _("daily")  # data is updated each day
    WEEKLY = 4, _("weekly")  # data is updated on a weekly basis
    FORTNIGHTLY = 5, _("fortnightly")  # data is updated every two weeks
    MONTHLY = 6, _("monthly")  # data is updated each month
    QUARTERLY = 7, _("querterly")  # data is updated every three months
    biannually = 8, _("biannually")  # data is updated twice each year
    annually = 9, _("annually")  # data is updated every year
    ASNEEDED = 10, _("as needed")  # data is updated as deemed necessary
    # data is updated in intervals that are uneven in duration
    IRREGULAR = 11, _("irregular")
    NOTPLANNED = 12, _("not planned")  # there are no plans to update the data
    # frequency of maintenance for the data is not known
    UNKNOWN = 13, _("unknown")


class CategoryChoices(SmartIntegerChoices):
    """Represents all valueable choices for  MD_TopicCategoryCode<<CodeList>> ISO19115-2"""
    """
        farming, biota, boundaries, climatologyMeteorologyAtmosphere, economy, elevation,
        environement, geoscientificInformation, health, imageryBaseMapsEarchCover,
        intelligenceMilitary, inlandWaters, location, oceans, planningCadastre, society, structure,
        transportation, utilitiesCommunication
    """
    FARMING = 1, _("farming")  # rearing of animals and/or cultivation of plants Examples: agriculture, irrigation, aquaculture, plantations, herding, pests and diseases affecting crops and livestock
    BIOTA = 2, _("biota")  # flora and fauna Examples: vegetation, wildlife, ecosystems, habitats, species distribution
    BOUNDARIES = 3, _("boundaries")  # political and administrative boundaries
    CLIMATOLOGYMETEOROLOGYATMOSPHERE = 4, _("climatologyMeteorologyAtmosphere") # processes and phenomena of the atmosphere Examples: cloud cover, weather, climate, atmospheric conditions, climate change, precipitation
    ECONOMY = 5, _("economy")  # economic activities and conditions Examples: employment, industries, income, production, consumption, trade, tourism
    ELEVATION = 6, _("elevation")  # height or depth of the Earth's surface Examples: topography, bathymetry, slope, terrain models, contours, digital elevation
    ENVIRONEMENT = 7, _("environement")  # environmental resources, protection and conservation Examples: natural resources, pollution, environmental monitoring, environmental impact assessments
    GEOSCIENTIFICINFORMATION = 8, _("geoscientificInformation")  # solid Earth and its processes Examples: geology, geophysics, soils, minerals, seismic activity, volcanology
    HEALTH = 9, _("health")  # human health and disease Examples: disease distribution, health facilities, sanitation, epidemiology
    IMAGERYBASEMAPSEARTHCOVER = 10, _("imageryBaseMapsEarchCover")  # remotely sensed imagery and base maps Examples: satellite imagery, aerial photography, land cover, land use
    INTELLIGENCEMILITARY = 11, _("intelligenceMilitary")  # military bases, facilities, operations and activities
    INLANDWATERS = 12, _("inlandWaters")  # water courses and bodies on the Earth's surface Examples: rivers, lakes, wetlands, reservoirs, watersheds
    LOCATION = 13, _("location")  # named locations and their associated information Examples: place names, postal codes, address locations
    OCEANS = 14, _("oceans")  # marine and coastal areas Examples: sea floor, coastal zones, marine ecosystems, oceanographic features
    PLANNINGCADASTRE = 15, _("planningCadastre")  # land use planning and cadastral information Examples: zoning, land parcels, property boundaries, land ownership
    SOCIETY = 16, _("society")  # social systems and activities Examples: demographics, education, culture, religion, social services
    STRUCTURE = 17, _("structure")  # man-made features and structures Examples: buildings, infrastructure, utilities, transportation networks
    TRANSPORTATION = 18, _("transportation")  # transport networks and services Examples: roads, railways, airports, public transit
    UTILITIESCOMMUNICATION = 19, _("utilitiesCommunication")  # utility and communication networks Examples: power lines, water supply, telecommunications, broadcasting
    

class LanguageChoices(SmartIntegerChoices):
    # ISO 639-2 language codes
    AAR = 1, _("aar")  # Afar
    ABK = 2, _("abk")  # Abkhazian
    ACE = 3, _("ace")  # Achinese
    ACH = 4, _("ach")  # Acoli
    ADA = 5, _("ada")  # Adangme
    ADY = 6, _("ady")  # Adyghe ; Adygei
    AFA = 7, _("afa")  # Afro-Asiatic languages
    AFH = 8, _("afh")  # Afrihili
    AFR = 9, _("afr")  # Afrikaans
    AIN = 10, _("ain")  # Ainu
    AKA = 11, _("aka")  # Akan
    AKK = 12, _("akk")  # Akkadian
    ALE = 13, _("ale")  # Aleut
    ALG = 14, _("alg")  # Algonquian languages
    ALT = 15, _("alt")  # Southern Altai
    AMH = 16, _("amh")  # Amharic
    ANG = 17, _("ang")  # English, Old (ca.450–1100)
    ANP = 18, _("anp")  # Angika
    APA = 19, _("apa")  # Apache languages
    ARA = 20, _("ara")  # Arabic
    ARC = 21, _("arc")  # Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)
    ARG = 22, _("arg")  # Aragonese
    ARN = 23, _("arn")  # Mapudungun; Mapuche
    ARP = 24, _("arp")  # Arapaho
    ART = 25, _("art")  # Artificial languages
    ARW = 26, _("arw")  # Arawak
    ASM = 27, _("asm")  # Assamese
    AST = 28, _("ast")  # Asturian ; Bable ; Leonese ; Asturleonese
    ATH = 29, _("ath")  # Athapascan languages
    AUS = 30, _("aus")  # Australian languages
    AVA = 31, _("ava")  # Avaric
    AVE = 32, _("ave")  # Avestan
    AWA = 33, _("awa")  # Awadhi
    AYM = 34, _("aym")  # Aymara
    AZE = 35, _("aze")  # Azerbaijani
    BAD = 36, _("bad")  # Banda languages
    BAI = 37, _("bai")  # Bamileke languages
    BAK = 38, _("bak")  # Bashkir
    BAL = 39, _("bal")  # Baluchi
    BAM = 40, _("bam")  # Bambara
    BAN = 41, _("ban")  # Balinese
    BAS = 42, _("bas")  # Basa
    BAT = 43, _("bat")  # Baltic languages
    BEJ = 44, _("bej")  # Beja ; Bedawiyet
    BEL = 45, _("bel")  # Belarusian
    BEM = 46, _("bem")  # Bemba
    BEN = 47, _("ben")  # Bengali
    BER = 48, _("ber")  # Berber languages
    BHO = 49, _("bho")  # Bhojpuri
    BIH = 50, _("bih")  # Bihari languages
    BIK = 51, _("bik")  # Bikol
    BIN = 52, _("bin")  # Bini ; Edo
    BIS = 53, _("bis")  # Bislama
    BLA = 54, _("bla")  # Siksika
    BNT = 55, _("bnt")  # Bantu languages
    BOD = 56, _("bod")  # Tibetan
    TIB = 57, _("tib")  # Tibetan
    BOS = 58, _("bos")  # Bosnian
    BRA = 59, _("bra")  # Braj
    BRE = 60, _("bre")  # Breton
    BTK = 61, _("btk")  # Batak languages
    BUA = 62, _("bua")  # Buriat
    BUG = 63, _("bug")  # Buginese
    BUL = 64, _("bul")  # Bulgarian
    BYN = 65, _("byn")  # Blin; Bilin
    CAD = 66, _("cad")  # Caddo
    CAI = 67, _("cai")  # Central American Indian languages
    CAR = 68, _("car")  # Galibi Carib
    CAT = 69, _("cat")  # Catalan ; Valencian
    CAU = 70, _("cau")  # Caucasian languages
    CEB = 71, _("ceb")  # Cebuano
    CEL = 72, _("cel")  # Celtic languages
    CES = 73, _("ces")  # Czech
    CZE = 74, _("cze")  # Czech
    CHA = 75, _("cha")  # Chamorro
    CHB = 76, _("chb")  # Chibcha
    CHE = 77, _("che")  # Chechen
    CHG = 78, _("chg")  # Chagatai
    CHK = 79, _("chk")  # Chuukese
    CHM = 80, _("chm")  # Mari
    CHN = 81, _("chn")  # Chinook Jargon
    CHO = 82, _("cho")  # Choctaw
    CHP = 83, _("chp")  # Chipewyan ; Dene Suline
    CHR = 84, _("chr")  # Cherokee
    CHU = 85, _("chu")  # Church Slavic ; Old Slavonic ; Church Slavonic ; Old Bulgarian ; Old Church Slavonic
    CHV = 86, _("chv")  # Chuvash
    CHY = 87, _("chy")  # Cheyenne
    CMC = 88, _("cmc")  # Chamic languages
    CNR = 89, _("cnr")  # Montenegrin
    COP = 90, _("cop")  # Coptic
    COR = 91, _("cor")  # Cornish
    COS = 92, _("cos")  # Corsican
    CPE = 93, _("cpe")  # Creoles and pidgins , English based
    CPF = 94, _("cpf")  # Creoles and pidgins, French-based
    CPP = 95, _("cpp")  # Creoles and pidgins, Portuguese-based
    CRE = 96, _("cre")  # Cree
    CRH = 97, _("crh")  # Crimean Tatar ; Crimean Turkish
    CRP = 98, _("crp")  # Creoles and pidgins
    CSB = 99, _("csb")  # Kashubian
    CUS = 100, _("cus")  # Cushitic languages
    CYM = 101, _("cym")  # Welsh
    WEL = 102, _("wel")  # Welsh
    DAK = 103, _("dak")  # Dakota
    DAN = 104, _("dan")  # Danish
    DAR = 105, _("dar")  # Dargwa
    DAY = 106, _("day")  # Land Dayak languages
    DEL = 107, _("del")  # Delaware
    DEN = 108, _("den")  # Slave (Athapascan)
    DEU = 109, _("deu")  # German
    GER = 110, _("ger")  # German
    DGR = 111, _("dgr")  # Tlicho; Dogrib
    DIN = 112, _("din")  # Dinka
    DIV = 113, _("div")  # Divehi; Dhivehi; Maldivian
    DOI = 114, _("doi")  # Dogri
    DRA = 115, _("dra")  # Dravidian languages
    DSB = 116, _("dsb")  # Lower Sorbian
    DUA = 117, _("dua")  # Duala
    DUM = 118, _("dum")  # Dutch, Middle (ca.1050–1350)
    DYU = 119, _("dyu")  # Dyula
    DZO = 120, _("dzo")  # Dzongkha
    EFI = 121, _("efi")  # Efik
    EGY = 122, _("egy")  # Egyptian (Ancient)
    EKA = 123, _("eka")  # Ekajuk
    ELL = 124, _("ell")  # Greek, Modern (1453–)
    GRE = 125, _("gre")  # Greek, Modern (1453–)
    ELX = 126, _("elx")  # Elamite
    ENG = 127, _("eng")  # English
    ENM = 128, _("enm")  # English, Middle (1100–1500)
    EPO = 129, _("epo")  # Esperanto
    EST = 130, _("est")  # Estonian
    EUS = 131, _("eus")  # Basque
    BAQ = 132, _("baq")  # Basque
    EWE = 133, _("ewe")  # Ewe
    EWO = 134, _("ewo")  # Ewondo
    FAN = 135, _("fan")  # Fang
    FAO = 136, _("fao")  # Faroese
    FAS = 137, _("fas")  # Persian
    PER = 138, _("per")  # Persian
    FAT = 139, _("fat")  # Fanti
    FIJ = 140, _("fij")  # Fijian
    FIL = 141, _("fil")  # Filipino ; Pilipino
    FIN = 142, _("fin")  # Finnish
    FIU = 143, _("fiu")  # Finno-Ugrian languages
    FON = 144, _("fon")  # Fon
    FRA = 145, _("fra")  # French
    FRE = 146, _("fre")  # French
    FRM = 147, _("frm")  # French, Middle (ca.1400–1600)
    FRO = 148, _("fro")  # French, Old (842–ca.1400)
    FRR = 149, _("frr")  # Northern Frisian
    FRS = 150, _("frs")  # Eastern Frisian
    FRY = 151, _("fry")  # Western Frisian
    FUL = 152, _("ful")  # Fulah
    FUR = 153, _("fur")  # Friulian
    GAA = 154, _("gaa")  # Ga
    GAY = 155, _("gay")  # Gayo
    GBA = 156, _("gba")  # Gbaya
    GEM = 157, _("gem")  # Germanic languages
    GEZ = 158, _("gez")  # Geez
    GIL = 159, _("gil")  # Gilbertese
    GLA = 160, _("gla")  # Gaelic ; Scottish Gaelic
    GLE = 161, _("gle")  # Irish
    GLG = 162, _("glg")  # Galician
    GLV = 163, _("glv")  # Manx
    GMH = 164, _("gmh")  # German, Middle High (ca.1050–1500)
    GOH = 165, _("goh")  # German, Old High (ca.750–1050)
    GON = 166, _("gon")  # Gondi
    GOR = 167, _("gor")  # Gorontalo
    GOT = 168, _("got")  # Gothic
    GRB = 169, _("grb")  # Grebo
    GRC = 170, _("grc")  # Greek, Ancient (to 1453)
    GRN = 171, _("grn")  # Guarani
    GSW = 172, _("gsw")  # Swiss German ; Alemannic ; Alsatian
    GUJ = 173, _("guj")  # Gujarati
    GWI = 174, _("gwi")  # Gwich'in
    HAI = 175, _("hai")  # Haida
    HAT = 176, _("hat")  # Haitian; Haitian Creole
    HAU = 177, _("hau")  # Hausa
    HAW = 178, _("haw")  # Hawaiian
    HEB = 179, _("heb")  # Hebrew
    HER = 180, _("her")  # Herero
    HIL = 181, _("hil")  # Hiligaynon
    HIM = 182, _("him")  # Himachali languages; Pahari languages
    HIN = 183, _("hin")  # Hindi
    HIT = 184, _("hit")  # Hittite
    HMN = 185, _("hmn")  # Hmong ; Mong
    HMO = 186, _("hmo")  # Hiri Motu
    HRV = 187, _("hrv")  # Croatian
    HSB = 188, _("hsb")  # Upper Sorbian
    HUN = 189, _("hun")  # Hungarian
    HUP = 190, _("hup")  # Hupa
    HYE = 191, _("hye")  # Armenian
    ARM = 192, _("arm")  # Armenian
    IBA = 193, _("iba")  # Iban
    IBO = 194, _("ibo")  # Igbo
    IDO = 195, _("ido")  # Ido
    III = 196, _("iii")  # Sichuan Yi ; Nuosu
    IJO = 197, _("ijo")  # Ijo languages
    IKU = 198, _("iku")  # Inuktitut
    ILE = 199, _("ile")  # Interlingue; Occidental
    ILO = 200, _("ilo")  # Iloko
    INA = 201, _("ina")  # Interlingua ( International Auxiliary Language Association )
    INC = 202, _("inc")  # Indic languages
    IND = 203, _("ind")  # Indonesian
    INE = 204, _("ine")  # Indo-European languages
    INH = 205, _("inh")  # Ingush
    IPK = 206, _("ipk")  # Inupiaq
    IRA = 207, _("ira")  # Iranian languages
    IRO = 208, _("iro")  # Iroquoian languages
    ISL = 209, _("isl")  # Icelandic
    ICE = 210, _("ice")  # Icelandic
    ITA = 211, _("ita")  # Italian
    JAV = 212, _("jav")  # Javanese
    JBO = 213, _("jbo")  # Lojban
    JPN = 214, _("jpn")  # Japanese
    JPR = 215, _("jpr")  # Judeo-Persian
    JRB = 216, _("jrb")  # Judeo-Arabic
    KAA = 217, _("kaa")  # Kara-Kalpak
    KAB = 218, _("kab")  # Kabyle
    KAC = 219, _("kac")  # Kachin ; Jingpho
    KAL = 220, _("kal")  # Kalaallisut ; Greenlandic
    KAM = 221, _("kam")  # Kamba
    KAN = 222, _("kan")  # Kannada
    KAR = 223, _("kar")  # Karen languages
    KAS = 224, _("kas")  # Kashmiri
    KAT = 225, _("kat")  # Georgian
    GEO = 226, _("geo")  # Georgian
    KAU = 227, _("kau")  # Kanuri
    KAW = 228, _("kaw")  # Kawi
    KAZ = 229, _("kaz")  # Kazakh
    KBD = 230, _("kbd")  # Kabardian
    KHA = 231, _("kha")  # Khasi
    KHI = 232, _("khi")  # Khoisan languages
    KHM = 233, _("khm")  # Central Khmer
    KHO = 234, _("kho")  # Khotanese ; Sakan
    KIK = 235, _("kik")  # Kikuyu ; Gikuyu
    KIN = 236, _("kin")  # Kinyarwanda
    KIR = 237, _("kir")  # Kirghiz ; Kyrgyz
    KMB = 238, _("kmb")  # Kimbundu
    KOK = 239, _("kok")  # Konkani
    KOM = 240, _("kom")  # Komi
    KON = 241, _("kon")  # Kongo
    KOR = 242, _("kor")  # Korean
    KOS = 243, _("kos")  # Kosraean
    KPE = 244, _("kpe")  # Kpelle
    KRC = 245, _("krc")  # Karachay-Balkar
    KRL = 246, _("krl")  # Karelian
    KRO = 247, _("kro")  # Kru languages
    KRU = 248, _("kru")  # Kurukh
    KUA = 249, _("kua")  # Kuanyama ; Kwanyama
    KUM = 250, _("kum")  # Kumyk
    KUR = 251, _("kur")  # Kurdish
    KUT = 252, _("kut")  # Kutenai
    LAD = 253, _("lad")  # Ladino
    LAH = 254, _("lah")  # Lahnda
    LAM = 255, _("lam")  # Lamba
    LAO = 256, _("lao")  # Lao
    LAT = 257, _("lat")  # Latin
    LAV = 258, _("lav")  # Latvian
    LEZ = 259, _("lez")  # Lezghian
    LIM = 260, _("lim")  # Limburgan ; Limburger ; Limburgish
    LIN = 261, _("lin")  # Lingala
    LIT = 262, _("lit")  # Lithuanian
    LOL = 263, _("lol")  # Mongo
    LOZ = 264, _("loz")  # Lozi
    LTZ = 265, _("ltz")  # Luxembourgish ; Letzeburgesch
    LUA = 266, _("lua")  # Luba-Lulua
    LUB = 267, _("lub")  # Luba-Katanga
    LUG = 268, _("lug")  # Ganda
    LUI = 269, _("lui")  # Luiseno
    LUN = 270, _("lun")  # Lunda
    LUO = 271, _("luo")  # Luo (Kenya and Tanzania)
    LUS = 272, _("lus")  # Lushai
    MAD = 273, _("mad")  # Madurese
    MAG = 274, _("mag")  # Magahi
    MAH = 275, _("mah")  # Marshallese
    MAI = 276, _("mai")  # Maithili
    MAK = 277, _("mak")  # Makasar
    MAL = 278, _("mal")  # Malayalam
    MAN = 279, _("man")  # Mandingo
    MAP = 280, _("map")  # Austronesian languages
    MAR = 281, _("mar")  # Marathi
    MAS = 282, _("mas")  # Masai
    MDF = 283, _("mdf")  # Moksha
    MDR = 284, _("mdr")  # Mandar
    MEN = 285, _("men")  # Mende
    MGA = 286, _("mga")  # Irish, Middle (900–1200)
    MIC = 287, _("mic")  # Mi'kmaq ; Micmac
    MIN = 288, _("min")  # Minangkabau
    MIS = 289, _("mis")  # Uncoded languages
    MKD = 290, _("mkd")  # Macedonian
    MAC = 291, _("mac")  # Macedonian
    MKH = 292, _("mkh")  # Mon-Khmer languages
    MLG = 293, _("mlg")  # Malagasy
    MLT = 294, _("mlt")  # Maltese
    MNC = 295, _("mnc")  # Manchu
    MNI = 296, _("mni")  # Manipuri
    MNO = 297, _("mno")  # Manobo languages
    MOH = 298, _("moh")  # Mohawk
    MON = 299, _("mon")  # Mongolian
    MOS = 300, _("mos")  # Mossi
    MRI = 301, _("mri")  # Maori
    MAO = 302, _("mao")  # Maori
    MSA = 303, _("msa")  # Malay
    MAY = 304, _("may")  # Malay
    MUL = 305, _("mul")  # Multiple languages
    MUN = 306, _("mun")  # Munda languages
    MUS = 307, _("mus")  # Creek
    MWL = 308, _("mwl")  # Mirandese
    MWR = 309, _("mwr")  # Marwari
    MYA = 310, _("mya")  # Burmese
    BUR = 311, _("bur")  # Burmese
    MYN = 312, _("myn")  # Mayan languages
    MYV = 313, _("myv")  # Erzya
    NAH = 314, _("nah")  # Nahuatl languages
    NAI = 315, _("nai")  # North American Indian languages
    NAP = 316, _("nap")  # Neapolitan
    NAU = 317, _("nau")  # Nauru
    NAV = 318, _("nav")  # Navajo ; Navaho
    NBL = 319, _("nbl")  # Ndebele, South; South Ndebele
    NDE = 320, _("nde")  # Ndebele, North; North Ndebele
    NDO = 321, _("ndo")  # Ndonga
    NDS = 322, _("nds")  # Low German ; Low Saxon; German, Low; Saxon, Low
    NEP = 323, _("nep")  # Nepali
    NEW = 324, _("new")  # Nepal Bhasa ; Newari
    NIA = 325, _("nia")  # Nias
    NIC = 326, _("nic")  # Niger-Kordofanian languages
    NIU = 327, _("niu")  # Niuean
    NLD = 328, _("nld")  # Dutch ; Flemish
    DUT = 329, _("dut")  # Dutch ; Flemish
    NNO = 330, _("nno")  # Norwegian Nynorsk ; Nynorsk, Norwegian
    NOB = 331, _("nob")  # Bokmål , Norwegian; Norwegian Bokmål
    NOG = 332, _("nog")  # Nogai
    NON = 333, _("non")  # Norse, Old
    NOR = 334, _("nor")  # Norwegian
    NQO = 335, _("nqo")  # N'Ko
    NSO = 336, _("nso")  # Pedi ; Sepedi ; Northern Sotho
    NUB = 337, _("nub")  # Nubian languages
    NWC = 338, _("nwc")  # Classical Newari ; Old Newari ; Classical Nepal Bhasa
    NYA = 339, _("nya")  # Chichewa ; Chewa ; Nyanja
    NYM = 340, _("nym")  # Nyamwezi
    NYN = 341, _("nyn")  # Nyankole
    NYO = 342, _("nyo")  # Nyoro
    NZI = 343, _("nzi")  # Nzima
    OCI = 344, _("oci")  # Occitan (post 1500)
    OJI = 345, _("oji")  # Ojibwa
    ORI = 346, _("ori")  # Oriya
    ORM = 347, _("orm")  # Oromo
    OSA = 348, _("osa")  # Osage
    OSS = 349, _("oss")  # Ossetian ; Ossetic
    OTA = 350, _("ota")  # Turkish, Ottoman (1500–1928)
    OTO = 351, _("oto")  # Otomian languages
    PAA = 352, _("paa")  # Papuan languages
    PAG = 353, _("pag")  # Pangasinan
    PAL = 354, _("pal")  # Pahlavi
    PAM = 355, _("pam")  # Pampanga ; Kapampangan
    PAN = 356, _("pan")  # Panjabi ; Punjabi
    PAP = 357, _("pap")  # Papiamento
    PAU = 358, _("pau")  # Palauan
    PEO = 359, _("peo")  # Persian, Old (ca.600–400 B.C.)
    PHI = 360, _("phi")  # Philippine languages
    PHN = 361, _("phn")  # Phoenician
    PLI = 362, _("pli")  # Pali
    POL = 363, _("pol")  # Polish
    PON = 364, _("pon")  # Pohnpeian
    POR = 365, _("por")  # Portuguese
    PRA = 366, _("pra")  # Prakrit languages
    PRO = 367, _("pro")  # Provençal, Old (to 1500); Old Occitan (to 1500)
    PUS = 368, _("pus")  # Pushto ; Pashto
    QAA = 369, _("qaa")  # Reserved for local use
    QTZ = 370, _("qtz")  # Reserved for local use
    QUE = 371, _("que")  # Quechua
    RAJ = 372, _("raj")  # Rajasthani
    RAP = 373, _("rap")  # Rapanui
    RAR = 374, _("rar")  # Rarotongan; Cook Islands Maori
    ROA = 375, _("roa")  # Romance languages
    ROH = 376, _("roh")  # Romansh
    ROM = 377, _("rom")  # Romany
    RON = 378, _("ron")  # Romanian ; Moldavian; Moldovan
    RUM = 379, _("rum")  # Romanian ; Moldavian; Moldovan
    RUN = 380, _("run")  # Rundi
    RUP = 381, _("rup")  # Aromanian ; Arumanian; Macedo-Romanian [ b ]
    RUS = 382, _("rus")  # Russian
    SAD = 383, _("sad")  # Sandawe
    SAG = 384, _("sag")  # Sango
    SAH = 385, _("sah")  # Yakut
    SAI = 386, _("sai")  # South American Indian languages
    SAL = 387, _("sal")  # Salishan languages
    SAM = 388, _("sam")  # Samaritan Aramaic
    SAN = 389, _("san")  # Sanskrit
    SAS = 390, _("sas")  # Sasak
    SAT = 391, _("sat")  # Santali
    SCN = 392, _("scn")  # Sicilian
    SCO = 393, _("sco")  # Scots
    SEL = 394, _("sel")  # Selkup
    SEM = 395, _("sem")  # Semitic languages
    SGA = 396, _("sga")  # Irish, Old (to 900)
    SGN = 397, _("sgn")  # Sign languages
    SHN = 398, _("shn")  # Shan
    SID = 399, _("sid")  # Sidamo
    SIN = 400, _("sin")  # Sinhala ; Sinhalese
    SIO = 401, _("sio")  # Siouan languages
    SIT = 402, _("sit")  # Sino-Tibetan languages
    SLA = 403, _("sla")  # Slavic languages
    SLK = 404, _("slk")  # Slovak
    SLO = 405, _("slo")  # Slovak
    SLV = 406, _("slv")  # Slovenian
    SMA = 407, _("sma")  # Southern Sami
    SME = 408, _("sme")  # Northern Sami
    SMI = 409, _("smi")  # Sami languages
    SMJ = 410, _("smj")  # Lule Sami
    SMN = 411, _("smn")  # Inari Sami
    SMO = 412, _("smo")  # Samoan
    SMS = 413, _("sms")  # Skolt Sami
    SNA = 414, _("sna")  # Shona
    SND = 415, _("snd")  # Sindhi
    SNK = 416, _("snk")  # Soninke
    SOG = 417, _("sog")  # Sogdian
    SOM = 418, _("som")  # Somali
    SON = 419, _("son")  # Songhai languages
    SOT = 420, _("sot")  # Sotho, Southern
    SPA = 421, _("spa")  # Spanish ; Castilian
    SQI = 422, _("sqi")  # Albanian
    ALB = 423, _("alb")  # Albanian
    SRD = 424, _("srd")  # Sardinian
    SRN = 425, _("srn")  # Sranan Tongo
    SRP = 426, _("srp")  # Serbian
    SRR = 427, _("srr")  # Serer
    SSA = 428, _("ssa")  # Nilo-Saharan languages
    SSW = 429, _("ssw")  # Swati
    SUK = 430, _("suk")  # Sukuma
    SUN = 431, _("sun")  # Sundanese
    SUS = 432, _("sus")  # Susu
    SUX = 433, _("sux")  # Sumerian
    SWA = 434, _("swa")  # Swahili
    SWE = 435, _("swe")  # Swedish
    SYC = 436, _("syc")  # Classical Syriac
    SYR = 437, _("syr")  # Syriac
    TAH = 438, _("tah")  # Tahitian
    TAI = 439, _("tai")  # Tai languages
    TAM = 440, _("tam")  # Tamil
    TAT = 441, _("tat")  # Tatar
    TEL = 442, _("tel")  # Telugu
    TEM = 443, _("tem")  # Timne
    TER = 444, _("ter")  # Tereno
    TET = 445, _("tet")  # Tetum
    TGK = 446, _("tgk")  # Tajik
    TGL = 447, _("tgl")  # Tagalog
    THA = 448, _("tha")  # Thai
    TIG = 449, _("tig")  # Tigre
    TIR = 450, _("tir")  # Tigrinya
    TIV = 451, _("tiv")  # Tiv
    TKL = 452, _("tkl")  # Tokelau
    TLH = 453, _("tlh")  # Klingon ; tlhIngan-Hol
    TLI = 454, _("tli")  # Tlingit
    TMH = 455, _("tmh")  # Tamashek
    TOG = 456, _("tog")  # Tonga (Nyasa)
    TON = 457, _("ton")  # Tonga (Tonga Islands)
    TPI = 458, _("tpi")  # Tok Pisin
    TSI = 459, _("tsi")  # Tsimshian
    TSN = 460, _("tsn")  # Tswana
    TSO = 461, _("tso")  # Tsonga
    TUK = 462, _("tuk")  # Turkmen
    TUM = 463, _("tum")  # Tumbuka
    TUP = 464, _("tup")  # Tupi languages
    TUR = 465, _("tur")  # Turkish
    TUT = 466, _("tut")  # Altaic languages
    TVL = 467, _("tvl")  # Tuvalu
    TWI = 468, _("twi")  # Twi
    TYV = 469, _("tyv")  # Tuvinian
    UDM = 470, _("udm")  # Udmurt
    UGA = 471, _("uga")  # Ugaritic
    UIG = 472, _("uig")  # Uighur ; Uyghur
    UKR = 473, _("ukr")  # Ukrainian
    UMB = 474, _("umb")  # Umbundu
    UND = 475, _("und")  # Undetermined
    URD = 476, _("urd")  # Urdu
    UZB = 477, _("uzb")  # Uzbek
    VAI = 478, _("vai")  # Vai
    VEN = 479, _("ven")  # Venda
    VIE = 480, _("vie")  # Vietnamese
    VOL = 481, _("vol")  # Volapük
    VOT = 482, _("vot")  # Votic
    WAK = 483, _("wak")  # Wakashan languages
    WAL = 484, _("wal")  # Wolaitta ; Wolaytta
    WAR = 485, _("war")  # Waray
    WAS = 486, _("was")  # Washo
    WEN = 487, _("wen")  # Sorbian languages
    WLN = 488, _("wln")  # Walloon
    WOL = 489, _("wol")  # Wolof
    XAL = 490, _("xal")  # Kalmyk ; Oirat
    XHO = 491, _("xho")  # Xhosa
    YAO = 492, _("yao")  # Yao
    YAP = 493, _("yap")  # Yapese
    YID = 494, _("yid")  # Yiddish
    YOR = 495, _("yor")  # Yoruba
    YPK = 496, _("ypk")  # Yupik languages
    ZAP = 497, _("zap")  # Zapotec
    ZBL = 498, _("zbl")  # Blissymbols ; Blissymbolics ; Bliss
    ZEN = 499, _("zen")  # Zenaga
    ZGH = 500, _("zgh")  # Standard Moroccan Tamazight
    ZHA = 501, _("zha")  # Zhuang ; Chuang
    ZHO = 502, _("zho")  # Chinese
    CHI = 503, _("chi")  # Chinese
    ZND = 504, _("znd")  # Zande languages
    ZUL = 505, _("zul")  # Zulu
    ZUN = 506, _("zun")  # Zuni
    ZXX = 507, _("zxx")  # No linguistic content; Not applicable
    ZZA = 508, _("zza")  # Zaza ; Dimili ; Dimli ; Kirdki ; Kirmanjki ; Zazaki
