# Generated by Django 3.1.8 on 2021-05-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmetadata',
            name='temporal_extent_end_indeterminate_position',
            field=models.CharField(choices=[('now', 'now'), ('before', 'before'), ('after', 'after'), ('unknown', 'unknown')], default='', help_text='Use indeterminatePosition to document unknown dates and present dates. The valid values for indeterminatePosition are ‘unknown’, ‘after’, ‘before’, and ‘now’.', max_length=10, verbose_name='indeterminate start'),
        ),
        migrations.AddField(
            model_name='datasetmetadata',
            name='temporal_extent_start_indeterminate_position',
            field=models.CharField(choices=[('now', 'now'), ('before', 'before'), ('after', 'after'), ('unknown', 'unknown')], default='', help_text='Use indeterminatePosition to document unknown dates and present dates. The valid values for indeterminatePosition are ‘unknown’, ‘after’, ‘before’, and ‘now’.', max_length=10, verbose_name='indeterminate start'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='dataset_contact_metadata', related_query_name='dataset_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_metadata', related_query_name='metadata_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='temporal_extent_end',
            field=models.DateTimeField(blank=True, help_text="the end of the period in which the represented data was collected. Leave empty if the date is unknown or it's never ending.", null=True, verbose_name='time period end'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='temporal_extent_start',
            field=models.DateTimeField(blank=True, help_text='the start of the period in which the represented data was collected. Leave empty if the date is unknown.', null=True, verbose_name='time period start'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_service_metadata', related_query_name='metadata_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='service_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='service_contact_service_metadata', related_query_name='service_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
    ]
