# Generated by Django 3.2.4 on 2021-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcontext',
            name='layer_tree',
        ),
        migrations.RemoveField(
            model_name='mapcontext',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='mapcontext',
            name='abstract',
            field=models.TextField(help_text='brief summary of the topic of this map context', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='mapcontext',
            name='title',
            field=models.CharField(help_text='a short descriptive title for this map context', max_length=1000, verbose_name='title'),
        ),
    ]
