# Generated by Django 3.2.4 on 2021-08-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcontext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mapcontext',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='mapcontext',
            name='last_modified_at',
        ),
        migrations.RemoveField(
            model_name='mapcontext',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='mapcontext',
            name='owned_by_org',
        ),
    ]
