# Generated by Django 3.1.8 on 2021-06-23 08:32

import MrMap.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedoperation',
            name='secured_feature_types',
            field=models.ManyToManyField(help_text='Select one or more feature types.', related_name='allowed_operations', related_query_name='allowed_operation', to='resourceNew.FeatureType', verbose_name='secured feature types'),
        ),
        migrations.AlterField(
            model_name='allowedoperation',
            name='secured_layers',
            field=models.ManyToManyField(help_text='Select one or more layers. Note that all sub layers of a selected layer will also be secured.', related_name='allowed_operations', related_query_name='allowed_operation', to='resourceNew.Layer', verbose_name='secured layers'),
        ),
        migrations.AlterField(
            model_name='externalauthentication',
            name='test_url',
            field=models.URLField(editable=False, help_text='this shall be the full get capabilities request url.', validators=[MrMap.validators.validate_get_capablities_uri], verbose_name='Service url'),
        ),
    ]
