# Generated by Django 3.1.8 on 2021-06-14 11:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmetadata',
            name='bounding_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='charset',
            field=models.CharField(blank=True, choices=[(None, '---'), ('utf8', 'utf8')], help_text='The charset which is used by the stored data.', max_length=10, null=True, verbose_name='charset'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='dataset_contact_metadata', related_query_name='dataset_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_id_code_space',
            field=models.CharField(blank=True, help_text='code space for the given identifier', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='format',
            field=models.CharField(blank=True, choices=[(None, '---'), ('Database', 'Database'), ('Esri shape', 'Esri shape'), ('CSV', 'CSV'), ('GML', 'GML'), ('GeoTIFF', 'GeoTIFF')], help_text='The format in which the described dataset is stored.', max_length=20, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='license_source_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_metadata', related_query_name='metadata_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='use_limitation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuretypemetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='layermetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='license_source_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='use_limitation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
