# Generated by Django 3.1.8 on 2021-05-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0002_auto_20210528_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetmetadata',
            name='temporal_extent_end',
        ),
        migrations.RemoveField(
            model_name='datasetmetadata',
            name='temporal_extent_end_indeterminate_position',
        ),
        migrations.RemoveField(
            model_name='datasetmetadata',
            name='temporal_extent_start',
        ),
        migrations.RemoveField(
            model_name='datasetmetadata',
            name='temporal_extent_start_indeterminate_position',
        ),
        migrations.AddField(
            model_name='dimension',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, help_text='the related dataset metadata of this dimension entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_metadata_dimensions', related_query_name='dataset_metadata_dimension', to='resourceNew.datasetmetadata', verbose_name='dataset metadata'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='feature_type',
            field=models.ForeignKey(blank=True, help_text='the related feature type of this dimension entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_type_dimensions', related_query_name='feature_type_dimension', to='resourceNew.featuretype', verbose_name='feature type'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='dataset_contact_metadata', related_query_name='dataset_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='inspire_top_consistence',
            field=models.BooleanField(default=False, help_text='Flag to signal if the described data has a topologically consistence.'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_metadata', related_query_name='metadata_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='layer',
            field=models.ForeignKey(blank=True, help_text='the related layer of this dimension entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_dimensions', related_query_name='layer_dimension', to='resourceNew.layer', verbose_name='layer'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_service_metadata', related_query_name='metadata_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='service_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='service_contact_service_metadata', related_query_name='service_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
    ]
