# Generated by Django 3.1.8 on 2021-06-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0002_auto_20210623_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxysetting',
            old_name='configured_service',
            new_name='secured_service',
        ),
    ]
