# Generated by Django 3.2.4 on 2021-07-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httprequestlog',
            name='auth_was_used',
        ),
        migrations.AlterField(
            model_name='httprequestlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
