# Generated by Django 3.2.3 on 2021-06-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0002_auto_20210614_1357'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='resourcenew_document_one_original',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uuid',
        ),
        migrations.AddField(
            model_name='document',
            name='xml',
            field=models.TextField(default='', help_text='the xml as string.', verbose_name='xml'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='xml_backup',
            field=models.TextField(default='', help_text='the original xml as backup to restore the xml field.', verbose_name='xml backup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='dataset_contact_metadata', related_query_name='dataset_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_metadata', related_query_name='metadata_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dataset_metadata',
            field=models.OneToOneField(blank=True, help_text='the metadata object which is parsed from this xml.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.datasetmetadata', verbose_name='related dataset metadata'),
        ),
        migrations.AlterField(
            model_name='document',
            name='feature_type_metadata',
            field=models.OneToOneField(blank=True, help_text='the metadata object which is parsed from this xml.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.featuretypemetadata', verbose_name='related feature type metadata'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='layer_metadata',
            field=models.OneToOneField(blank=True, help_text='the metadata object which is parsed from this xml.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.layermetadata', verbose_name='related layer metadata'),
        ),
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.OneToOneField(blank=True, help_text='the service object which is described by this document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.service', verbose_name='related service'),
        ),
        migrations.AlterField(
            model_name='document',
            name='service_metadata',
            field=models.OneToOneField(blank=True, help_text='the metadata object which is parsed from this xml.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.servicemetadata', verbose_name='related dataset metadata'),
        ),
        migrations.AlterField(
            model_name='externalauthentication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featuretypeelement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featuretypemetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='harvestresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layermetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='legendurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mimetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operationurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='referencesystem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='remotemetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='insufficient_quality',
            field=models.TextField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='style',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeextent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
