# Generated by Django 3.2.4 on 2021-06-30 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resourceNew', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proxylog',
            managers=[
                ('response_logging', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='proxylog',
            name='query_params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proxylog',
            name='post_body',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='proxylog',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxy_logs', related_query_name='proxy_log', to='resourceNew.service'),
        ),
        migrations.AlterField(
            model_name='proxylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxy_logs', related_query_name='proxy_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
