# Generated by Django 3.2.4 on 2021-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretypeelement',
            name='maxOccurs',
        ),
        migrations.RemoveField(
            model_name='featuretypeelement',
            name='minOccurs',
        ),
        migrations.AddField(
            model_name='featuretypeelement',
            name='max_occurs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='featuretypeelement',
            name='min_occurs',
            field=models.IntegerField(default=0),
        ),
    ]
