# Generated by Django 3.2.4 on 2021-07-09 08:39

from django.db import migrations, models
import resourceNew.models.security


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0003_auto_20210709_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthentication',
            name='key_file',
            field=models.FileField(editable=False, max_length=1024, upload_to=resourceNew.models.security.key_file_path),
        ),
        migrations.AlterField(
            model_name='httprequestlog',
            name='body',
            field=models.FileField(max_length=1024, upload_to=resourceNew.models.security.request_body_path),
        ),
        migrations.AlterField(
            model_name='httpresponselog',
            name='content',
            field=models.FileField(max_length=1024, upload_to=resourceNew.models.security.response_content_path),
        ),
    ]
