# Generated by Django 3.2.7 on 2021-09-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0004_mapcontextlayer_dataset_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontextlayer',
            name='feature_type_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.featuretypemetadata'),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='layer_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.layermetadata'),
        ),
    ]
