# Generated by Django 3.2.4 on 2021-07-13 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resourceNew', '0004_auto_20210709_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedresponselog',
            name='entity_unit',
            field=models.CharField(choices=[('MPx', 'MPx'), ('Ft', 'Ft')], help_text='The unit in which the entity count is stored.', max_length=5),
        ),
        migrations.CreateModel(
            name='MapContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('layer_tree', models.TextField()),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_mapcontext_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_mapcontext_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owned_by_org', models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_mapcontext_owned_by_org', to='structure.organization', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
