# Generated by Django 3.2.3 on 2021-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0004_auto_20210623_1651'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proxysetting',
            name='resourcenew_proxysetting_log_response_without_camouflage',
        ),
        migrations.AddConstraint(
            model_name='proxysetting',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('camouflage', True), ('log_response', True)), models.Q(('camouflage', True), ('log_response', False)), models.Q(('camouflage', False), ('log_response', False)), _connector='OR'), name='resourcenew_proxysetting_log_response_without_camouflage'),
        ),
    ]
