# Generated by Django 3.2.4 on 2021-07-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0005_auto_20210713_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(editable=False, help_text='the concrete type and version of the service.', on_delete=django.db.models.deletion.PROTECT, related_name='services', related_query_name='service', to='resourceNew.servicetype', verbose_name='service type'),
        ),
        migrations.DeleteModel(
            name='HarvestResult',
        ),
    ]
