# Generated by Django 3.2.3 on 2021-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0005_auto_20210623_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthentication',
            name='auth_type',
            field=models.CharField(blank=True, choices=[(None, '---'), ('http_basic', 'http_basic'), ('http_digest', 'http_digest')], help_text='kind of authentication mechanism shall used.', max_length=100, verbose_name='authentication type'),
        ),
        migrations.AlterField(
            model_name='externalauthentication',
            name='password',
            field=models.CharField(blank=True, help_text='the password used for the authentication.', max_length=500, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='externalauthentication',
            name='username',
            field=models.CharField(blank=True, help_text='the username used for the authentication.', max_length=255, verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='externalauthentication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('username', None), _negated=True), models.Q(('password', None), _negated=True), models.Q(('auth_type', None), _negated=True), _connector='OR'), name='resourcenew_externalauthentication_empty_fields'),
        ),
    ]
