# Generated by Django 3.2.7 on 2021-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0005_auto_20210921_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcontextlayer',
            name='feature_type_metadata',
        ),
        migrations.RemoveField(
            model_name='mapcontextlayer',
            name='layer_metadata',
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
