# Generated by Django 3.2.3 on 2021-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0006_auto_20210623_1706'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externalauthentication',
            name='resourcenew_externalauthentication_empty_fields',
        ),
        migrations.AddConstraint(
            model_name='externalauthentication',
            constraint=models.CheckConstraint(check=models.Q(('username', None), ('password', None), ('auth_type', None), _connector='OR'), name='resourcenew_externalauthentication_empty_fields'),
        ),
    ]
