# Generated by Django 3.2.7 on 2021-09-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import resourceNew.models.document


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0002_initial'),
        ('resourceNew', '0006_auto_20210922_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextLayerOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayeroperations_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayeroperations_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
            bases=(main.models.GenericModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.layer'),
        ),
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='A preview image for the Map Context Layer', null=True, upload_to=resourceNew.models.document.preview_image_file_path, verbose_name='preview image'),
        ),
        migrations.CreateModel(
            name='ContextLayerSelectOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('context_layer_operations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceNew.contextlayeroperations')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayerselectoptions_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayerselectoptions_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceNew.layer')),
                ('owned_by_org', models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayerselectoptions_owned_by_org', to='structure.organization', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
            bases=(main.models.GenericModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContextLayerRenderOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('minScale', models.IntegerField(blank=True, null=True)),
                ('maxScale', models.IntegerField(blank=True, null=True)),
                ('transparency', models.IntegerField(blank=True, null=True)),
                ('context_layer_operations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceNew.contextlayeroperations')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayerrenderoptions_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayerrenderoptions_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owned_by_org', models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayerrenderoptions_owned_by_org', to='structure.organization', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
            bases=(main.models.GenericModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='contextlayeroperations',
            name='map_context_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceNew.mapcontextlayer'),
        ),
        migrations.AddField(
            model_name='contextlayeroperations',
            name='owned_by_org',
            field=models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayeroperations_owned_by_org', to='structure.organization', verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='ContextLayerMetadataOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at')),
                ('context_layer_operations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceNew.contextlayeroperations')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayermetadataoptions_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('dataset_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceNew.datasetmetadata')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayermetadataoptions_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owned_by_org', models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_contextlayermetadataoptions_owned_by_org', to='structure.organization', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
            bases=(main.models.GenericModelMixin, models.Model),
        ),
    ]
