# Generated by Django 3.2.4 on 2021-07-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resourceNew.models.harvest


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0002_initial'),
        ('job', '0002_initial'),
        ('resourceNew', '0007_mapcontextlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The timestamp of the creation date of this object.', verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The timestamp of the last modification of this object', verbose_name='Last modified at')),
                ('result_file', models.FileField(editable=False, max_length=1024, upload_to=resourceNew.models.harvest.result_file_path)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, help_text='The user who has created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_harvestresult_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_results', related_query_name='harvest_result', to='job.job')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, help_text='The last user who has modified this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_harvestresult_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owned_by_org', models.ForeignKey(blank=True, editable=False, help_text='The organization which is the owner of this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourcenew_harvestresult_owned_by_org', to='structure.organization', verbose_name='Owner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_results', related_query_name='harvest_result', to='resourceNew.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
