# Generated by Django 3.2.3 on 2021-06-23 15:10

import MrMap.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0007_auto_20210623_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalauthentication',
            name='test_url',
            field=models.URLField(editable=False, help_text='this shall be the full get capabilities request url.', null=True, validators=[MrMap.validators.validate_get_capablities_uri], verbose_name='Service url'),
        ),
    ]
