# Generated by Django 3.1.8 on 2021-06-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0008_auto_20210609_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='dataset_contact_metadata', related_query_name='dataset_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='insufficient_quality',
            field=models.TextField(help_text=''),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_metadata', related_query_name='metadata_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='featuretypeelement',
            name='feature_type',
            field=models.ForeignKey(help_text='related feature type of this element', on_delete=django.db.models.deletion.CASCADE, related_name='elements', related_query_name='element', to='resourceNew.featuretype', verbose_name='feature type'),
        ),
        migrations.AlterField(
            model_name='featuretypemetadata',
            name='insufficient_quality',
            field=models.TextField(help_text=''),
        ),
        migrations.AlterField(
            model_name='layermetadata',
            name='insufficient_quality',
            field=models.TextField(help_text=''),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='address_type',
            field=models.CharField(default='', max_length=100, verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='facsimile',
            field=models.CharField(default='', max_length=100, verbose_name='Facsimile'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='person_name',
            field=models.CharField(default='', max_length=200, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='postal_code',
            field=models.CharField(default='', max_length=100, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='metadatacontact',
            name='state_or_province',
            field=models.CharField(default='', max_length=100, verbose_name='State or province'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='insufficient_quality',
            field=models.TextField(help_text=''),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_service_metadata', related_query_name='metadata_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='service_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='service_contact_service_metadata', related_query_name='service_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AddConstraint(
            model_name='metadatacontact',
            constraint=models.UniqueConstraint(fields=('name', 'person_name', 'email', 'phone', 'facsimile', 'city', 'postal_code', 'address_type', 'address', 'state_or_province', 'country'), name='resourcenew_metadatacontact_unique_metadata_contact'),
        ),
    ]
