# Generated by Django 3.2.3 on 2021-06-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0008_alter_externalauthentication_test_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externalauthentication',
            name='resourcenew_externalauthentication_empty_fields',
        ),
    ]
