# Generated by Django 3.2.4 on 2021-07-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0008_harvestresult'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datasetmetadatarelation',
            name='resourcenew_datasetmetadatarelation_one_related_object_selected',
        ),
        migrations.AddField(
            model_name='datasetmetadatarelation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_metadata_relations', related_query_name='dataset_metadata_relation', to='resourceNew.service'),
        ),
        migrations.AddConstraint(
            model_name='datasetmetadatarelation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('service', False)), _negated=True)), name='resourcenew_datasetmetadatarelation_one_related_object_selected'),
        ),
    ]
