# Generated by Django 3.2.4 on 2021-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0009_remove_externalauthentication_resourcenew_externalauthentication_empty_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proxysetting',
            constraint=models.CheckConstraint(check=models.Q(('camouflage', True), ('secured_service__allowed_operation__isnull', True)), name='resourcenew_proxysetting_allowed_operation_without_camouflage'),
        ),
    ]
