# Generated by Django 3.2.4 on 2021-07-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0009_auto_20210714_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmetadata',
            name='self_pointing_services',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all services from which this dataset was harvested.', related_name='dataset_metadata', related_query_name='dataset_metadata', through='resourceNew.DatasetMetadataRelation', to='resourceNew.Service', verbose_name='services'),
        ),
    ]
