# Generated by Django 3.2.4 on 2021-07-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0010_datasetmetadata_self_pointing_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='feature_type',
            field=models.OneToOneField(blank=True, help_text='the feature type object which is described by this capabilities document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.featuretype', verbose_name='related feature type'),
        ),
        migrations.AddField(
            model_name='document',
            name='layer',
            field=models.OneToOneField(blank=True, help_text='the layer object which is described by this capabilities document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.layer', verbose_name='related layer'),
        ),
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.OneToOneField(blank=True, help_text='the service object which is described by this capabilities document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', related_query_name='document', to='resourceNew.service', verbose_name='related service'),
        ),
        migrations.AlterField(
            model_name='document',
            name='xml',
            field=models.FileField(help_text='the currently actual xml (original or edited content).', upload_to='', verbose_name='xml'),
        ),
        migrations.AlterField(
            model_name='document',
            name='xml_backup',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to='', verbose_name='xml backup'),
        ),
    ]
