# Generated by Django 3.1.8 on 2021-05-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceNew', '0016_auto_20210526_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmetadata',
            name='dataset_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='dataset_contact_metadata', related_query_name='dataset_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='datasetmetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_metadata', related_query_name='metadata_contact_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='featuretypemetadata',
            name='described_resource',
            field=models.OneToOneField(help_text='choice the feature type you want to describe with this metadata', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', related_query_name='metadata', to='resourceNew.featuretype', verbose_name='described feature type'),
        ),
        migrations.AlterField(
            model_name='layermetadata',
            name='described_layer',
            field=models.OneToOneField(help_text='choice the layer you want to describe with this metadata', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', related_query_name='metadata', to='resourceNew.layer', verbose_name='described layer'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='described_service',
            field=models.OneToOneField(help_text='choice the service you want to describe with this metadata', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', related_query_name='metadata', to='resourceNew.service', verbose_name='described service'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='metadata_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='metadata_contact_service_metadata', related_query_name='metadata_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='service_contact',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.RESTRICT, related_name='service_contact_service_metadata', related_query_name='service_contact_service_metadata', to='resourceNew.metadatacontact', verbose_name='contact'),
        ),
    ]
