# Generated by Django 3.1.8 on 2021-04-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrmapuser',
            name='organization',
        ),
    ]
