# Generated by Django 3.1.7 on 2021-03-29 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210329_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 11, 38, 24, 494416, tzinfo=utc)),
        ),
    ]
