# Generated by Django 3.1.7 on 2021-03-24 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210324_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='activation_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 10, 24, 50, 783148, tzinfo=utc)),
        ),
    ]
