# Generated by Django 3.1.5 on 2021-02-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivation',
            name='id',
        ),
        migrations.AddField(
            model_name='publishrequest',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AlterField(
            model_name='mrmapgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mrmapuser',
            name='confirmed_dsgvo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='I understand and accept that my data will be automatically processed and securely stored, as it is stated in the general data protection regulation (GDPR).'),
        ),
        migrations.AlterField(
            model_name='mrmapuser',
            name='confirmed_newsletter',
            field=models.BooleanField(default=False, verbose_name='I want to sign up for the newsletter'),
        ),
        migrations.AlterField(
            model_name='mrmapuser',
            name='confirmed_survey',
            field=models.BooleanField(default=False, verbose_name='I want to participate in surveys'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='publishrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_requests', to='structure.mrmapgroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='publishrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_requests', to='structure.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='activation_hash',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='publishrequest',
            unique_together={('group', 'organization')},
        ),
    ]
