# Generated by Django 3.1.6 on 2021-02-18 10:58

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinvitationrequest',
            options={'verbose_name': 'Pending group invitation', 'verbose_name_plural': 'Pending group invitations'},
        ),
        migrations.AlterModelOptions(
            name='mrmapgroup',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(name='Public', then=0)), 'name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='mrmapuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='publishrequest',
            options={'verbose_name': 'Pending publish request', 'verbose_name_plural': 'Pending publish requests'},
        ),
    ]
