# Generated by Django 3.1.5 on 2021-02-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210215_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitationrequest',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='groupinvitationrequest',
            name='to_group',
        ),
        migrations.AddField(
            model_name='groupinvitationrequest',
            name='group',
            field=models.ForeignKey(default=None, help_text='Invite the selected user to this group.', on_delete=django.db.models.deletion.CASCADE, to='structure.mrmapgroup', verbose_name='to group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupinvitationrequest',
            name='user',
            field=models.ForeignKey(default=None, help_text='Invite this user to a selected group.', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to='structure.mrmapuser', verbose_name='Invited user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mrmapgroup',
            name='publish_for_organizations',
            field=models.ManyToManyField(blank=True, related_name='publishers', to='structure.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='facsimile',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Facsimile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_auto_generated',
            field=models.BooleanField(default=True, help_text='Autogenerated organizations are resolved from registered resources.', verbose_name='autogenerated'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Configure a inheritance structure for this Organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure.organization', verbose_name='Parent organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='person_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state_or_province',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State or province'),
        ),
    ]
