# Generated by Django 5.2.8 on 2025-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datasetmetadatarecord',
            name='registry_datasetmetadatarecord_check_spatial_res',
        ),
        migrations.RemoveConstraint(
            model_name='servicemetadatarecord',
            name='registry_servicemetadatarecord_check_spatial_res',
        ),
        migrations.RemoveField(
            model_name='datasetmetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='datasetmetadatarecord',
            name='spatial_res_value',
        ),
        migrations.RemoveField(
            model_name='historicaldatasetmetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='historicaldatasetmetadatarecord',
            name='spatial_res_value',
        ),
        migrations.RemoveField(
            model_name='historicalservicemetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='historicalservicemetadatarecord',
            name='spatial_res_value',
        ),
        migrations.RemoveField(
            model_name='servicemetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='servicemetadatarecord',
            name='spatial_res_value',
        ),
        migrations.AddField(
            model_name='catalogueservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalfeaturetype',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='layer',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='webfeatureservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='the language this metadata content is written.', null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='catalogueservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='catalogueservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='charset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(8, 'utf8')], help_text='The charset which is used by the stored data.', null=True, verbose_name='charset'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='format',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Database'), (2, 'Esri shape'), (3, 'CSV'), (4, 'GML'), (5, 'GeoTIFF')], help_text='The format in which the described dataset is stored.', null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='update_frequency_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'unknown'), (1, 'annually'), (2, 'biannually'), (3, 'as needed'), (4, 'irregular'), (5, 'not planned')], null=True),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='charset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(8, 'utf8')], help_text='The charset which is used by the stored data.', null=True, verbose_name='charset'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='format',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Database'), (2, 'Esri shape'), (3, 'CSV'), (4, 'GML'), (5, 'GeoTIFF')], help_text='The format in which the described dataset is stored.', null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='update_frequency_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'unknown'), (1, 'annually'), (2, 'biannually'), (3, 'as needed'), (4, 'irregular'), (5, 'not planned')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalservicemetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalservicemetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='metadatarelation',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], help_text='determines where this relation was found or it is added by a user.', verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AddConstraint(
            model_name='datasetmetadatarecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equivalent_scale', None), ('ground_res', None)), models.Q(('equivalent_scale__gte', 0), ('ground_res', None)), models.Q(('equivalent_scale', None), ('ground_res__gte', 0)), _connector='OR'), name='registry_datasetmetadatarecord_check_scale_xor_res'),
        ),
        migrations.AddConstraint(
            model_name='servicemetadatarecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equivalent_scale', None), ('ground_res', None)), models.Q(('equivalent_scale__gte', 0), ('ground_res', None)), models.Q(('equivalent_scale', None), ('ground_res__gte', 0)), _connector='OR'), name='registry_servicemetadatarecord_check_scale_xor_res'),
        ),
    ]
