# Generated by Django 5.2.8 on 2025-12-16 13:57

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeExtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerange', django.contrib.postgres.fields.ranges.DateTimeRangeField(default_bounds='[]', help_text='The time range represented by this TimeExtent.', verbose_name='time range')),
                ('resolution', models.DurationField(blank=True, help_text='The resolution of the time extent. Null or 0 means infinite fine resolution.', null=True, verbose_name='resolution')),
            ],
            options={
                'ordering': ['timerange'],
            },
        ),
        migrations.RemoveField(
            model_name='layertimeextent',
            name='layer',
        ),
        migrations.RemoveConstraint(
            model_name='datasetmetadatarecord',
            name='registry_datasetmetadatarecord_check_spatial_res',
        ),
        migrations.RemoveConstraint(
            model_name='servicemetadatarecord',
            name='registry_servicemetadatarecord_check_spatial_res',
        ),
        migrations.RemoveField(
            model_name='datasetmetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='datasetmetadatarecord',
            name='spatial_res_value',
        ),
        migrations.RemoveField(
            model_name='historicaldatasetmetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='historicaldatasetmetadatarecord',
            name='spatial_res_value',
        ),
        migrations.RemoveField(
            model_name='historicalservicemetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='historicalservicemetadatarecord',
            name='spatial_res_value',
        ),
        migrations.RemoveField(
            model_name='servicemetadatarecord',
            name='self_pointing_feature_types',
        ),
        migrations.RemoveField(
            model_name='servicemetadatarecord',
            name='self_pointing_layers',
        ),
        migrations.RemoveField(
            model_name='servicemetadatarecord',
            name='spatial_res_type',
        ),
        migrations.RemoveField(
            model_name='servicemetadatarecord',
            name='spatial_res_value',
        ),
        migrations.AddField(
            model_name='catalogueservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalfeaturetype',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='charset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'ucs2'), (3, 'ucs4'), (4, 'utf7'), (5, 'utf8'), (6, 'utf16'), (7, '8859part1'), (8, '8859part2'), (9, '8859part3'), (10, '8859part4'), (11, '8859part5'), (12, '8859part6'), (13, '8859part7'), (14, '8859part8'), (15, '8859part9'), (16, '8859part10'), (17, '8859part11'), (19, '8859part13'), (20, '8859part14'), (21, '8859part15'), (22, '8859part16'), (23, 'jis'), (24, 'shiftJIS'), (25, 'eucJP'), (26, 'usAscii'), (27, 'ebcdic'), (28, 'eucKR'), (29, 'big5'), (30, 'GB2312')], help_text='full name of the character coding standard used for the metadata set', null=True, verbose_name='charset'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='layer',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='charset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'ucs2'), (3, 'ucs4'), (4, 'utf7'), (5, 'utf8'), (6, 'utf16'), (7, '8859part1'), (8, '8859part2'), (9, '8859part3'), (10, '8859part4'), (11, '8859part5'), (12, '8859part6'), (13, '8859part7'), (14, '8859part8'), (15, '8859part9'), (16, '8859part10'), (17, '8859part11'), (19, '8859part13'), (20, '8859part14'), (21, '8859part15'), (22, '8859part16'), (23, 'jis'), (24, 'shiftJIS'), (25, 'eucJP'), (26, 'usAscii'), (27, 'ebcdic'), (28, 'eucKR'), (29, 'big5'), (30, 'GB2312')], help_text='full name of the character coding standard used for the metadata set', null=True, verbose_name='charset'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='equivalent_scale',
            field=models.FloatField(blank=True, editable=False, help_text='1 cm : 100 cm for example', null=True, verbose_name='equivalent scale'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='ground_res',
            field=models.FloatField(blank=True, editable=False, help_text='pixel per meter for example', null=True, verbose_name='ground resolution'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='webfeatureservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ger'), (2, 'en')], help_text='language used for documenting metadata', null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='catalogueservice',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='catalogueservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='catalogueservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='charset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'ucs2'), (3, 'ucs4'), (4, 'utf7'), (5, 'utf8'), (6, 'utf16'), (7, '8859part1'), (8, '8859part2'), (9, '8859part3'), (10, '8859part4'), (11, '8859part5'), (12, '8859part6'), (13, '8859part7'), (14, '8859part8'), (15, '8859part9'), (16, '8859part10'), (17, '8859part11'), (19, '8859part13'), (20, '8859part14'), (21, '8859part15'), (22, '8859part16'), (23, 'jis'), (24, 'shiftJIS'), (25, 'eucJP'), (26, 'usAscii'), (27, 'ebcdic'), (28, 'eucKR'), (29, 'big5'), (30, 'GB2312')], help_text='full name of the character coding standard used for the metadata set', null=True, verbose_name='charset'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='format',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Database'), (2, 'Esri shape'), (3, 'CSV'), (4, 'GML'), (5, 'GeoTIFF')], help_text='The format in which the described dataset is stored.', null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='update_frequency_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'continual'), (3, 'daily'), (4, 'weekly'), (5, 'fortnightly'), (6, 'monthly'), (7, 'querterly'), (8, 'biannually'), (9, 'annually'), (10, 'as needed'), (11, 'irregular'), (12, 'not planned'), (13, 'unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='getcapabilitiesproberesult',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='getmapproberesult',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='harvestinglog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='charset',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'ucs2'), (3, 'ucs4'), (4, 'utf7'), (5, 'utf8'), (6, 'utf16'), (7, '8859part1'), (8, '8859part2'), (9, '8859part3'), (10, '8859part4'), (11, '8859part5'), (12, '8859part6'), (13, '8859part7'), (14, '8859part8'), (15, '8859part9'), (16, '8859part10'), (17, '8859part11'), (19, '8859part13'), (20, '8859part14'), (21, '8859part15'), (22, '8859part16'), (23, 'jis'), (24, 'shiftJIS'), (25, 'eucJP'), (26, 'usAscii'), (27, 'ebcdic'), (28, 'eucKR'), (29, 'big5'), (30, 'GB2312')], help_text='full name of the character coding standard used for the metadata set', null=True, verbose_name='charset'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='format',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Database'), (2, 'Esri shape'), (3, 'CSV'), (4, 'GML'), (5, 'GeoTIFF')], help_text='The format in which the described dataset is stored.', null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='update_frequency_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'continual'), (3, 'daily'), (4, 'weekly'), (5, 'fortnightly'), (6, 'monthly'), (7, 'querterly'), (8, 'biannually'), (9, 'annually'), (10, 'as needed'), (11, 'irregular'), (12, 'not planned'), (13, 'unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalservicemetadatarecord',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicalservicemetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalservicemetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='metadatarelation',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], help_text='determines where this relation was found or it is added by a user.', verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='date_stamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='date that the metadata was created. If this is a metadata record which is parsed from remote iso metadata, the date stamp of the remote iso metadata will be used.', verbose_name='date stamp'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='hits',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='how many times this metadata was requested by a client', verbose_name='hits'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capabilities'), (2, 'Upload'), (3, 'File System Import'), (4, 'Editor'), (5, 'Catalogue')], editable=False, help_text='Where the metadata record comes from.', null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='webmapservicemonitoringrun',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Datetime field when the run was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='webmapservicemonitoringrun',
            name='date_done',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Datetime field when the run was done in UTC', null=True, verbose_name='Done DateTime'),
        ),
        migrations.AddIndex(
            model_name='timeextent',
            index=django.contrib.postgres.indexes.GistIndex(fields=['timerange'], name='registry_ti_timeran_cee13e_gist'),
        ),
        migrations.AddIndex(
            model_name='timeextent',
            index=models.Index(fields=['resolution'], name='registry_ti_resolut_040c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeextent',
            constraint=models.CheckConstraint(condition=models.Q(('timerange__isempty', True), _negated=True), name='timerange_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='timeextent',
            constraint=models.UniqueConstraint(fields=('timerange', 'resolution'), name='registry_timeextent_unique_timerange_resolution'),
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this metadata record.', related_name='%(app_label)s_%(class)s', related_query_name='%(app_label)s_%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this layer.', related_name='%(class)s', related_query_name='%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this layer.', related_name='%(class)s', related_query_name='%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this metadata record.', related_name='%(app_label)s_%(class)s', related_query_name='%(app_label)s_%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddConstraint(
            model_name='datasetmetadatarecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equivalent_scale', None), ('ground_res', None)), models.Q(('equivalent_scale__gte', 0), ('ground_res', None)), models.Q(('equivalent_scale', None), ('ground_res__gte', 0)), _connector='OR'), name='registry_datasetmetadatarecord_check_scale_xor_res'),
        ),
        migrations.AddConstraint(
            model_name='servicemetadatarecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equivalent_scale', None), ('ground_res', None)), models.Q(('equivalent_scale__gte', 0), ('ground_res', None)), models.Q(('equivalent_scale', None), ('ground_res__gte', 0)), _connector='OR'), name='registry_servicemetadatarecord_check_scale_xor_res'),
        ),
        migrations.DeleteModel(
            name='LayerTimeExtent',
        ),
    ]
