# Generated by Django 3.2.9 on 2022-01-05 12:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='webfeatureservice',
            managers=[
                ('capabilities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='webmapservice',
            managers=[
                ('capabilities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalougeserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation'), name='registry_catalougeserviceoperationurl_unique_together_method_id_operation'),
        ),
        migrations.AddConstraint(
            model_name='webfeatureserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation'), name='registry_webfeatureserviceoperationurl_unique_together_method_id_operation'),
        ),
        migrations.AddConstraint(
            model_name='webmapserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation'), name='registry_webmapserviceoperationurl_unique_together_method_id_operation'),
        ),
    ]
