# Generated by Django 3.2.7 on 2021-12-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedoperation',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='analyzedresponselog',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='legendurl',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mapcontext',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='operationurl',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='remotemetadata',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceaccessgroup',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceauthentication',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='timeextent',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
