# Generated by Django 3.2.9 on 2022-01-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('registry', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalougeservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='historicalcatalougeservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='historicalwebfeatureservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='historicalwebmapservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='webfeatureservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='webmapservice',
            name='get_capabilities_url',
        ),
        migrations.CreateModel(
            name='WMSGetCapabilitiesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('monitored_uri', models.URLField(max_length=4096)),
                ('request_duration', models.DurationField()),
                ('needs_update', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', related_query_name='monitoring_result', to='registry.webmapservice')),
                ('task_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wmsgetcapabilitiesresult_monitoring_results', related_query_name='wmsgetcapabilitiesresult_monitoring_result', to='django_celery_results.taskresult')),
            ],
            options={
                'ordering': ['-task_result__date_done'],
                'get_latest_by': 'task_result__date_done',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerGetMapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('monitored_uri', models.URLField(max_length=4096)),
                ('request_duration', models.DurationField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_map_monitoring_results', related_query_name='get_map_monitoring_result', to='registry.layer')),
                ('task_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layergetmapresult_monitoring_results', related_query_name='layergetmapresult_monitoring_result', to='django_celery_results.taskresult')),
            ],
            options={
                'ordering': ['-task_result__date_done'],
                'get_latest_by': 'task_result__date_done',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerGetFeatureInfoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('monitored_uri', models.URLField(max_length=4096)),
                ('request_duration', models.DurationField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_feature_info_monitoring_results', related_query_name='get_feature_info_monitoring_result', to='registry.layer')),
                ('task_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layergetfeatureinforesult_monitoring_results', related_query_name='layergetfeatureinforesult_monitoring_result', to='django_celery_results.taskresult')),
            ],
            options={
                'ordering': ['-task_result__date_done'],
                'get_latest_by': 'task_result__date_done',
                'abstract': False,
            },
        ),
    ]
