# Generated by Django 5.2.8 on 2025-12-15 16:37

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_datasetmetadatarecord_registry_datasetmetadatarecord_check_spatial_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getcapabilitiesproberesult',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='getmapproberesult',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='harvestinglog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text='Datetime field when the process was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='webmapservicemonitoringrun',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Datetime field when the run was created in UTC', null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='webmapservicemonitoringrun',
            name='date_done',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Datetime field when the run was done in UTC', null=True, verbose_name='Done DateTime'),
        ),
        migrations.CreateModel(
            name='TimeExtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerange', django.contrib.postgres.fields.ranges.DateTimeRangeField(default_bounds='[]', help_text='The time range represented by this TimeExtent.', verbose_name='time range')),
                ('resolution', models.DurationField(blank=True, help_text='The resolution of the time extent. Null or 0 means infinite fine resolution.', null=True, verbose_name='resolution')),
            ],
            options={
                'ordering': ['timerange'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['timerange'], name='registry_ti_timeran_cee13e_gist'), models.Index(fields=['resolution'], name='registry_ti_resolut_040c18_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('timerange__isempty', True), _negated=True), name='timerange_not_empty'), models.UniqueConstraint(fields=('timerange', 'resolution'), name='registry_timeextent_unique_timerange_resolution')],
            },
        ),
        migrations.AddField(
            model_name='datasetmetadatarecord',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this metadata record.', related_name='%(app_label)s_%(class)s', related_query_name='%(app_label)s_%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this layer.', related_name='%(class)s', related_query_name='%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this layer.', related_name='%(class)s', related_query_name='%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.AddField(
            model_name='servicemetadatarecord',
            name='time_extents',
            field=models.ManyToManyField(blank=True, editable=False, help_text='all time extents which are available for this metadata record.', related_name='%(app_label)s_%(class)s', related_query_name='%(app_label)s_%(class)s', to='registry.timeextent', verbose_name='time extent'),
        ),
        migrations.DeleteModel(
            name='LayerTimeExtent',
        ),
    ]
