# Generated by Django 3.2.9 on 2022-01-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedwebfeatureserviceoperation',
            options={'ordering': ['-secured_service']},
        ),
        migrations.AlterModelOptions(
            name='allowedwebmapserviceoperation',
            options={'ordering': ['-secured_service']},
        ),
    ]
