# Generated by Django 3.2.7 on 2021-10-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='dataset_metadata',
            field=models.ForeignKey(blank=True, help_text='You can use this field to pre filter possible Layer selection.', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.datasetmetadata', verbose_name='Dataset Metadata'),
        ),
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='layer',
            field=models.ForeignKey(blank=True, help_text='Select a layer as a offering for rendering.', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.layer', verbose_name='Layer'),
        ),
    ]
