# Generated by Django 3.2.7 on 2021-11-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='map_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_context_layers', related_query_name='map_context_layer', to='registry.mapcontext'),
        ),
        migrations.DeleteModel(
            name='RegisterOgcServiceJob',
        ),
    ]
