# Generated by Django 3.2.7 on 2021-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datasetmetadatarelation',
            name='registry_datasetmetadatarelation_one_related_object_selected',
        ),
        migrations.AddConstraint(
            model_name='datasetmetadatarelation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('csw', False)), _negated=True)), name='registry_datasetmetadatarelation_one_related_object_selected'),
        ),
    ]
