# Generated by Django 3.2.9 on 2022-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalougeserviceoperationurl',
            name='registry_catalougeserviceoperationurl_unique_together_method_id_operation',
        ),
        migrations.RemoveConstraint(
            model_name='webfeatureserviceoperationurl',
            name='registry_webfeatureserviceoperationurl_unique_together_method_id_operation',
        ),
        migrations.RemoveConstraint(
            model_name='webmapserviceoperationurl',
            name='registry_webmapserviceoperationurl_unique_together_method_id_operation',
        ),
        migrations.AlterField(
            model_name='webfeatureserviceoperation',
            name='operation',
            field=models.CharField(choices=[(None, '---'), ('GetFeature', 'GetFeature')], max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webmapserviceoperation',
            name='operation',
            field=models.CharField(choices=[(None, '---'), ('GetMap', 'GetMap'), ('GetFeatureInfo', 'GetFeatureInfo')], max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='catalougeserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation', 'service'), name='registry_catalougeserviceoperationurl_unique_together_method_id_operation'),
        ),
        migrations.AddConstraint(
            model_name='webfeatureserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation', 'service'), name='registry_webfeatureserviceoperationurl_unique_together_method_id_operation'),
        ),
        migrations.AddConstraint(
            model_name='webmapserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation', 'service'), name='registry_webmapserviceoperationurl_unique_together_method_id_operation'),
        ),
    ]
