# Generated by Django 5.2.12 on 2026-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='harvestedmetadatarelation',
            name='dm_record_or_sm_record',
        ),
        migrations.AddConstraint(
            model_name='harvestedmetadatarelation',
            constraint=models.CheckConstraint(condition=models.Q(('dataset_metadata_record__isnull', True), ('service_metadata_record__isnull', True), _connector='XOR'), name='dm_record_or_sm_record', violation_error_message='wrong relation type. dataset_metadata_record or service_metadata_record, not both is required.'),
        ),
    ]
