# Generated by Django 3.2.9 on 2022-01-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('registry', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedwebfeatureserviceoperation',
            options={'ordering': ['-secured_service']},
        ),
        migrations.AlterModelOptions(
            name='allowedwebmapserviceoperation',
            options={'ordering': ['-secured_service']},
        ),
        migrations.RemoveField(
            model_name='catalougeservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='historicalcatalougeservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='historicalwebfeatureservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='historicalwebmapservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='webfeatureservice',
            name='get_capabilities_url',
        ),
        migrations.RemoveField(
            model_name='webmapservice',
            name='get_capabilities_url',
        ),
        migrations.CreateModel(
            name='WMSGetCapabilitiesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=0, editable=False, help_text='The http status code of the response', verbose_name='HTTP status code')),
                ('error_msg', models.TextField(blank=True, editable=False, help_text='The error message of the http response or other error description', null=True, verbose_name='error message')),
                ('monitored_uri', models.URLField(editable=False, help_text='This is the url which was monitored', max_length=4096, verbose_name='monitored uri')),
                ('request_duration', models.DurationField(blank=True, editable=False, help_text='elapsed time of the request', null=True, verbose_name='request duration')),
                ('needs_update', models.BooleanField(default=False, editable=False, help_text='signals if the ogc capabilities document has any changes', verbose_name='needs update')),
                ('service', models.ForeignKey(help_text='this is the service which shall be monitored', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', related_query_name='monitoring_result', to='registry.webmapservice', verbose_name='web map service')),
                ('task_result', models.OneToOneField(editable=False, help_text='The result of the celery task', on_delete=django.db.models.deletion.CASCADE, related_name='wmsgetcapabilitiesresult_monitoring_results', related_query_name='wmsgetcapabilitiesresult_monitoring_result', to='django_celery_results.taskresult', verbose_name='Task Result')),
            ],
            options={
                'ordering': ['-task_result__date_done'],
                'get_latest_by': 'task_result__date_done',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerGetMapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=0, editable=False, help_text='The http status code of the response', verbose_name='HTTP status code')),
                ('error_msg', models.TextField(blank=True, editable=False, help_text='The error message of the http response or other error description', null=True, verbose_name='error message')),
                ('monitored_uri', models.URLField(editable=False, help_text='This is the url which was monitored', max_length=4096, verbose_name='monitored uri')),
                ('request_duration', models.DurationField(blank=True, editable=False, help_text='elapsed time of the request', null=True, verbose_name='request duration')),
                ('layer', models.ForeignKey(help_text='this is the layer which shall be monitored', on_delete=django.db.models.deletion.CASCADE, related_name='get_map_monitoring_results', related_query_name='get_map_monitoring_result', to='registry.layer', verbose_name='layer')),
                ('task_result', models.OneToOneField(editable=False, help_text='The result of the celery task', on_delete=django.db.models.deletion.CASCADE, related_name='layergetmapresult_monitoring_results', related_query_name='layergetmapresult_monitoring_result', to='django_celery_results.taskresult', verbose_name='Task Result')),
            ],
            options={
                'ordering': ['-task_result__date_done'],
                'get_latest_by': 'task_result__date_done',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerGetFeatureInfoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=0, editable=False, help_text='The http status code of the response', verbose_name='HTTP status code')),
                ('error_msg', models.TextField(blank=True, editable=False, help_text='The error message of the http response or other error description', null=True, verbose_name='error message')),
                ('monitored_uri', models.URLField(editable=False, help_text='This is the url which was monitored', max_length=4096, verbose_name='monitored uri')),
                ('request_duration', models.DurationField(blank=True, editable=False, help_text='elapsed time of the request', null=True, verbose_name='request duration')),
                ('layer', models.ForeignKey(help_text='this is the layer which shall be monitored', on_delete=django.db.models.deletion.CASCADE, related_name='get_feature_info_monitoring_results', related_query_name='get_feature_info_monitoring_result', to='registry.layer', verbose_name='layer')),
                ('task_result', models.OneToOneField(editable=False, help_text='The result of the celery task', on_delete=django.db.models.deletion.CASCADE, related_name='layergetfeatureinforesult_monitoring_results', related_query_name='layergetfeatureinforesult_monitoring_result', to='django_celery_results.taskresult', verbose_name='Task Result')),
            ],
            options={
                'ordering': ['-task_result__date_done'],
                'get_latest_by': 'task_result__date_done',
                'abstract': False,
            },
        ),
    ]
