# Generated by Django 3.2.9 on 2022-01-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('registry', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(null=True)),
                ('monitored_uri', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='WebMapServiceMonitoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_update', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.webmapservice')),
                ('task_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebFeatureServiceMonitoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_update', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.webfeatureservice')),
                ('task_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetMetadataMonitoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.datasetmetadata')),
                ('task_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'verbose_name': 'Monitoring result',
                'verbose_name_plural': 'Monitoring results',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebMapServiceMonitoringResult',
            fields=[
                ('monitoringresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.monitoringresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.webmapservicemonitoringrun')),
            ],
            bases=('registry.monitoringresult',),
        ),
    ]
