# Generated by Django 3.2.9 on 2022-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontextlayer',
            name='description',
            field=models.CharField(blank=True, help_text='a short description for this map context layer', max_length=1000, null=True, verbose_name='description'),
        ),
    ]
