# Generated by Django 3.2.9 on 2022-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20220105_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontextlayer',
            name='is_leaf',
            field=models.BooleanField(default=False, help_text='Set if this map context layer is a layer withattributes (leaf) or it defines a group of layers like a folder (not leaf).', verbose_name='Is tree leaf'),
        ),
    ]
