# Generated by Django 3.2.9 on 2022-01-07 12:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registry', '0003_auto_20220106_1346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webfeatureserviceoperationurl',
            name='registry_webfeatureserviceoperationurl_unique_together_method_id_operation',
        ),
        migrations.RemoveConstraint(
            model_name='webmapserviceoperationurl',
            name='registry_webmapserviceoperationurl_unique_together_method_id_operation',
        ),
        migrations.AlterField(
            model_name='allowedwebfeatureserviceoperation',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowedwebfeatureserviceoperation_allowed_operations', related_query_name='allowedwebfeatureserviceoperation_allowed_operation', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='allowedwebmapserviceoperation',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowedwebmapserviceoperation_allowed_operations', related_query_name='allowedwebmapserviceoperation_allowed_operation', to='auth.Group'),
        ),
        migrations.AddConstraint(
            model_name='allowedwebfeatureserviceoperation',
            constraint=models.CheckConstraint(check=django.db.models.expressions.Func(django.db.models.expressions.F('allowed_area'), function='NOT st_isempty', output_field=models.BooleanField()), name='registry_allowedwebfeatureserviceoperation_allowed_area_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='webfeatureserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation', 'service'), name='registry_webfeatureserviceoperationurl_unique_together_method_id_operation_service'),
        ),
        migrations.AddConstraint(
            model_name='webmapserviceoperationurl',
            constraint=models.UniqueConstraint(fields=('method', 'operation', 'service'), name='registry_webmapserviceoperationurl_unique_together_method_id_operation_service'),
        ),
    ]
