# Generated by Django 3.2.9 on 2022-01-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20220125_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.IntegerField(blank=True, help_text='total count of records which will be harvested by this job', null=True, verbose_name='total records')),
                ('step_size', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, help_text='timestamp of start', null=True, verbose_name='date started')),
                ('done_at', models.DateTimeField(blank=True, help_text='timestamp of done', null=True, verbose_name='date done')),
                ('existing_records', models.ManyToManyField(related_name='ignored_by', to='registry.DatasetMetadata')),
                ('new_records', models.ManyToManyField(related_name='harvested_by', to='registry.DatasetMetadata')),
                ('service', models.ForeignKey(help_text='the csw for that this job is running', on_delete=django.db.models.deletion.CASCADE, to='registry.catalougeservice', verbose_name='service')),
                ('updated_records', models.ManyToManyField(related_name='updated_by', to='registry.DatasetMetadata')),
            ],
        ),
    ]
