# Generated by Django 3.2.7 on 2021-11-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20211124_1042'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='datasetmetadata',
            managers=[
            ],
        ),
    ]
