# Generated by Django 3.2.9 on 2022-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20220125_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergetfeatureinforesult',
            name='request_duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='layergetfeatureinforesult',
            name='status_code',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='layergetmapresult',
            name='request_duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='layergetmapresult',
            name='status_code',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wmsgetcapabilitiesresult',
            name='request_duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='wmsgetcapabilitiesresult',
            name='status_code',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
