# Generated by Django 5.2.12 on 2026-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_harvestedmetadatarelation_dm_record_or_sm_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='update_frequency_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'continual'), (3, 'daily'), (4, 'weekly'), (5, 'fortnightly'), (6, 'monthly'), (7, 'quarterly'), (8, 'biannually'), (9, 'annually'), (10, 'as needed'), (11, 'irregular'), (12, 'not planned'), (13, 'unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='update_frequency_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'continual'), (3, 'daily'), (4, 'weekly'), (5, 'fortnightly'), (6, 'monthly'), (7, 'quarterly'), (8, 'biannually'), (9, 'annually'), (10, 'as needed'), (11, 'irregular'), (12, 'not planned'), (13, 'unknown')], null=True),
        ),
    ]
