# Generated by Django 5.1.2 on 2024-12-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_backgroundprocess_done_steps_and_more'),
        ('registry', '0004_remove_layergetmapresult_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingjob',
            name='background_process',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.backgroundprocess'),
        ),
    ]
