# Generated by Django 3.2.9 on 2022-02-01 13:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0004_auto_20220128_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontext',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='language',
            field=models.CharField(choices=[('de', 'de'), ('en', 'en')], default='en', help_text='language of context document', max_length=4, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='mm_per_pixel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='pixel_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='pixel_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pixel width'),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='rendering_active',
            field=models.BooleanField(blank=True, default=True, help_text='should this offering be visible?', verbose_name='rendering active'),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='selection_active',
            field=models.BooleanField(blank=True, default=True, help_text='should this offering be visible?', verbose_name='rendering active'),
        ),
        migrations.AlterField(
            model_name='mapcontext',
            name='abstract',
            field=models.TextField(blank=True, help_text='brief summary of the topic of this map context', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_layers', related_query_name='child_layer', to='registry.mapcontextlayer'),
        ),
        migrations.CreateModel(
            name='HistoricalMapContextLayer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('layer_scale_min', models.FloatField(blank=True, help_text='minimum scale for a possible request to this layer. If the request is out of the given scope, the service will response with empty transparentimages. None value means no restriction.', null=True, verbose_name='scale minimum value')),
                ('layer_scale_max', models.FloatField(blank=True, help_text='maximum scale for a possible request to this layer. If the request is out of the given scope, the service will response with empty transparentimages. None value means no restriction.', null=True, verbose_name='scale maximum value')),
                ('preview_image', models.TextField(blank=True, help_text='A preview image for the Map Context Layer', max_length=100, null=True, verbose_name='preview image')),
                ('rendering_active', models.BooleanField(blank=True, default=True, help_text='should this offering be visible?', verbose_name='rendering active')),
                ('selection_active', models.BooleanField(blank=True, default=True, help_text='should this offering be visible?', verbose_name='rendering active')),
                ('title', models.CharField(help_text='an identifying name for this map context layer', max_length=1000, verbose_name='title')),
                ('description', models.CharField(blank=True, help_text='a short description for this map context layer', max_length=1000, null=True, verbose_name='description')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dataset_metadata', models.ForeignKey(blank=True, db_constraint=False, help_text='You can use this field to pre filter possible Layer selection.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.datasetmetadata', verbose_name='Dataset Metadata')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_logs', to='registry.mapcontextlayer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('layer_style', models.ForeignKey(blank=True, db_constraint=False, help_text='Select a style for rendering.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.style', verbose_name='Style')),
                ('map_context', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='map_context_layer', to='registry.mapcontext')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='child_layer', to='registry.mapcontextlayer')),
                ('rendering_layer', models.ForeignKey(blank=True, db_constraint=False, help_text='Select a layer for rendering.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.layer', verbose_name='Rendering layer')),
                ('selection_layer', models.ForeignKey(blank=True, db_constraint=False, help_text='Select a layer for feature selection.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.layer', verbose_name='Selection layer')),
            ],
            options={
                'verbose_name': 'historical map context layer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMapContext',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='a short descriptive title for this map context', max_length=1000, verbose_name='title')),
                ('language', models.CharField(choices=[('de', 'de'), ('en', 'en')], default='en', help_text='language of context document', max_length=4, verbose_name='language')),
                ('abstract', models.TextField(blank=True, help_text='brief summary of the topic of this map context', null=True, verbose_name='abstract')),
                ('pixel_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='pixel width')),
                ('pixel_height', models.PositiveIntegerField(blank=True, null=True)),
                ('mm_per_pixel', models.FloatField(blank=True, null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_logs', to='registry.mapcontext')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical map context',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
