# Generated by Django 3.2.9 on 2022-01-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_mapcontextlayer_is_leaf'),
    ]

    operations = [
    ]
