# Generated by Django 3.2.9 on 2022-01-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_harvestingjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestingjob',
            options={'ordering': ['-done_at']},
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='done_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='timestamp of done', null=True, verbose_name='date done'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='existing_records',
            field=models.ManyToManyField(editable=False, related_name='ignored_by', to='registry.DatasetMetadata'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='new_records',
            field=models.ManyToManyField(editable=False, related_name='harvested_by', to='registry.DatasetMetadata'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='timestamp of start', null=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='step_size',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='total_records',
            field=models.IntegerField(blank=True, editable=False, help_text='total count of records which will be harvested by this job', null=True, verbose_name='total records'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='updated_records',
            field=models.ManyToManyField(editable=False, related_name='updated_by', to='registry.DatasetMetadata'),
        ),
        migrations.AddConstraint(
            model_name='harvestingjob',
            constraint=models.UniqueConstraint(fields=('service', 'done_at'), name='registry_harvestingjob_service_done_at_uniq'),
        ),
        migrations.AddConstraint(
            model_name='harvestingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='registry_harvestingjob_service_uniq'),
        ),
    ]
