# Generated by Django 5.2.12 on 2026-04-08 12:20

import django.db.models.deletion
import django.utils.timezone
import registry.models.update
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_datasetmetadatarecord_update_frequency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Layer Mapping',
                'verbose_name_plural': 'Layer Mappings',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='WebMapServiceUpdateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=registry.models.update.default_update_config)),
            ],
            options={
                'verbose_name': 'Web Map Service Update Config',
                'verbose_name_plural': 'Web Map Service Update Configs',
            },
        ),
        migrations.CreateModel(
            name='WebMapServiceUpdateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('done_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'No update needed'), (1, 'Updating'), (2, 'Review required'), (3, 'Error'), (4, 'Waiting for processing'), (5, 'Updated')], default=4)),
            ],
            options={
                'verbose_name': 'Web Map Service Update Job',
                'verbose_name_plural': 'Web Map Service Update Jobs',
                'ordering': ['-date_created'],
                'get_latest_by': '-date_created',
            },
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['mptt_tree_id', 'mptt_lft'], 'verbose_name': 'layer', 'verbose_name_plural': 'layers'},
        ),
        migrations.AddField(
            model_name='catalogueservice',
            name='update_candidate_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update_candidate', related_query_name='%(class)s_update_candidate', to='registry.catalogueservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='update_candidate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)s_update_candidate', to='registry.catalogueservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='update_candidate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)s_update_candidate', to='registry.webfeatureservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='update_candidate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)s_update_candidate', to='registry.webmapservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='webfeatureservice',
            name='update_candidate_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update_candidate', related_query_name='%(class)s_update_candidate', to='registry.webfeatureservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='update_candidate_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update_candidate', related_query_name='%(class)s_update_candidate', to='registry.webmapservice', verbose_name='update candidate'),
        ),
        migrations.AddIndex(
            model_name='catalogueservice',
            index=models.Index(fields=['update_candidate_of'], name='registry_ca_update__7b419c_idx'),
        ),
        migrations.AddIndex(
            model_name='webfeatureservice',
            index=models.Index(fields=['update_candidate_of'], name='registry_we_update__8ab6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='webmapservice',
            index=models.Index(fields=['update_candidate_of'], name='registry_we_update__22cc8f_idx'),
        ),
        migrations.AddField(
            model_name='layermapping',
            name='new_layer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', related_query_name='mapping', to='registry.layer'),
        ),
        migrations.AddField(
            model_name='layermapping',
            name='old_layer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_mapping', related_query_name='reverse_mapping', to='registry.layer'),
        ),
        migrations.AddField(
            model_name='webmapserviceupdateconfig',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_config', to='registry.webmapservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='webmapserviceupdatejob',
            name='service',
            field=models.ForeignKey(help_text='the wms for that this job is running', on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', related_query_name='update_job', to='registry.webmapservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='layermapping',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', related_query_name='mapping', to='registry.webmapserviceupdatejob'),
        ),
        migrations.AddIndex(
            model_name='webmapserviceupdatejob',
            index=models.Index(fields=['date_created'], name='registry_we_date_cr_e31b68_idx'),
        ),
        migrations.AddIndex(
            model_name='webmapserviceupdatejob',
            index=models.Index(fields=['done_at'], name='registry_we_done_at_fe653d_idx'),
        ),
        migrations.AddConstraint(
            model_name='webmapserviceupdatejob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='only_one_unfinished_update_per_service', violation_error_message='There is an existing noncompleted job for this service.'),
        ),
        migrations.AddIndex(
            model_name='layermapping',
            index=models.Index(fields=['created'], name='registry_la_created_fb523f_idx'),
        ),
        migrations.AddConstraint(
            model_name='layermapping',
            constraint=models.UniqueConstraint(fields=('job', 'new_layer'), name='unique_new_layer_per_job_in_mapping', violation_error_message='A new layer can only be mapped once. Please adjust the layer mappings accordingly.'),
        ),
        migrations.AddConstraint(
            model_name='layermapping',
            constraint=models.CheckConstraint(condition=models.Q(('new_layer__isnull', True), ('old_layer__isnull', True), _negated=True), name='prevent_both_layers_null'),
        ),
    ]
