# Generated by Django 3.2.9 on 2022-01-31 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20220128_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontext',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='mm_per_pixel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='pixel_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapcontext',
            name='pixel_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pixel width'),
        ),
        migrations.AddField(
            model_name='mapcontextlayer',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='should this offering be visible?', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='mapcontext',
            name='abstract',
            field=models.TextField(blank=True, help_text='brief summary of the topic of this map context', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_layers', related_query_name='child_layer', to='registry.mapcontextlayer'),
        ),
    ]
