# Generated by Django 3.2.9 on 2022-01-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20220118_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcontextlayer',
            name='name',
        ),
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='title',
            field=models.CharField(help_text='an identifying name for this map context layer', max_length=1000, verbose_name='name'),
        ),
    ]
