# Generated by Django 5.2.12 on 2026-03-23 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_datasetmetadatarecord_update_frequency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebMapServiceUpdateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('done_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'OK'), (1, 'Updating'), (2, 'Review required'), (3, 'Error'), (4, 'Waiting for processing')], default=4)),
                ('keep_customized_metadata', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Web Map Service Update Job',
                'verbose_name_plural': 'Web Map Service Update Jobs',
                'ordering': ['-date_created'],
                'get_latest_by': '-date_created',
            },
        ),
        migrations.AddField(
            model_name='catalogueservice',
            name='update_candidate_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update_candidate', related_query_name='%(class)s_update_candidate', to='registry.catalogueservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='update_candidate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)s_update_candidate', to='registry.catalogueservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='update_candidate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)s_update_candidate', to='registry.webfeatureservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='update_candidate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(class)s_update_candidate', to='registry.webmapservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='webfeatureservice',
            name='update_candidate_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update_candidate', related_query_name='%(class)s_update_candidate', to='registry.webfeatureservice', verbose_name='update candidate'),
        ),
        migrations.AddField(
            model_name='webmapservice',
            name='update_candidate_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='this is the update candidate of this service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update_candidate', related_query_name='%(class)s_update_candidate', to='registry.webmapservice', verbose_name='update candidate'),
        ),
        migrations.AddIndex(
            model_name='catalogueservice',
            index=models.Index(fields=['update_candidate_of'], name='registry_ca_update__7b419c_idx'),
        ),
        migrations.AddIndex(
            model_name='webfeatureservice',
            index=models.Index(fields=['update_candidate_of'], name='registry_we_update__8ab6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='webmapservice',
            index=models.Index(fields=['update_candidate_of'], name='registry_we_update__22cc8f_idx'),
        ),
        migrations.AddField(
            model_name='layermapping',
            name='new_layer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', related_query_name='mapping', to='registry.layer'),
        ),
        migrations.AddField(
            model_name='layermapping',
            name='old_layer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_mapping', related_query_name='reverse_mapping', to='registry.layer'),
        ),
        migrations.AddField(
            model_name='webmapserviceupdatejob',
            name='service',
            field=models.ForeignKey(help_text='the wms for that this job is running', on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', related_query_name='update_job', to='registry.webmapservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='layermapping',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', related_query_name='mapping', to='registry.webmapserviceupdatejob'),
        ),
        migrations.AddIndex(
            model_name='webmapserviceupdatejob',
            index=models.Index(fields=['date_created'], name='registry_we_date_cr_e31b68_idx'),
        ),
        migrations.AddIndex(
            model_name='webmapserviceupdatejob',
            index=models.Index(fields=['done_at'], name='registry_we_done_at_fe653d_idx'),
        ),
        migrations.AddConstraint(
            model_name='webmapserviceupdatejob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='only_one_unfinished_update_per_service', violation_error_message='There is an existing noncompleted job for this service.'),
        ),
    ]
