# Generated by Django 5.1.2 on 2024-12-04 09:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_alter_backgroundprocess_done_steps_and_more'),
        ('registry', '0005_harvestingjob_background_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHarvestingJob',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('harvest_datasets', models.BooleanField(default=True)),
                ('harvest_services', models.BooleanField(default=True)),
                ('total_records', models.IntegerField(blank=True, editable=False, help_text='total count of records which will be harvested by this job', null=True, verbose_name='total records')),
                ('step_size', models.IntegerField(blank=True, default=50)),
                ('started_at', models.DateTimeField(blank=True, editable=False, help_text='timestamp of start', null=True, verbose_name='date started')),
                ('done_at', models.DateTimeField(blank=True, editable=False, help_text='timestamp of done', null=True, verbose_name='date done')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('background_process', models.ForeignKey(blank=True, db_constraint=False, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notify.backgroundprocess')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_logs', to='registry.harvestingjob')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, help_text='the csw for that this job is running', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.catalogueservice', verbose_name='service')),
            ],
            options={
                'verbose_name': 'historical harvesting job',
                'verbose_name_plural': 'historical harvesting jobs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
