# Generated by Django 5.2.12 on 2026-05-11 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_layermapping_webmapserviceupdateconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeatureservicehttprequestlog',
            name='is_test_request',
            field=models.BooleanField(default=False, help_text='indicates if this request was processed in test-as-user mode', verbose_name='is test request'),
        ),
        migrations.AddField(
            model_name='webfeatureservicehttprequestlog',
            name='test_user',
            field=models.ForeignKey(blank=True, help_text='the user context used for testing; null if not a test request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_test_http_request_logs', related_query_name='%(class)stest_http_request_log', to=settings.AUTH_USER_MODEL, verbose_name='test user'),
        ),
        migrations.AddField(
            model_name='webmapservicehttprequestlog',
            name='is_test_request',
            field=models.BooleanField(default=False, help_text='indicates if this request was processed in test-as-user mode', verbose_name='is test request'),
        ),
        migrations.AddField(
            model_name='webmapservicehttprequestlog',
            name='test_user',
            field=models.ForeignKey(blank=True, help_text='the user context used for testing; null if not a test request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_test_http_request_logs', related_query_name='%(class)stest_http_request_log', to=settings.AUTH_USER_MODEL, verbose_name='test user'),
        ),
        migrations.AlterField(
            model_name='webmapserviceupdatejob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No update needed'), (1, 'Updating'), (2, 'Review required'), (3, 'Error'), (4, 'Waiting for processing'), (5, 'Updated'), (6, 'Resume')], default=4),
        ),
    ]
