# Generated by Django 3.2.9 on 2022-01-12 17:48

from django.apps import apps
from django.db import migrations, models
from django.db.models import F


def exchange_fields_values(app, schema):
    MyModel = apps.get_model('registry', 'MapContextLayer')

    # Titles are currently a small optional description. They will be covering the task of "name" and the title is a description.
    # So first, titles that are NULL, should be filled to avoid not-null constraint error when exchanging values.
    # They will be filled with the exact same value as names
    MyModel.objects.filter(title=None).update(title=F('name'))

    # now exchange the values between the columns
    MyModel.objects.all().update(title=F('name'), name=F('title'))

    # copy values from name to description
    MyModel.objects.all().update(description=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20220112_1847'),
    ]

    operations = [migrations.RunPython(exchange_fields_values)]
