# Generated by Django 3.2.9 on 2022-02-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20220201_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingjob',
            name='record_type',
            field=models.CharField(choices=[('dataset', 'dataset'), ('service', 'service'), ('tile', 'tile'), ('series', 'series')], default='dataset', help_text='the type of the record, which shall be harvested.', max_length=10, verbose_name='record type'),
        ),
        migrations.CreateModel(
            name='CswOperationUrlQueryable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('operation_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queryables', related_query_name='queryable', to='registry.catalougeserviceoperationurl')),
            ],
        ),
    ]
