# Generated by Django 5.2.12 on 2026-07-15 07:08

import django.db.models.deletion
import registry.models.update
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_webfeatureservicehttprequestlog_is_test_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueServiceUpdateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=registry.models.update.default_csw_update_config)),
            ],
            options={
                'verbose_name': 'Web Catalogue Service Update Config',
                'verbose_name_plural': 'Web Catalogue Service Update Configs',
            },
        ),
        migrations.CreateModel(
            name='CatalogueServiceUpdateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(editable=False, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'No update needed'), (1, 'Updating'), (2, 'Review required'), (3, 'Error'), (4, 'Waiting for processing'), (5, 'Updated'), (6, 'Resume')], default=4)),
            ],
            options={
                'verbose_name': 'Web Catalogue Service Update Job',
                'verbose_name_plural': 'Web Catalogue Service Update Jobs',
                'ordering': ['-date_created'],
                'get_latest_by': '-date_created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feature Type Mapping',
                'verbose_name_plural': 'Feature Type Mappings',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebFeatureServiceUpdateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=registry.models.update.default_wfs_update_config)),
            ],
            options={
                'verbose_name': 'Web Feature Service Update Config',
                'verbose_name_plural': 'Web Feature Service Update Configs',
            },
        ),
        migrations.CreateModel(
            name='WebFeatureServiceUpdateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(editable=False, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'No update needed'), (1, 'Updating'), (2, 'Review required'), (3, 'Error'), (4, 'Waiting for processing'), (5, 'Updated'), (6, 'Resume')], default=4)),
            ],
            options={
                'verbose_name': 'Web Feature Service Update Job',
                'verbose_name_plural': 'Web Feature Service Update Jobs',
                'ordering': ['-date_created'],
                'get_latest_by': '-date_created',
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='webmapserviceupdatejob',
            name='only_one_unfinished_update_per_service',
        ),
        migrations.AlterField(
            model_name='layermapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webmapserviceupdatejob',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webmapserviceupdatejob',
            name='done_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='webmapserviceupdatejob',
            name='service',
            field=models.ForeignKey(help_text='the wms this job is running for', on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', related_query_name='update_job', to='registry.webmapservice', verbose_name='service'),
        ),
        migrations.AddConstraint(
            model_name='webmapserviceupdatejob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='registry_webmapserviceupdatejob_only_one_unfinished_update_per_service', violation_error_message='There is an existing noncompleted job for this service.'),
        ),
        migrations.AddField(
            model_name='catalogueserviceupdateconfig',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_config', to='registry.catalogueservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='catalogueserviceupdatejob',
            name='service',
            field=models.ForeignKey(help_text='the CSW this job is running for', on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', related_query_name='update_job', to='registry.catalogueservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='featuretypemapping',
            name='new_featuretype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', related_query_name='mapping', to='registry.featuretype'),
        ),
        migrations.AddField(
            model_name='featuretypemapping',
            name='old_featuretype',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_mapping', related_query_name='reverse_mapping', to='registry.featuretype'),
        ),
        migrations.AddField(
            model_name='webfeatureserviceupdateconfig',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_config', to='registry.webfeatureservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='webfeatureserviceupdatejob',
            name='service',
            field=models.ForeignKey(help_text='the WFS this job is running for', on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', related_query_name='update_job', to='registry.webfeatureservice', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='featuretypemapping',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', related_query_name='mapping', to='registry.webfeatureserviceupdatejob'),
        ),
        migrations.AddIndex(
            model_name='catalogueserviceupdatejob',
            index=models.Index(fields=['date_created'], name='registry_ca_date_cr_970f00_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogueserviceupdatejob',
            index=models.Index(fields=['done_at'], name='registry_ca_done_at_9f7f25_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogueserviceupdatejob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='registry_catalogueserviceupdatejob_only_one_unfinished_update_per_service', violation_error_message='There is an existing noncompleted job for this service.'),
        ),
        migrations.AddIndex(
            model_name='webfeatureserviceupdatejob',
            index=models.Index(fields=['date_created'], name='registry_we_date_cr_480ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='webfeatureserviceupdatejob',
            index=models.Index(fields=['done_at'], name='registry_we_done_at_500bd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='webfeatureserviceupdatejob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='registry_webfeatureserviceupdatejob_only_one_unfinished_update_per_service', violation_error_message='There is an existing noncompleted job for this service.'),
        ),
        migrations.AddIndex(
            model_name='featuretypemapping',
            index=models.Index(fields=['created'], name='registry_fe_created_7f52d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='featuretypemapping',
            constraint=models.UniqueConstraint(fields=('job', 'new_featuretype'), name='unique_new_featuretype_per_job_in_mapping', violation_error_message='A new feature type can only be mapped once. Please adjust the feature type mappings accordingly.'),
        ),
        migrations.AddConstraint(
            model_name='featuretypemapping',
            constraint=models.CheckConstraint(condition=models.Q(('new_featuretype__isnull', True), ('old_featuretype__isnull', True), _negated=True), name='prevent_both_featuretypes_null'),
        ),
    ]
