# Generated by Django 5.1.2 on 2024-12-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_alter_backgroundprocess_done_steps_and_more'),
        ('registry', '0006_historicalharvestingjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestingjob',
            name='step_size',
        ),
        migrations.RemoveField(
            model_name='historicalharvestingjob',
            name='step_size',
        ),
        migrations.AddField(
            model_name='catalogueservice',
            name='max_step_size',
            field=models.IntegerField(default=50, help_text='the maximum step size this csw can handle by a single GetRecords request.', verbose_name='max step size'),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='max_step_size',
            field=models.IntegerField(default=50, help_text='the maximum step size this csw can handle by a single GetRecords request.', verbose_name='max step size'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='background_process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.backgroundprocess'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='background_process',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notify.backgroundprocess'),
        ),
    ]
