# Generated by Django 3.2.9 on 2022-02-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20220203_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapcontext',
            options={'ordering': ['title']},
        ),
    ]
