# Generated by Django 6.0.8 on 2026-09-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('registry', '0007_catalogueserviceupdateconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebMapServiceUpdateSetting',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('service', models.ForeignKey(help_text='this is the service which shall be updated', on_delete=django.db.models.deletion.CASCADE, related_name='web_map_service_update_settings', related_query_name='web_map_service_update_setting', to='registry.webmapservice', verbose_name='web map service')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
