# Generated by Django 3.2.7 on 2021-10-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20211018_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontextlayer',
            name='layer_style',
            field=models.ForeignKey(blank=True, help_text='Select a style for rendering.', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.style', verbose_name='Style'),
        ),
    ]
