# Generated by Django 5.1.2 on 2025-02-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_backgroundprocess_done_at'),
        ('registry', '0007_remove_harvestingjob_step_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestingjob',
            name='background_process',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.backgroundprocess'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='background_process',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notify.backgroundprocess'),
        ),
    ]
