# Generated by Django 4.0.4 on 2022-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_alter_allowedwebfeatureserviceoperation_allowed_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcatalougeservice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical catalouge service', 'verbose_name_plural': 'historical catalouge services'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeaturetype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical feature type', 'verbose_name_plural': 'historical feature types'},
        ),
        migrations.AlterModelOptions(
            name='historicallayer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical layer', 'verbose_name_plural': 'historical layers'},
        ),
        migrations.AlterModelOptions(
            name='historicalmapcontext',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical map context', 'verbose_name_plural': 'historical map contexts'},
        ),
        migrations.AlterModelOptions(
            name='historicalmapcontextlayer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical map context layer', 'verbose_name_plural': 'historical map context layers'},
        ),
        migrations.AlterModelOptions(
            name='historicalwebfeatureservice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical web feature service', 'verbose_name_plural': 'historical web feature services'},
        ),
        migrations.AlterModelOptions(
            name='historicalwebmapservice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical web map service', 'verbose_name_plural': 'historical web map services'},
        ),
        migrations.AlterField(
            model_name='historicalcatalougeservice',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmapcontext',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmapcontextlayer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
