# Generated by Django 6.0.8 on 2026-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_webmapserviceupdatesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestedmetadatarelation',
            name='collecting_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'updated'), (3, 'existing'), (4, 'removed'), (0, 'duplicated')]),
        ),
    ]
