# Generated by Django 5.1.6 on 2025-02-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_getcapabilitiesprobe_check_response_does_not_contain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymdmetadatafile',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_md_metadata_files', related_query_name='temporary_md_metadata_file', to='registry.harvestingjob', verbose_name='harvesting job'),
        ),
    ]
