# Generated by Django 4.1.3 on 2022-11-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_historicalcatalougeservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTypeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_occurs', models.IntegerField(default=1, help_text='The maximum count this property is part of a feature type')),
                ('min_occurs', models.IntegerField(default=0, help_text='The minimum count this property is part of a feature type')),
                ('name', models.CharField(help_text='The identifing type name of the property', max_length=255)),
                ('data_type', models.CharField(blank=True, help_text='The concrete data type of this property', max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('feature_type', models.ForeignKey(editable=False, help_text='related feature type of this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='property', to='registry.featuretype', verbose_name='feature type')),
            ],
            options={
                'verbose_name': 'feature type property',
                'verbose_name_plural': 'feature type properties',
                'ordering': ['-name'],
            },
        ),
        migrations.DeleteModel(
            name='FeatureTypeElement',
        ),
    ]
