# Generated by Django 6.0.8 on 2026-10-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('registry', '0009_harvested_record_removals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueServiceUpdateSetting',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('service', models.ForeignKey(help_text='this is the service which shall be updated', on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_service_update_settings', related_query_name='catalogue_service_update_setting', to='registry.catalogueservice', verbose_name='catalogue service')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='WebFeatureServiceUpdateSetting',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('service', models.ForeignKey(help_text='this is the service which shall be updated', on_delete=django.db.models.deletion.CASCADE, related_name='web_feature_service_update_settings', related_query_name='web_feature_service_update_setting', to='registry.webfeatureservice', verbose_name='web feature service')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
