# Generated by Django 5.1.6 on 2025-02-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_alter_temporarymdmetadatafile_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestingjob',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='harvestingjob',
            name='registry_harvestingjob_service_done_at_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='harvestingjob',
            name='registry_harvestingjob_service_uniq',
        ),
        migrations.RemoveField(
            model_name='harvestingjob',
            name='done_at',
        ),
        migrations.RemoveField(
            model_name='harvestingjob',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='historicalharvestingjob',
            name='done_at',
        ),
        migrations.RemoveField(
            model_name='historicalharvestingjob',
            name='started_at',
        ),
    ]
