# Generated by Django 3.2.7 on 2021-10-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_alter_mapcontextlayer_rendering_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontextlayer',
            name='selection_layer',
            field=models.ForeignKey(blank=True, help_text='Select a layer for feature selection.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapcontextlayers_selection', to='registry.layer', verbose_name='Selection layer'),
        ),
        migrations.AlterField(
            model_name='mapcontextlayer',
            name='rendering_layer',
            field=models.ForeignKey(blank=True, help_text='Select a layer for rendering.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapcontextlayers_rendering', to='registry.layer', verbose_name='Rendering layer'),
        ),
    ]
