# Generated by Django 4.1.3 on 2022-12-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_featuretypeproperty_delete_featuretypeelement'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='layer',
            index_together={('tree_id', 'lft', 'rght')},
        ),
    ]
