# Generated by Django 6.0.8 on 2026-10-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_catalogueserviceupdatesetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmapservicemonitoringrun',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.webmapservicemonitoringsetting'),
        ),
    ]
