# Generated by Django 6.0.8 on 2026-10-07 08:19

import django_pgviews.db.migrations.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_webmapservicemonitoringrun_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedLayerStatsPerDayAndService',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('service', models.UUIDField()),
            ],
            options={
                'managed': False,
            },
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name='MaterializedLayerStatsPerDayAndService',
            materialized=True,
            db_name='registry_materializedlayerstatsperdayandservice',
        ),
    ]
