# Generated by Django 5.1.7 on 2025-03-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_remove_harvestingjob_existing_dataset_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvesteddatasetmetadatarelation',
            name='download_duration',
            field=models.DurationField(blank=True, help_text='This is the duration it tooked proportionately to download this record. This means if the GetRecords response contains 50 records for example, the request duration was 50 * self.download_durationTo get the download duration over all for one harvesting job, aggregate this col.', null=True, verbose_name='download duration'),
        ),
        migrations.AddField(
            model_name='harvesteddatasetmetadatarelation',
            name='processing_duration',
            field=models.DurationField(blank=True, help_text='This is the duration it tooked to handle the processing of creating or updating this record.', null=True, verbose_name='processing duration'),
        ),
        migrations.AddField(
            model_name='harvestedservicemetadatarelation',
            name='download_duration',
            field=models.DurationField(blank=True, help_text='This is the duration it tooked proportionately to download this record. This means if the GetRecords response contains 50 records for example, the request duration was 50 * self.download_durationTo get the download duration over all for one harvesting job, aggregate this col.', null=True, verbose_name='download duration'),
        ),
        migrations.AddField(
            model_name='harvestedservicemetadatarelation',
            name='processing_duration',
            field=models.DurationField(blank=True, help_text='This is the duration it tooked to handle the processing of creating or updating this record.', null=True, verbose_name='processing duration'),
        ),
        migrations.AddField(
            model_name='harvestingjob',
            name='max_step_size',
            field=models.IntegerField(default=50, help_text='the maximum step size this csw can handle by a single GetRecords request.', verbose_name='max step size'),
        ),
        migrations.AddField(
            model_name='historicalharvestingjob',
            name='max_step_size',
            field=models.IntegerField(default=50, help_text='the maximum step size this csw can handle by a single GetRecords request.', verbose_name='max step size'),
        ),
        migrations.AddField(
            model_name='temporarymdmetadatafile',
            name='download_duration',
            field=models.DurationField(blank=True, help_text='This is the duration it tooked proportionately to download this record. This means if the GetRecords response contains 50 records for example, the request duration was 50 * self.download_duration', null=True, verbose_name='download duration'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='service',
            field=models.ForeignKey(help_text='the csw for that this job is running', on_delete=django.db.models.deletion.CASCADE, related_name='harvesting_jobs', related_query_name='harvesting_job', to='registry.catalogueservice', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='the csw for that this job is running', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='harvesting_job', to='registry.catalogueservice', verbose_name='service'),
        ),
    ]
