# Generated by Django 5.1.7 on 2025-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_harvesteddatasetmetadatarelation_download_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvesteddatasetmetadatarelation',
            name='requested_url',
            field=models.URLField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='harvestedservicemetadatarelation',
            name='requested_url',
            field=models.URLField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='temporarymdmetadatafile',
            name='requested_url',
            field=models.URLField(max_length=4096, null=True),
        ),
    ]
