# Generated by Django 5.1.7 on 2025-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_harvesteddatasetmetadatarelation_requested_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvesteddatasetmetadatarelation',
            name='requested_url',
        ),
        migrations.RemoveField(
            model_name='harvestedservicemetadatarelation',
            name='requested_url',
        ),
        migrations.AddField(
            model_name='temporarymdmetadatafile',
            name='request_id',
            field=models.DateTimeField(null=True),
        ),
    ]
