# Generated by Django 5.1.7 on 2025-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_remove_harvesteddatasetmetadatarelation_requested_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datasetmetadatarecord',
            name='registry_datasetmetadatarecord_unique_together_code__and_code_space',
        ),
        migrations.RemoveConstraint(
            model_name='servicemetadatarecord',
            name='registry_servicemetadatarecord_unique_together_code__and_code_space',
        ),
        migrations.AddConstraint(
            model_name='datasetmetadatarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), ('code_space', ''), _negated=True), fields=('file_identifier', 'code', 'code_space'), name='registry_datasetmetadatarecord_unique_together_code__and_code_space'),
        ),
        migrations.AddConstraint(
            model_name='servicemetadatarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), ('code_space', ''), _negated=True), fields=('file_identifier', 'code', 'code_space'), name='registry_servicemetadatarecord_unique_together_code__and_code_space'),
        ),
    ]
