# Generated by Django 5.1.7 on 2025-03-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_remove_datasetmetadatarecord_registry_datasetmetadatarecord_unique_together_code__and_code_space_and'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestingjob',
            name='service',
            field=models.ForeignKey(help_text='the csw for that this job is running', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvesting_jobs', related_query_name='harvesting_job', to='registry.catalogueservice', verbose_name='service'),
        ),
    ]
