# Generated by Django 5.1.7 on 2025-03-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_alter_harvestingjob_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymdmetadatafile',
            name='has_import_error',
            field=models.BooleanField(default=False, editable=False, help_text="signals if this object can't be imported"),
        ),
    ]
