# Generated by Django 5.1.7 on 2025-04-03 10:36

import registry.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_remove_harvestedservicemetadatarelation_harvesting_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueservice',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='datasetmetadatarecord',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetmetadatarecord',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturetype',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicalservicemetadatarecord',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='xml_backup_file',
            field=models.TextField(help_text='the original xml as backup to restore the xml field.', max_length=100, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='servicemetadatarecord',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='xml_backup_file',
            field=models.FileField(help_text='the original xml as backup to restore the xml field.', upload_to=registry.models.document.xml_backup_file_path, verbose_name='xml backup'),
        ),
        migrations.AddIndex(
            model_name='harvestedmetadatarelation',
            index=models.Index(fields=['harvesting_job', 'id'], name='registry_ha_harvest_d15840_idx'),
        ),
        migrations.AddIndex(
            model_name='temporarymdmetadatafile',
            index=models.Index(fields=['job_id', '-id'], name='registry_te_job_id_5e81a1_idx'),
        ),
    ]
