# Generated by Django 5.1.7 on 2025-04-15 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_harvestinglog_alter_harvestingjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingjob',
            name='celery_task_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, editable=False, size=None),
        ),
        migrations.AddField(
            model_name='historicalharvestingjob',
            name='celery_task_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='done_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datetime field when the process was completed in UTC', null=True, verbose_name='Completed DateTime'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='phase',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'pending'), (1, 'get total records count'), (2, 'download records'), (3, 'records to db'), (4, 'completed'), (5, 'aborted'), (4711, 'abort')], default=0, help_text='Current phase of the process', verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='harvestinglog',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Fatal'), (1, 'Error'), (2, 'Warning'), (3, 'Info'), (4, 'Debug')], default=3),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='done_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datetime field when the process was completed in UTC', null=True, verbose_name='Completed DateTime'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='phase',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'pending'), (1, 'get total records count'), (2, 'download records'), (3, 'records to db'), (4, 'completed'), (5, 'aborted'), (4711, 'abort')], default=0, help_text='Current phase of the process', verbose_name='phase'),
        ),
    ]
