# Generated by Django 5.1.7 on 2025-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_harvestingjob_celery_task_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestingjob',
            name='max_step_size',
            field=models.PositiveSmallIntegerField(default=50, help_text='the maximum step size this csw can handle by a single GetRecords request.', verbose_name='max step size'),
        ),
        migrations.AlterField(
            model_name='harvestingjob',
            name='total_records',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='total count of records which will be harvested by this job', null=True, verbose_name='total records'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='max_step_size',
            field=models.PositiveSmallIntegerField(default=50, help_text='the maximum step size this csw can handle by a single GetRecords request.', verbose_name='max step size'),
        ),
        migrations.AlterField(
            model_name='historicalharvestingjob',
            name='total_records',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='total count of records which will be harvested by this job', null=True, verbose_name='total records'),
        ),
    ]
