# Generated by Django 5.1.7 on 2025-07-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_alter_catalogueservice_xml_backup_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicharvestingjob',
            name='service',
            field=models.ForeignKey(help_text='this is the service which shall be harvested', on_delete=django.db.models.deletion.CASCADE, related_name='periodic_harvesting_jobs', related_query_name='periodic_harvesting_job', to='registry.catalogueservice', verbose_name='catalogue service'),
        ),
    ]
