# Generated by Django 5.1.7 on 2025-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_alter_periodicharvestingjob_service'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='harvestingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('done_at__isnull', True)), fields=('service',), name='only_one_unfinished_job_per_service', violation_error_message='There is an existing noncompleted job for this service.'),
        ),
    ]
