# Generated by Django 5.2.4 on 2025-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_harvestingjob_only_one_unfinished_job_per_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalcatalogueservice',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicaldatasetmetadatarecord',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalfeaturetype',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicalfeaturetype',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalfeaturetype',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalfeaturetype',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalharvestingjob',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicalharvestingjob',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalharvestingjob',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalharvestingjob',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalservicemetadatarecord',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalwebfeatureservice',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='history_day',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='TIMEZONE', output_field=models.DateField(), template="(%(function)s('EUROPE/BERLIN', %(expressions)s))::date"), output_field=models.DateField()),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='history_month',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(MONTH FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='history_week',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(WEEK FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
        migrations.AddField(
            model_name='historicalwebmapservice',
            name='history_year',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Func(models.F('history_date'), function='EXTRACT', output_field=models.IntegerField(), template="EXTRACT(YEAR FROM (TIMEZONE('EUROPE/BERLIN', %(expressions)s)))"), output_field=models.IntegerField()),
        ),
    ]
