# Generated by Django 5.2.6 on 2025-10-01 07:15

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt2', '0001_initial'),
        ('registry', '0028_harvestedmetadatarelation_history_date_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='LayerTimeExtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('timerange', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('resolution', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='dataset_metadata',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='feature_type',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='timeextent',
            name='dimension',
        ),
        migrations.AddIndex(
            model_name='featuretype',
            index=django.contrib.postgres.indexes.GistIndex(condition=models.Q(
                ('bbox_lat_lon__isnull', False)), fields=['bbox_lat_lon'], name='featuretype_bbox_not_null'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=django.contrib.postgres.indexes.GistIndex(condition=models.Q(
                ('bbox_lat_lon__isnull', False)), fields=['bbox_lat_lon'], name='layer_bbox_not_null'),
        ),
        migrations.AddField(
            model_name='layertimeextent',
            name='layer',
            field=models.ForeignKey(help_text='the related layer of this time dimension entity', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='time_extents', related_query_name='time_extent', to='registry.layer', verbose_name='layer'),
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
        migrations.DeleteModel(
            name='TimeExtent',
        ),
        migrations.AddIndex(
            model_name='layertimeextent',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['timerange'], name='registry_la_timeran_38cdf2_gist'),
        ),
        migrations.AddIndex(
            model_name='layertimeextent',
            index=models.Index(
                fields=['layer', 'timerange'], name='registry_la_layer_i_2250f7_idx'),
        ),
    ]
