# Generated by Django 5.2.6 on 2025-10-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_layertimeextent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedHarvestingStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('service', models.UUIDField()),
                ('harvesting_job', models.IntegerField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('existed', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='catalogueservice',
            name='version',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.0.0'), (11, '1.1.0'), (111, '1.1.1'), (130, '1.3.0'), (200, '2.0.0'), (202, '2.0.2')], editable=False, help_text='the version of the service type as sem version', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='catalogueserviceoperationurl',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Get'), (2, 'Post')], help_text='the http method you can perform for this url', verbose_name='http method'),
        ),
        migrations.AlterField(
            model_name='catalogueserviceoperationurl',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GetCapabilities'), (2, 'GetMap'), (3, 'GetFeatureInfo'), (4, 'DescribeLayer'), (5, 'GetLegendGraphic'), (6, 'GetStyles'), (7, 'PutStyles'), (8, 'GetFeature'), (9, 'Transaction'), (10, 'LockFeature'), (11, 'DescribeFeatureType'), (12, 'GetFeatureWithLock'), (13, 'GetGmlObject'), (14, 'ListStoredQueries'), (15, 'GetPropertyValue'), (16, 'DescribeStoredQueries'), (17, 'GetRecords'), (18, 'DescribeRecord'), (19, 'GetRecordById')], help_text='the operation you can perform with this url.', verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='getcapabilitiesproberesult',
            name='status_code',
            field=models.SmallIntegerField(blank=True, default=None, editable=False, help_text='The http status code of the response', null=True, verbose_name='HTTP status code'),
        ),
        migrations.AlterField(
            model_name='getmapproberesult',
            name='status_code',
            field=models.SmallIntegerField(blank=True, default=None, editable=False, help_text='The http status code of the response', null=True, verbose_name='HTTP status code'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogueservice',
            name='version',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.0.0'), (11, '1.1.0'), (111, '1.1.1'), (130, '1.3.0'), (200, '2.0.0'), (202, '2.0.2')], editable=False, help_text='the version of the service type as sem version', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='historicalwebfeatureservice',
            name='version',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.0.0'), (11, '1.1.0'), (111, '1.1.1'), (130, '1.3.0'), (200, '2.0.0'), (202, '2.0.2')], editable=False, help_text='the version of the service type as sem version', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='historicalwebmapservice',
            name='version',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.0.0'), (11, '1.1.0'), (111, '1.1.1'), (130, '1.3.0'), (200, '2.0.0'), (202, '2.0.2')], editable=False, help_text='the version of the service type as sem version', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='webfeatureservice',
            name='version',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.0.0'), (11, '1.1.0'), (111, '1.1.1'), (130, '1.3.0'), (200, '2.0.0'), (202, '2.0.2')], editable=False, help_text='the version of the service type as sem version', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='webfeatureserviceoperation',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(8, 'GetFeature'), (9, 'Transaction')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webfeatureserviceoperationurl',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Get'), (2, 'Post')], help_text='the http method you can perform for this url', verbose_name='http method'),
        ),
        migrations.AlterField(
            model_name='webfeatureserviceoperationurl',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GetCapabilities'), (2, 'GetMap'), (3, 'GetFeatureInfo'), (4, 'DescribeLayer'), (5, 'GetLegendGraphic'), (6, 'GetStyles'), (7, 'PutStyles'), (8, 'GetFeature'), (9, 'Transaction'), (10, 'LockFeature'), (11, 'DescribeFeatureType'), (12, 'GetFeatureWithLock'), (13, 'GetGmlObject'), (14, 'ListStoredQueries'), (15, 'GetPropertyValue'), (16, 'DescribeStoredQueries'), (17, 'GetRecords'), (18, 'DescribeRecord'), (19, 'GetRecordById')], help_text='the operation you can perform with this url.', verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='webmapservice',
            name='version',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.0.0'), (11, '1.1.0'), (111, '1.1.1'), (130, '1.3.0'), (200, '2.0.0'), (202, '2.0.2')], editable=False, help_text='the version of the service type as sem version', verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='webmapserviceoperation',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(2, 'GetMap'), (3, 'GetFeatureInfo')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webmapserviceoperationurl',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Get'), (2, 'Post')], help_text='the http method you can perform for this url', verbose_name='http method'),
        ),
        migrations.AlterField(
            model_name='webmapserviceoperationurl',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GetCapabilities'), (2, 'GetMap'), (3, 'GetFeatureInfo'), (4, 'DescribeLayer'), (5, 'GetLegendGraphic'), (6, 'GetStyles'), (7, 'PutStyles'), (8, 'GetFeature'), (9, 'Transaction'), (10, 'LockFeature'), (11, 'DescribeFeatureType'), (12, 'GetFeatureWithLock'), (13, 'GetGmlObject'), (14, 'ListStoredQueries'), (15, 'GetPropertyValue'), (16, 'DescribeStoredQueries'), (17, 'GetRecords'), (18, 'DescribeRecord'), (19, 'GetRecordById')], help_text='the operation you can perform with this url.', verbose_name='operation'),
        ),
        migrations.CreateModel(
            name='MaterializedCatalogueServiceStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_45c1c1_idx'), models.Index(fields=['history_day'], name='registry_ma_history_a3ed53_idx'), models.Index(fields=['new'], name='registry_ma_new_bcea64_idx'), models.Index(fields=['updated'], name='registry_ma_updated_86f5c0_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_0359b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterializedDatasetMetadataRecordStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_3b76b7_idx'), models.Index(fields=['history_day'], name='registry_ma_history_0680a6_idx'), models.Index(fields=['new'], name='registry_ma_new_32b8e7_idx'), models.Index(fields=['updated'], name='registry_ma_updated_4ddcdf_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_84d485_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterializedFeatureTypeStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_7ed1ed_idx'), models.Index(fields=['history_day'], name='registry_ma_history_c8b26d_idx'), models.Index(fields=['new'], name='registry_ma_new_b81bc8_idx'), models.Index(fields=['updated'], name='registry_ma_updated_561b29_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_cd6cc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterializedLayerStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_c229d3_idx'), models.Index(fields=['history_day'], name='registry_ma_history_82a624_idx'), models.Index(fields=['new'], name='registry_ma_new_466854_idx'), models.Index(fields=['updated'], name='registry_ma_updated_99e320_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_2b3df9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterializedServiceMetadataRecordStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_6710ed_idx'), models.Index(fields=['history_day'], name='registry_ma_history_5f3365_idx'), models.Index(fields=['new'], name='registry_ma_new_3c5bd2_idx'), models.Index(fields=['updated'], name='registry_ma_updated_e0086a_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_322e82_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterializedWebFeatureServiceStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_45213f_idx'), models.Index(fields=['history_day'], name='registry_ma_history_54b8de_idx'), models.Index(fields=['new'], name='registry_ma_new_e849e4_idx'), models.Index(fields=['updated'], name='registry_ma_updated_fc2360_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_b7373a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterializedWebMapServiceStatsPerDay',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('history_day', models.DateField()),
                ('new', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='registry_ma_id_564aad_idx'), models.Index(fields=['history_day'], name='registry_ma_history_6f976d_idx'), models.Index(fields=['new'], name='registry_ma_new_b362ac_idx'), models.Index(fields=['updated'], name='registry_ma_updated_462240_idx'), models.Index(fields=['deleted'], name='registry_ma_deleted_c5367d_idx')],
            },
        ),
    ]
