# Generated by Django 5.2.6 on 2025-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt2', '0001_initial'),
        ('registry', '0030_materializedharvestingstatsperday_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='catalogueservice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='webfeatureservice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='webmapservice',
            managers=[
            ],
        ),
        migrations.AddConstraint(
            model_name='featuretype',
            constraint=models.UniqueConstraint(fields=('service', 'identifier'), name='unique_identifer_per_wfs'),
        ),
        migrations.AddConstraint(
            model_name='featuretype',
            constraint=models.UniqueConstraint(fields=('file_identifier',), name='registry_featuretype_unique_file_identifier'),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('service', 'identifier'), name='unique_identifer_per_wms'),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.CheckConstraint(condition=models.Q(('mptt_rgt__gt', models.F('mptt_lft'))), name='registry_layer_rgt_gt_lft'),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('file_identifier',), name='registry_layer_unique_file_identifier'),
        ),
    ]
