# Generated by Django 5.2.6 on 2025-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_alter_catalogueservice_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueserviceoperationurl',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GetCapabilities'), (20, 'GetMap'), (21, 'GetFeatureInfo'), (22, 'DescribeLayer'), (23, 'GetLegendGraphic'), (24, 'GetStyles'), (25, 'PutStyles'), (30, 'GetFeature'), (31, 'Transaction'), (32, 'LockFeature'), (33, 'DescribeFeatureType'), (34, 'GetFeatureWithLock'), (35, 'GetGmlObject'), (36, 'ListStoredQueries'), (37, 'GetPropertyValue'), (38, 'DescribeStoredQueries'), (39, 'CreateStoredQuery'), (40, 'DropStoredQuery'), (50, 'GetRecords'), (51, 'DescribeRecord'), (52, 'GetRecordById'), (53, 'GetDomain'), (54, 'GetRepositoryItem')], help_text='the operation you can perform with this url.', verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='webfeatureserviceoperation',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(30, 'GetFeature'), (31, 'Transaction')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webfeatureserviceoperationurl',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GetCapabilities'), (20, 'GetMap'), (21, 'GetFeatureInfo'), (22, 'DescribeLayer'), (23, 'GetLegendGraphic'), (24, 'GetStyles'), (25, 'PutStyles'), (30, 'GetFeature'), (31, 'Transaction'), (32, 'LockFeature'), (33, 'DescribeFeatureType'), (34, 'GetFeatureWithLock'), (35, 'GetGmlObject'), (36, 'ListStoredQueries'), (37, 'GetPropertyValue'), (38, 'DescribeStoredQueries'), (39, 'CreateStoredQuery'), (40, 'DropStoredQuery'), (50, 'GetRecords'), (51, 'DescribeRecord'), (52, 'GetRecordById'), (53, 'GetDomain'), (54, 'GetRepositoryItem')], help_text='the operation you can perform with this url.', verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='webmapserviceoperation',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(20, 'GetMap'), (21, 'GetFeatureInfo')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webmapserviceoperationurl',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GetCapabilities'), (20, 'GetMap'), (21, 'GetFeatureInfo'), (22, 'DescribeLayer'), (23, 'GetLegendGraphic'), (24, 'GetStyles'), (25, 'PutStyles'), (30, 'GetFeature'), (31, 'Transaction'), (32, 'LockFeature'), (33, 'DescribeFeatureType'), (34, 'GetFeatureWithLock'), (35, 'GetGmlObject'), (36, 'ListStoredQueries'), (37, 'GetPropertyValue'), (38, 'DescribeStoredQueries'), (39, 'CreateStoredQuery'), (40, 'DropStoredQuery'), (50, 'GetRecords'), (51, 'DescribeRecord'), (52, 'GetRecordById'), (53, 'GetDomain'), (54, 'GetRepositoryItem')], help_text='the operation you can perform with this url.', verbose_name='operation'),
        ),
    ]
