# Generated by Django 5.2.8 on 2026-03-02 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '1337_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeextent',
            name='kind_check',
        ),
        migrations.AlterField(
            model_name='isocategory',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'farming'), (2, 'biota'), (3, 'boundaries'), (4, 'climatologyMeteorologyAtmosphere'), (5, 'economy'), (6, 'elevation'), (7, 'environment'), (8, 'geoscientificInformation'), (9, 'health'), (10, 'imageryBaseMapsEarthCover'), (11, 'intelligenceMilitary'), (12, 'inlandWaters'), (13, 'location'), (14, 'oceans'), (15, 'planningCadastre'), (16, 'society'), (17, 'structure'), (18, 'transportation'), (19, 'utilitiesCommunication')], help_text='the topic category of the dataset', primary_key=True, serialize=False, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='timeextent',
            name='resolution',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='The resolution of the time extent. Null or 0 means infinite fine resolution.', verbose_name='resolution'),
        ),
        migrations.AddConstraint(
            model_name='timeextent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('begin', models.F('end'))), models.Q(('end__gte', models.F('begin')), ('is_relative', False)), models.Q(('begin__isnull', True), ('end__isnull', True), ('is_relative', True), ('resolution__gt', datetime.timedelta(0))), _connector='OR'), name='kind_check'),
        ),
    ]
