# Generated by Django 3.2.7 on 2021-12-02 14:01

from django.db import migrations
import users.managers.users


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mrmapuser',
            managers=[
                ('objects', users.managers.users.CustomUserManager()),
            ],
        ),
    ]
