# Generated by Django 3.1.8 on 2021-04-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210421_1457'),
        ('guardian_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrollist',
            name='organization',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='structure.organization'),
            preserve_default=False,
        ),
    ]
