# Generated by Django 3.1.7 on 2021-04-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardian_roles', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerbasedrole',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_based_roles', to='structure.organization'),
        ),
        migrations.AddField(
            model_name='ownerbasedrole',
            name='object_based_roles',
            field=models.ManyToManyField(blank=True, related_name='owner_set', related_query_name='owner', to='guardian_roles.ObjectBasedRole'),
        ),
    ]
