# Generated by Django 3.1.8 on 2021-04-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_roles', '0002_accesscontrollist_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='organization',
        ),
    ]
