# Generated by Django 3.1.7 on 2021-03-29 10:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210325_1509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('guardian', '0002_auto_20210325_1509'),
        ('structure', '0003_auto_20210329_1220'),
        ('users', '0002_auto_20210329_1220'),
        ('guardian_roles', '0003_auto_20210325_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBasedRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(help_text='Describe what permissions this role shall grant', verbose_name='Description')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('based_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_roles_objectbasedrole_concrete_template', to='guardian_roles.templaterole')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.group', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerBasedRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe what permissions this role shall grant', verbose_name='Description')),
                ('based_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_roles_ownerbasedrole_concrete_template', to='guardian_roles.templaterole')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_based_template_roles', to='structure.organization')),
                ('object_based_roles', models.ManyToManyField(blank=True, related_name='owner_set', related_query_name='owner', to='guardian_roles.ObjectBasedRole')),
                ('users', models.ManyToManyField(blank=True, help_text='The users this role belongs to. A user will get all permissions granted to each of their roles.', related_name='role_set', related_query_name='role', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ownerbasedtemplaterole',
            name='based_template',
        ),
        migrations.RemoveField(
            model_name='ownerbasedtemplaterole',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='ownerbasedtemplaterole',
            name='object_based_template_roles',
        ),
        migrations.RemoveField(
            model_name='ownerbasedtemplaterole',
            name='users',
        ),
        migrations.DeleteModel(
            name='ObjectBasedTemplateRole',
        ),
        migrations.DeleteModel(
            name='OwnerBasedTemplateRole',
        ),
    ]
