# Generated by Django 3.1.8 on 2021-04-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_generic_permissions_index'),
        ('service', '0002_auto_20210421_1457'),
        ('users', '0001_initial'),
        ('guardian_roles', '0003_auto_20210421_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerbasedrole',
            name='based_template',
        ),
        migrations.RemoveField(
            model_name='ownerbasedrole',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='ownerbasedrole',
            name='object_based_roles',
        ),
        migrations.RemoveField(
            model_name='ownerbasedrole',
            name='users',
        ),
        migrations.RemoveField(
            model_name='templaterole',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='ObjectBasedRole',
        ),
        migrations.DeleteModel(
            name='OwnerBasedRole',
        ),
        migrations.DeleteModel(
            name='TemplateRole',
        ),
    ]
