# Generated by Django 3.1.7 on 2021-03-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_roles', '0003_auto_20210322_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectbasedtemplaterole',
            name='based_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_roles_objectbasedtemplaterole_concrete_template', to='guardian_roles.templaterole'),
        ),
        migrations.AlterField(
            model_name='organizationbasedtemplaterole',
            name='based_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_roles_organizationbasedtemplaterole_concrete_template', to='guardian_roles.templaterole'),
        ),
    ]
