# Generated by Django 3.1.8 on 2021-04-23 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('guardian_roles', '0004_auto_20210423_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('members', models.ManyToManyField(blank=True, related_name='acls', to=settings.AUTH_USER_MODEL)),
                ('objects', models.ManyToManyField(blank=True, to='guardian_roles.ObjectRelation')),
                ('permissions', models.ManyToManyField(blank=True, related_name='acls', to='auth.Permission')),
            ],
        ),
    ]
