# Generated by Django 3.1.7 on 2021-03-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210329_1338'),
        ('guardian_roles', '0004_auto_20210329_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerbasedrole',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_based_roles', to='structure.organization'),
        ),
    ]
