# Generated by Django 3.1.8 on 2021-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_roles', '0005_accesscontrollist_objectrelation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='objectrelation',
            constraint=models.UniqueConstraint(fields=('object_pk', 'content_type'), name='guardian_roles_objectrelation_unique_together'),
        ),
    ]
