# Generated by Django 3.1.8 on 2021-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_roles', '0006_auto_20210423_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectrelation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='objectrelation',
            name='object_pk',
        ),
    ]
