# Generated by Django 3.1.8 on 2021-04-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('guardian_roles', '0007_auto_20210423_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='objects',
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='object_pk',
            field=models.CharField(default=None, max_length=255, verbose_name='object ID'),
            preserve_default=False,
        ),
    ]
