# Generated by Django 3.1.8 on 2021-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_roles', '0008_auto_20210423_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrollist',
            name='secured_objects',
            field=models.ManyToManyField(blank=True, to='guardian_roles.ObjectRelation'),
        ),
    ]
