# Generated by Django 3.1.8 on 2021-04-23 09:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('guardian_roles', '0009_accesscontrollist_secured_objects'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accesscontrollist',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='permissions',
        ),
        migrations.AddField(
            model_name='accesscontrollist',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectrelation',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='objectrelation',
            name='object_pk',
            field=models.CharField(editable=False, max_length=255, verbose_name='object ID'),
        ),
    ]
