# Generated by Django 3.1.8 on 2021-04-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_roles', '0010_auto_20210423_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrollist',
            name='members',
        ),
    ]
