name: build docs
on:
  workflow_dispatch:
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]

jobs:
  check-docs:
    name: build docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      # Install all system dependencies for the MrMap project
      # ===============================
      - name: Install System Dependencies for MrMap project
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libssl-dev \
          libcurl4-openssl-dev \
          gdal-bin \
      # Install sphinx local
      # ===============================
      - name: Install sphinx
        run: |
          sudo apt-get install python3-sphinx
      # Upgrade pip, setuptools and wheel
      # ===============================
      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install pip dependencies
        run: |
            pip3 install -r ./mrmap/requirements.txt && pip3 install -r ./docs/requirements.txt
      # ===============================
      # Build documentation
      # ===============================
      - name: build documentation
        run: |
          export $(grep -v '^#' .env.docs | xargs)
          sphinx-multiversion docs/source docs/build/html -b linkcheck -D smv_branch_whitelist='${GITHUB_REF##*/}'
          sphinx-multiversion docs/source docs/build/html -b html -E -D smv_branch_whitelist='${GITHUB_REF##*/}'
      # ===============================
