name: Publishing docs on github pages
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  check-docs:
    name: build docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install all system dependencies for the MrMap project
      # ===============================
      - name: Install System Dependencies for MrMap project
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libssl-dev \
          libcurl4-openssl-dev \
          gdal-bin \
          postgresql \
          postgresql-client \
          postgis \
          postgresql-server-dev-13 \
          postgresql-13-postgis-3 \
          postgresql-13-postgis-3-scripts \
          redis-server
      # Upgrade pip, setuptools and wheel
      # ===============================
      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install pip dependencies
        run: |
            pip3 install -r ./mrmap/requirements.txt
      # ===============================
      # Build documentation
      # ===============================
      - name: build documentation
        run: |
          cd docs/
          make linkcheck
          make html
      # ===============================
      # Publish built docs to gh-pages branch.
      # ===============================
      - name: Commit documentation changes
        run: |
            git clone https://github.com/${GITHUB_REPOSITORY}.git --branch gh-pages --single-branch gh-pages
            cp -r docs/build/html/* gh-pages/
            cd gh-pages
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update documentation" -a || true
            # The above command will fail if no changes were present, so we ignore
            # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # ===============================
