name: Quality Assurance
on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: 0 16 * * *
jobs:
  pre-commit-checks:
    name: pre-commit-checks
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run pre commit checks
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build --abort-on-container-exit --exit-code-from pre-commit-check pre-commit-check
      
  quality-assurance:
    name: quality-assurance
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract branch name
        uses: nelonoel/branch-name@v1.0.1
        id: extract_branch

      - name: Run behave tests
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build --abort-on-container-exit --exit-code-from behave behave
      
      - name: Run sonar-scanner
        run: |
          echo "sonar.branch.name=$GITHUB_HEAD_REF" >> ./backend/sonar-project.properties
          echo "sonar.branch.target=$GITHUB_BASE_REF" >> ./backend/sonar-project.properties
          echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> ./backend/sonar-project.properties          
          GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}' docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build --abort-on-container-exit --exit-code-from sonar-scanner sonar-scanner
