name: Sonar
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: 0 16 * * *
jobs:
  sonarcloud:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - name: Set up postgres
        run: |
          sudo sed -i "/host    all             all             127.0.0.1/32            md5/c host    all             all             127.0.0.1/32            trust" /etc/postgresql/13/main/pg_hba.conf
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract branch name
        uses: nelonoel/branch-name@v1.0.1
        id: extract_branch
      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libssl-dev \
          libcurl4-openssl-dev \
          gdal-bin
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.branch.name=${env.BRANCH_NAME}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'